- packages/react-app/tsconfig.json
Note this might be a temporary workaround.
Reason: CRA automatically updates `tsconfig.json` and forces `isolatedModules: true` config. (see https://github.com/facebook/create-react-app/issues/5508)
We have the react app's tsconfig extend our base sdk config, which has `"declaration": true` set. That couldn't co-exist with `isolatedModules`.
This has resulted: 1, TypeScript would complain about the config. 2, if we remove `isolatedModules` CRA adds it back and changes the tsconfig file every time we run the app.
Until we have a more elegant tsconfig setup let have all compiler options in the tsconfig.json file (some of them might be the same to default value but I didn't bother double checking them).
> Move all extended tsconfig settings to react-app

- packages/neuron-wallet/package.json
- packages/neuron-wallet/src/main.ts
* Remember and restore window position and size.
* Set default window size to 1366x768, which covers most desktop computers.
* Hook `window-all-closed` event though we don't have multiple windows.
> Manage window properties/state

- packages/neuron-ui/src/components/Dialog/index.tsx
This dialog could be used in this method:
```javascript
<Dialog open>
<div>My Dialog Content</div>
</Dialog>
```
And this is a rough one, we should add more interaction like `backdrop` click or sth on it.
> feat(neuron-ui): add stateless dialog

- .travis.yml
- package.json
Which fixes tiny-secp256k1 symbol not found issue on macOS.
Fix #77.
> chore(deps): require node 11.10

- packages/neuron-wallet/electron-builder.yml
Generally, electron-builder set default naming conventions on three platforms and different from each other.
And I'm not found common naming conventions, like `* ${productName}-${version}.${ext}` `${productName}-Setup-${version}-${arch}.${ext}`  and so on.
So, I think we can decide what we should custom package name.
> feat: add package naming conventions

- packages/neuron-wallet/src/main.ts
Should call the method to fetch the locale.
> fix: get locale from electron app

- .eslintrc.js
- packages/neuron-ui/src/components/History/TablePagination.tsx
- packages/neuron-ui/src/components/History/index.tsx
- packages/neuron-ui/src/widgets/Table/Pagination.tsx
- packages/neuron-ui/src/widgets/Table/index.tsx
> feat(neuron-ui): optimize pagination ui

- packages/neuron-wallet/package.json
"electron-window-state" should be a runtime dependency.
> fix: move `electron-window-state` back to dependencies

- packages/neuron-wallet/src/channel/index.ts
- packages/neuron-wallet/src/monitor.ts
the auto-dismiss leads [this problem](https://github.com/nervosnetwork/neuron/issues/152), notification objects cleaned before the callbacks.
> feat(neuron-wallet): remove useless notification

- .eslintrc.js
eslint will take it as a global function once it's on staging 4
> chore: enable BigInt as a global variable

- packages/neuron-ui/.env.example
@Keith-CY I guess we no longer use this?
> chore: delete .env.example file

- packages/neuron-wallet/package.json
- yarn.lock
`@types/electron` has been deprecated, see https://www.npmjs.com/package/@types/electron for more info.
> chore: remove useless `@types/electron`

- packages/neuron-ui/src/components/Settings/Wallets.tsx
fix: the settings TAB is disappeared when click 'Wallets'
> refactor: wallet manager add pagination

- packages/neuron-wallet/src/entities/Input.ts
- packages/neuron-wallet/src/entities/Output.ts
- packages/neuron-wallet/src/entities/Transaction.ts
- packages/neuron-wallet/src/services/transactions.ts
1. implement `getAll`, `getAllByAddresses`, `getAllByPubkeys`
2. add static methods `addressToLockScript` and `addressToLockHash` to `TransactionsService`
3. calculate `capacity` and `lockHash` of `InputEntity` when save
4. remove `value` and `type` from `TransactionEntity`
5. calculate `value` and `type` by `params.lockHashes` when in `getAll`, `getAllByAddresses`, `getAllByPubkeys`
> chore: impl getAll in TransactionsService

- packages/neuron-ui/src/components/History/index.tsx
- packages/neuron-ui/src/components/Receive/index.tsx
- packages/neuron-ui/src/components/WalletWizard/index.tsx
- packages/neuron-ui/src/containers/Providers/hooks.ts
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/utils/parser.ts
- packages/neuron-wallet/src/controllers/transactions.ts
1. clear data when switching between wizard subviews
2. add more response info in get-history API
> refactor wizard and history view

- packages/neuron-ui/src/components/Transfer/hooks.ts
- packages/neuron-ui/src/components/Transfer/index.tsx
- packages/neuron-ui/src/containers/MainContent/actionCreators/transfer.ts
- packages/neuron-ui/src/containers/Providers/hooks.ts
- packages/neuron-ui/src/services/UILayer.ts
- packages/neuron-ui/src/utils/const.ts
- packages/neuron-ui/src/widgets/BannerMessages/index.tsx
- packages/neuron-ui/src/widgets/QRScanner/index.tsx
- packages/neuron-wallet/src/channel/listeners.ts
- packages/neuron-wallet/src/controllers/wallets.ts
- packages/neuron-wallet/src/services/wallets.ts
1. remove the sendCapacity listener and use the wallet controller to handle the send capacity request.
2. add id in send capacity request for identify requests.
3. when the transaction fails, display an error message in Transfer View
4. when the transaction succeeds, navigate to the Transaction View.
5. add a type of `{content: string, id: string}` to error message in response to identify requests.
5. update basic address verification in neuron-ui, it should have the length of 50
6. use codeHash of `0x0000000000000000000000000000000000000000000000000000000000000001` in the wallet service to make lockhashes, it will be deprecated soon, should be updated.
> NOTICE: the interfaces between wallet service and transaction service are incompatible now.
> Enable send transaction

- packages/neuron-ui/src/containers/Sidebar/index.tsx
- packages/neuron-ui/src/styles/layout.scss
Hide the sidebar when wallets.length ===0
This behavior differs from the launch screen and wizard, which hide both of header bar and sidebar.
> feat(neuron-ui): make sidebar invisible when wallets.length === 0

- packages/neuron-wallet/src/keys/hd.ts
- packages/neuron-wallet/src/services/addresses.ts
- packages/neuron-wallet/tests/services/address.test.ts
See https://github.com/satoshilabs/slips/pull/621. 🍻
> Register and use cointype `309` for BIP44

- packages/neuron-wallet/src/services/cells.ts
- packages/neuron-wallet/src/services/networks.ts
- packages/neuron-wallet/src/services/node.ts
- packages/neuron-wallet/src/services/syncBlocks.ts
- packages/neuron-wallet/src/services/transactions.ts
- packages/neuron-wallet/src/startup/loopTask/create.ts
1. cache `blockHeaderForCheck`
2. cache `currentBlockNumber`
3. listen `tipBlockNumber` by `nodeService` to replace monitor by self
4. listen to network switch
5. reduce fetch size when failed 3 times in a row
> Refactor sync blocks

- package.json
- yarn.lock
We should soon consider 3.5.0 RC too, as it claims to fix regression brought by 3.4.
> Bump TypeScript to 3.4.5

- .travis.yml
Configure Travis to run Node 11/12 on Ubuntu 16.04/macOS. (4 jobs)
> chore(ci): Add Node 12

- packages/neuron-wallet/src/env.ts
- packages/neuron-wallet/src/utils/logger.ts
fileBasePath pointer to `dev` when packaged, logger only works in main process
> fix: fileBasePath and logger bugs

- packages/neuron-wallet/package.json
Some tests (e.g., HD key derivation) are very slow which makes the pre commit check take too long. Remove that; we always run tests locally frequently and let's delegate that to CI to catch if we miss the green before committing.
> chore: Skip neuron-wallet test on commit

- packages/neuron-ui/src/containers/Sidebar/index.tsx
They are lost in the refactoring of https://github.com/nervosnetwork/neuron/commit/1a6afb5c05c529dc0bd38e3d3d5d50d4bb247d93#diff-4bbaf8c600de7dee442ac266d55cbda7R64
> fix(neuron-ui): display icons of sidebar items

- packages/neuron-wallet/src/services/addresses.ts
- packages/neuron-wallet/src/services/file.ts
- packages/neuron-wallet/src/services/networks.ts
- packages/neuron-wallet/src/services/node.ts
- packages/neuron-wallet/src/services/sync-blocks.ts
- packages/neuron-wallet/src/services/transactions.ts
- packages/neuron-wallet/src/services/wallets.ts
- packages/neuron-wallet/src/startup/init-app.ts
- packages/neuron-wallet/src/startup/sync-block-task/create.ts
- packages/neuron-wallet/src/utils/lock-utils.ts
- packages/neuron-wallet/src/utils/store.ts
- packages/neuron-wallet/tests/services/address.test.ts
Use `XxxService.getInstance()` instead of exposing a singleton constant.
> refactor: Unify singleton usage

- packages/neuron-ui/src/components/Receive/index.tsx
- packages/neuron-ui/src/components/Transaction/index.tsx
- packages/neuron-ui/src/components/WalletEditor/index.tsx
- packages/neuron-ui/src/components/WalletWizard/index.tsx
- packages/neuron-ui/src/containers/MainContent/actionCreators/networks.ts
- packages/neuron-ui/src/containers/Providers/hooks.ts
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/utils/validators.ts
remove unnecessary todo, and add some exception handlers.
> refactor(neuron-ui): clean todo in neuron-ui

- .travis.yml
To apply a more proper use of learn and avoid installing deps twice.
> chore(ci): Add lerna globally when running travis

- packages/neuron-ui/src/components/WalletWizard/index.tsx
It's a bug that the hint was placed under `name`.
> fix: Password field hint position

- .eslintignore
- jest.config.js
- packages/neuron-ui/package.json
- packages/neuron-wallet/package.json
Jest couldn't pick up neuron-ui tests as RCA has its own jest settings.
Note this doesn't affect our running `yarn test` manually. Only affects the vscode jest extension behavior.
> test: Update jest config to run only neuron-wallet tests automatically inside vscode

- packages/neuron-ui/src/components/Send/index.tsx
- packages/neuron-ui/src/containers/Providers/hooks.ts
- packages/neuron-ui/src/contexts/NeuronWallet/wallet.ts
- packages/neuron-ui/src/services/UILayer.ts
- packages/neuron-wallet/src/controllers/wallets/index.ts
the sending state should be set after verification of password, which happens in neuron-wallet, so a
message is required to display the loading view.
> refactor: update sending status of ui via neuron-wallet's messages

- packages/neuron-wallet/src/keys/keychain.ts
- packages/neuron-wallet/tests/keys/keychain.test.ts
This reverts commit 61a0e1491d7150c0e7092591ff9bdfe8af2797f7.
1. Buffer.from never accepts string with 0x prefixed hex string (as I observed).
2. 66 is length of string key, not buffer.
Let's keep stripping the 0x outside.
Original PR: https://github.com/nervosnetwork/neuron/pull/493
> Revert "refactor(neuron-wallet): slice '0x' in privateToPublic"

- packages/neuron-wallet/src/startup/sync-block-task/create.ts
- packages/neuron-wallet/src/startup/sync-block-task/params.ts
- packages/neuron-wallet/src/startup/sync-block-task/task.ts
Should listen new addresses saved, create wallet and insert addresses will happen after sync start, so will not include those until you restart now.
> feat: update lockHashes when new address generated

- packages/neuron-wallet/src/controllers/app/index.ts
fix the path to transaction detail dialog
> [ᚬrc/v0.1.0] refactor(neuron-wallet): remove slash before the transaction detail url

- packages/neuron-wallet/src/controllers/app/index.ts
fix the path to transaction detail dialog
> refactor(neuron-wallet): remove slash before the transaction detail url

- packages/neuron-wallet/src/database/address/dao.ts
- packages/neuron-wallet/src/listener/address.ts
- packages/neuron-wallet/src/main.ts
- packages/neuron-wallet/src/services/addresses.ts
- packages/neuron-wallet/src/services/wallets.ts
- packages/neuron-wallet/tests/services/address.test.ts
It will generate new addresses when addresses used out.
When `address` used, will broadcast a `addressUsedSubject` subject and subscribe this subject, when listened an address used, check the max `addressIndex` is used or not, if do, generate new addresses.
> feat: rescanning and expanding addresses when one type used out

- packages/neuron-wallet/src/listener/tx-status.ts
- packages/neuron-wallet/src/services/transactions.ts
- packages/neuron-wallet/src/startup/sync-block-task/task.ts
Load `pending` transactions and using RPC `getTransaction` to get new status, then update status to `failed` if return null, sync task will resolve `committed` transactions, do just kill these.
Will do this every 5 seconds. (May too short or too long ?)
Do this inside sync renderer process.
> feat: listen tx and update when failed

- .travis.yml
Travis should have yarn 1.15 or 1.16 pre installed already.
> chore(ci): Expect Travis to have yarn > 1.13 pre-installed

- packages/neuron-ui/src/containers/Main/hooks.ts
- packages/neuron-ui/src/services/UILayer.ts
update transaction list and current transaction if the updated one is displayed
- if the updated transaction has a timestamp of `null` and the page number is 1, insert it in the transaction list.
- if the updated transaction is listed in the transaction list, replace it directly
- if the updated transaction is the one displayed in the transaction detail view, update the transaction detail view.
> feat(neuron-ui): add TransactionUpdated listener

- packages/neuron-ui/src/components/Addresses/index.tsx
Ideally we could colorize the cell background, but we have yet to find how to do that (apply dynamic `className` to a column).
> feat: Apply color to adress type

- packages/neuron-ui/src/components/WalletWizard/index.tsx
We're styling the main content area with white background now. It doesn't look natural if the readonly text field doesn't show border.
We may want to use a custom border style for `readOnly` though.
> refactor: Show mnemonic field border even when it's readonly

- packages/neuron-ui/package.json
- packages/neuron-ui/src/components/WalletWizard/index.tsx
- packages/neuron-ui/src/utils/icons.ts
- yarn.lock
This allows us to use Grommet icons with Fabric buttons. Their sizes are different though, so we have to use `buttonGrommetIconStyles` for Fabric button's `iconProps` to adjust them to fit.
Note: we use Grommet icons as they are offline, while Fabric's icon sets are hosted from CDN.
> feat: Support registering grommet icons to be used as fabric icons

- packages/neuron-wallet/src/utils/logger.ts
Using userData if `getPath('logs')` throw errors. It will happen in linux.
> fix: using userData when logs dir failed

- packages/neuron-wallet/package.json
to allow running that on Windows
Note: it's fine to call `ncp` directly as there's only one html entry for now. If we need to copy multiple files we still need to think of calling a shell file, as putting several files copying in a single command makes it too long.
> feat: Do not call shell script from yarn start

- packages/neuron-ui/src/components/Receive/index.tsx
- packages/neuron-ui/src/components/Send/index.tsx
- packages/neuron-ui/src/components/TransactionFeePanel/index.tsx
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh.json
Give the send view some UI love.
Note: since we don't use office ui fabric's icon set, the dropdown button doesn't show the right side arrow. Perhaps should inject a grommet icon instead. Updated: done with e5c2210.
> feat: Polish send view fee panel

- packages/neuron-wallet/electron-builder.yml
The current Windows Installer has several issues:
* It acts as one installer, not giving user the option to select install directory.
* It runs Neuron right after installation, which is not friendly.
> feat: Make Windows installer as assisted installer

- azure-pipelines.yml
- packages/neuron-wallet/scripts/notarize.js
For reason unknown yet, from alpha 14 Azure Pipelines stopped building for release tags.
I believe this is a Azure Pipelines [issue](https://github.com/vega/ts-json-schema-generator/issues/49); But there is a stupid notarizing bug we need to fix here.
> chore: Specify release tags only for Azure Pipelines to build

- packages/neuron-ui/package.json
- packages/neuron-wallet/package.json
- yarn.lock
Note after this we'll track ckb/sdk version and set Neuron's version number accordingly.
> chore(deps): Bump ckb sdk to v0.16.0

- package.json
- packages/neuron-ui/package.json
- packages/neuron-wallet/package.json
* As installation path (especially on Windows) comes from `name` or `productName`, it's odd to have `@nervosnetworkneuron-wallet` (note `/` was removed) as user installation folder.
* `neuron-ui` and `neuron-wallet` are not supposed to be referenced and installed from NPM, so not scoping them with `@nervosnetwork` is not a big concern.
> refactor: Rename package names removing @nervosnetwork scope

- packages/neuron-wallet/dev-app-update.yml
- packages/neuron-wallet/electron-builder.yml
- packages/neuron-wallet/package.json
- yarn.lock
Troubleshoot Windows Code Signing Cert issue.
This requires two new versions to test. The first one to apply the `publisherName` change, the second to verify if updating works.
Note the sqlite3 change was checked in by mistake but let's just keep it. It's already cherry-picked to `electron-v6` branch.
> Improve updater

- packages/neuron-wallet/src/services/wallets.ts
If the current wallet is not set, the UI will request the previous wallet id on the wallet list updated.
> fix(neuron-wallet): set current wallet empty if wallet list is empty

- packages/neuron-ui/src/components/Transaction/index.tsx
- packages/neuron-ui/src/containers/Main/hooks.ts
- packages/neuron-ui/src/index.tsx
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/states/initStates/chain.ts
- packages/neuron-ui/src/states/stateProvider/actionCreators/transactions.ts
- packages/neuron-ui/src/states/stateProvider/reducer.ts
- packages/neuron-ui/src/types/App/index.d.ts
The transaction view is totally different from other views(no app states, no header, no footer) so it's better to make it independent.
The only thing it does is to fetch and render data, and close itself when the current wallet changes
> feat(neuron-ui): separate the transaction view from the app

- package.json
- packages/neuron-ui/tsconfig.json
- packages/neuron-wallet/tsconfig.json
- tsconfig.json
- yarn.lock
Rationale:
* Neuron is not a SDK; confirming to a `sdk-ts-config` is misleading.
* From time to time we need to adjust tsconfig. Having a config that's not depending on an external repo is more convenient.
We should also probably further tweaking this by removing unnecessary config items in tsconfig.json.
> Remove sdk ts config

- packages/neuron-ui/src/components/NetworkEditor/index.tsx
This fixed warning caused by https://github.com/nervosnetwork/neuron/pull/812#issuecomment-518045241.
> fix: Add cachedNetwork to useMemo depencency

- packages/neuron-wallet/electron-builder.yml
Windows update always fail due to cert issue. Our cert has Chinese company
name which might be not handled well by electron-updater.
Note as before, we won't be able to test this until next two alpha versions.
> chore: Disable verifying update code sign for Windows

- packages/neuron-wallet/package.json
- packages/neuron-wallet/src/database/chain/ormconfig.ts
- packages/neuron-wallet/src/startup/create-main-window.ts
- packages/neuron-wallet/src/utils/logger.ts
- yarn.lock
Winston has 10+ depencencies while electron-log zero.
Note: We also simplify log location and file name. Now we log to `electron-log`'s default location with file name `log.log`, and don't change log file path based on environment.
> feat: Remove winston logger in favor of electron-log

- packages/neuron-ui/src/components/History/hooks.ts
- packages/neuron-ui/src/components/Overview/index.tsx
- packages/neuron-ui/src/styles/index.scss
- packages/neuron-ui/src/utils/animations.ts
The scrollbar is hidden by chromium automatically, try to find a better indicator in the future.
UPDATED: add a custom scrollbar on the list
> fix(neuron-ui): handle overflow on recent activities

- packages/neuron-ui/src/components/Overview/index.tsx
- packages/neuron-ui/src/utils/const.ts
1. set the threshold of confirmations to 10.
2. display a recent activity as a pending one if its status is success while its confirmations is less the the threshold of confirmations.
> feat(neuron-ui): update confirmation threshold of confirmations

- packages/neuron-ui/src/components/ImportKeystore/index.tsx
Before this PR, there's only an alert message beneath the wallet name field, but the submit button is not disabled.
This PR prevent submission when the inputted wallet name is used.
> refactor(neuron-ui): disable submit button when the wallet name is used

- azure-pipelines.yml
- packages/neuron-wallet/package.json
- packages/neuron-wallet/src/controllers/app/index.ts
- packages/neuron-wallet/src/controllers/app/options.ts
- packages/neuron-wallet/src/controllers/update.ts
- packages/neuron-wallet/src/controllers/wallets/index.ts
- yarn.lock
* `dialog` APIs are promise based now, need to update usage.
* `ipcMain`'s `on` receives `IpcMainEvent`, not `Event`.
* Others?
* spectron hasn't released any update for electron v6 yet, e2e tests are behaving wrong
* sqlite3 native module build on Windows
* Others?
Due to Electron's API change (`dialog` etc), there might be some changes our tests don't cover.  It's ok to leave them as holes and fix ASAP.
> feat: Update Electron to v6

- packages/neuron-ui/src/components/PasswordRequest/index.tsx
Move the action `set loading to true` next to the parameter verification is unnecessary because there's another user-triggered confirmation after the verification and before the submission, which means it will not submit twice to the neuron-wallet.
This PR just stops double-submit on confirmation to send the transaction with a required password, namely, it stops sending the request to neuron-wallet repeatedly.
> fix(neuron-ui): disable the submit button when it's sending

- packages/neuron-wallet/src/models/lock-utils.ts
- packages/neuron-wallet/tests/models/lock-utils.test.ts
But hold interfaces and maybe address will map to multi lock hashes.
> chore: only use hash_type=Data when generate lock hash

- packages/neuron-ui/src/components/Send/hooks.ts
Set the `cycles` to `0` if the transaction to send is invalid.
> feat(neuron-ui): set the cycles to empty if the transaction is invalid

- packages/neuron-wallet/src/models/keys/keystore.ts
- packages/neuron-wallet/tests/models/keys/keystore.test.ts
Having two issues needing fix:
* Neuron doesn't seem to be able to handle CKB cli's standard keystore( `262144` of `n` param), resulting OPENSSL `MEMORY_LIMIT_EXCEEDED` error.
* Neuron keystore password logic has flaw.
We don't aim 100% compatibility. CKB CLI uses the master private key to derive mainnet/testnet addresses. Neuron on the other hand generates HD addresses (both receiving and change) with full path (`m/44'/309'/0'/0/n`, and `m/44'/309'/0'/1/n`).
This means the address you see from cli will NOT appear in Neuron.
One more thing, our Keystore format doesn't conform to Ethereum wallets in the way that we save the encrypted extended master key, not the encrypted master private key.
> Keystore compatibility with cli

- packages/neuron-ui/package.json
- packages/neuron-wallet/package.json
- packages/neuron-wallet/src/services/indexer/indexer-rpc.ts
- packages/neuron-wallet/src/services/indexer/queue.ts
- packages/neuron-wallet/src/services/node.ts
- packages/neuron-wallet/src/services/sdk-core.ts
- packages/neuron-wallet/src/services/sync/block-listener.ts
- packages/neuron-wallet/src/services/sync/get-blocks.ts
- packages/neuron-wallet/src/services/sync/queue.ts
- packages/neuron-wallet/src/services/sync/range-for-check.ts
- packages/neuron-wallet/src/startup/sync-block-task/sync.ts
- packages/neuron-wallet/src/startup/sync-block-task/task.ts
- packages/neuron-wallet/src/utils/blake2b.ts
- yarn.lock
This PR only enabled `keepAlive` in `neuron-wallet`
> feat: enable keep alive

- packages/neuron-ui/src/components/Addresses/index.tsx
- packages/neuron-ui/src/components/History/index.tsx
- packages/neuron-ui/src/components/TransactionList/index.tsx
- packages/neuron-ui/src/containers/Main/hooks.ts
- packages/neuron-ui/src/containers/Main/index.tsx
- packages/neuron-ui/src/states/initStates/app.ts
- packages/neuron-ui/src/states/stateProvider/actionCreators/app.ts
- packages/neuron-ui/src/states/stateProvider/actionCreators/transactions.ts
- packages/neuron-ui/src/states/stateProvider/actionCreators/wallets.ts
- packages/neuron-ui/src/states/stateProvider/reducer.ts
- packages/neuron-ui/src/stories/TransactionList.stories.tsx
- packages/neuron-ui/src/styles/index.scss
- packages/neuron-ui/src/theme.tsx
- packages/neuron-ui/src/types/App/index.d.ts
- packages/neuron-ui/src/utils/hooks.ts
Add an edit button aside the description field
> feat: add an edit button by the side of description

- packages/neuron-ui/src/components/Receive/index.tsx
- packages/neuron-ui/src/widgets/QRCode/index.tsx
- packages/neuron-ui/src/widgets/QRScanner/index.tsx
According to [some tutorials](https://www.qrcode-monkey.com/6-reasons-why-your-qr-code-is-not-working)
>6. Leave a border space around your QR Code
Always leave a space between your QR code and the content or design around it. The QR Code should always stand alone on the background and the foreground should not touch other elements. It is important for QR code scanner apps to detect the corner elements as stand-alone objects.
I've added a blank border around the QR Code like this:
While an indent between the Image and buttons is introduced on the Receive View
I prefer to keep it since the blank margin is a part of the QR Code and not aberrant.
> Improve qr scanner

- packages/neuron-ui/src/components/PasswordRequest/index.tsx
- packages/neuron-ui/src/states/initStates/app.ts
- packages/neuron-ui/src/states/stateProvider/actionCreators/wallets.ts
- packages/neuron-ui/src/states/stateProvider/reducer.ts
- packages/neuron-ui/src/types/App/index.d.ts
Add a timeout to avoid the block in ui process due to the transaction generation
Put the real request in next event loop to avert the block: https://github.com/nervosnetwork/neuron/pull/928/files#diff-32a64efad2cec627ed8428447ce1a310R151
> fix(neuron-ui): disable the submit button once a sending request is sent

- packages/neuron-ui/src/components/Addresses/index.tsx
- packages/neuron-ui/src/components/TransactionList/index.tsx
- packages/neuron-ui/src/styles/index.scss
rename .text-overflow to .textOverflow
> fix(neuron-ui): fix typo in class name

- packages/neuron-ui/src/components/Transaction/index.tsx
1. hide the deprecated block hash
2. fix the display of cell out point
> fix(neuron-ui): fix the transaction detail view

- packages/neuron-ui/src/components/Addresses/index.tsx
- packages/neuron-ui/src/components/TransactionList/index.tsx
- packages/neuron-ui/src/styles/index.scss
TODO: There's different behavior in the abbreviation of transaction hash and address @ashchan 
1. transaction hash only displays the first 8 and last 6 characters.
2. address displays a flexible length of leading characters.
------------------------------------------------
The current format is fine.
> Refine list

- packages/neuron-ui/src/components/Addresses/index.tsx
- packages/neuron-ui/src/components/Transaction/index.tsx
Some fixes missing in https://github.com/nervosnetwork/neuron/commit/3417445e0909d8a5f8a2761bee736abbb04febae
> fix: rename class name from text-overflow to textOverflow

- packages/neuron-ui/src/components/Addresses/index.tsx
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/types/App/index.d.ts
And disable context menu when the mainnet addresses are displayed.
> feat(neuron-ui): add mainnet/testnet addresses toggle

- packages/neuron-ui/package.json
- yarn.lock
This would remove dependency of eslint-plugin below 2.2.2 and
omit the TypeScript version warning at launch.
Also see #934.
> chore(deps): Bump cra to v3.1.2

- packages/neuron-ui/src/components/Transaction/index.tsx
- packages/neuron-ui/src/types/App/index.d.ts
- packages/neuron-wallet/src/controllers/transactions.ts
This is a workaround for the performance problem of Transaction View.
It needs more work on handling the remote object.
> refactor: sort transaction outputs in neuron wallet for performance

- packages/neuron-ui/src/components/TransactionList/index.tsx
> feat(neuron-ui): extend the width of tx type field to 70 px

- packages/neuron-ui/src/components/Addresses/index.tsx
- packages/neuron-ui/src/components/GeneralSetting/index.tsx
- packages/neuron-ui/src/containers/Navbar/index.tsx
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/services/remote/index.ts
- packages/neuron-ui/src/services/remote/skipDataAndType.ts
- packages/neuron-ui/src/states/initStates/settings.ts
- packages/neuron-ui/src/states/stateProvider/actionCreators/app.ts
- packages/neuron-ui/src/states/stateProvider/actionCreators/index.ts
- packages/neuron-ui/src/states/stateProvider/actionCreators/skipDataAndType.ts
- packages/neuron-ui/src/states/stateProvider/reducer.ts
- packages/neuron-ui/src/types/App/index.d.ts
- packages/neuron-ui/src/types/Controller/index.d.ts
- packages/neuron-wallet/src/controllers/app/index.ts
- packages/neuron-wallet/src/controllers/index.ts
- packages/neuron-wallet/tests-e2e/main.test.ts
- packages/neuron-wallet/tests-e2e/tests/generalSettings.ts
- packages/neuron-wallet/tests-e2e/tests/index.ts
add a toggle for skip-data-and-type on the general settings view
The label requires refurbishment @ashchan
> Add skip data toggle

- packages/neuron-ui/src/components/TransactionList/index.tsx
> fix(neuron-ui): show 0 confirmations if the real data is negative

- packages/neuron-ui/src/states/initStates/wallet.ts
- packages/neuron-ui/src/states/stateProvider/actionCreators/wallets.ts
Before this PR
the `initState.wallet` is possible to have values, which is incorrect when the result is null or undefined.
> fix(neuron-ui): set current wallet to empty when all wallets are deleted

- packages/neuron-wallet/src/controllers/transactions.ts
- packages/neuron-wallet/src/database/address/dao.ts
- packages/neuron-wallet/src/models/lock-utils.ts
- packages/neuron-wallet/src/services/tx/transaction-service.ts
- packages/neuron-wallet/src/services/wallets.ts
- packages/neuron-wallet/src/startup/sync-block-task/indexer.ts
- packages/neuron-wallet/src/startup/sync-block-task/sync.ts
- packages/neuron-wallet/tests/models/lock-utils.test.ts
Eliminate nested async calls and maps. Other than loading the system script,
lock utils should be able to handle batch of addresses <=> lock hashes
in synchronous manner.
> feature: Allow creating LockUtils instance

- packages/neuron-wallet/.eslintrc.js
- packages/neuron-wallet/src/database/chain/entities/input.ts
- packages/neuron-wallet/src/database/chain/entities/output.ts
- packages/neuron-wallet/src/database/chain/entities/transaction.ts
- packages/neuron-wallet/src/services/cells.ts
- packages/neuron-wallet/src/services/indexer/indexer-rpc.ts
- packages/neuron-wallet/src/services/indexer/queue.ts
- packages/neuron-wallet/src/services/sync/get-blocks.ts
- packages/neuron-wallet/src/services/tx/transaction-persistor.ts
- packages/neuron-wallet/src/services/tx/transaction-service.ts
Allow unused function arg to be ignored if they start with `_`, just as `TypeScript` handles that.
> Eslint no unused vars

- packages/neuron-ui/src/services/remote/apiMethodWrapper.ts
- packages/neuron-wallet/src/controllers/api.ts
- packages/neuron-wallet/src/decorators/index.ts
- packages/neuron-wallet/src/decorators/mappers.ts
On handling 10000 outputs:
> Stringified: 0.03271484375ms
> Unstringified: 3.60595703125ms
> Stringify api result

- packages/neuron-wallet/src/services/sync/check-and-save/output.ts
- packages/neuron-wallet/src/services/sync/check-and-save/tx.ts
- packages/neuron-wallet/src/services/sync/get-blocks.ts
- packages/neuron-wallet/src/services/sync/queue.ts
Local optimization for batch txs from and to the same address.
For each block, simply add a hash map to cache the output tx used by input.
This speeds up tx insert for our batch txs test (e.g. https://explorer.nervos.org/transaction/0x774a3e608afe267617d28db098dd9e36c93df9de75aedf10d8e5fcb55e38e774) from 2-5 txs/sec to 50~ txs/sec.
Note for a real world block that contains many unrelated transactions this optimization won't help. We still need to figure out how to tweak that. But for end user usage I don't think a wallet would have so many transactions.
> Optimize non indexer sync

- packages/neuron-ui/src/components/Overview/index.tsx
> fix(neuron-ui): hide the confirmations of pending txs

- scripts/release-checksums.rb
and get SHA256 checksums
Ideally we could have this integrated to the CI publish task (that we don't need to download and digest), but not urgent to implement that for the time being.
> Ruby script to download a release binaries and calculate SHA256 checksums

- packages/neuron-wallet/package.json
- yarn.lock
22.2 doesn't seem to be able to build the windows binary on macOS.
> [ᚬmaster] chore: Roll back electron-builder to 22.1.0

- packages/neuron-wallet/electron-builder.yml
Remove unnecessary part, e.g.:
* `linux` for AppImage
* `mac` for dmg
* `win` for exe
> feat: Shorter binary file names

- packages/neuron-ui/src/components/CustomRows/DAORecordRow.tsx
- packages/neuron-ui/src/components/CustomRows/daoRecordRow.module.scss
- packages/neuron-ui/src/components/NervosDAO/WithdrawDialog.tsx
- packages/neuron-ui/src/components/NervosDAO/index.tsx
- packages/neuron-ui/src/components/Send/index.tsx
- packages/neuron-ui/src/components/Transaction/index.tsx
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/states/stateProvider/actionCreators/wallets.ts
> Update nervos dao ui

- scripts/release-checksums.rb
> chore: Update release checksums script to reflect recent

- packages/neuron-ui/src/components/NervosDAO/index.tsx
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/utils/formatters.ts
- packages/neuron-ui/src/utils/validators.ts
> fix(neuron-ui): add decimal validation on deposit value

- packages/neuron-ui/src/components/NervosDAO/index.tsx
- packages/neuron-ui/src/widgets/PropertyList/index.tsx
> feat(neuron-ui): use the same style of overview on nervos dao overview

- packages/neuron-ui/src/components/Overview/index.tsx
- packages/neuron-ui/src/containers/Main/hooks.ts
- packages/neuron-ui/src/states/initStates/app.ts
- packages/neuron-ui/src/states/stateProvider/reducer.ts
- packages/neuron-ui/src/stories/Overview.stories.tsx
- packages/neuron-ui/src/tests/formatters/difficultyFormatter/fixtures.json
- packages/neuron-ui/src/tests/formatters/difficultyFormatter/index.test.ts
- packages/neuron-ui/src/types/App/index.d.ts
- packages/neuron-ui/src/utils/formatters.ts
> feat(neuron-ui): add difficulty formatter

- packages/neuron-ui/package.json
- packages/neuron-ui/src/services/remote/app.ts
- packages/neuron-wallet/package.json
- packages/neuron-wallet/src/controllers/api.ts
- packages/neuron-wallet/src/controllers/transactions.ts
- packages/neuron-wallet/src/env.ts
- packages/neuron-wallet/src/services/networks.ts
- packages/neuron-wallet/src/startup/sync-block-task/create.ts
- packages/neuron-wallet/src/startup/sync-block-task/init-database.ts
- packages/neuron-wallet/src/types/network.ts
- packages/neuron-wallet/tests-e2e/tests/network.ts
- packages/neuron-wallet/tests-e2e/tests/sendTransaction.ts
- packages/neuron-wallet/tests/services/networks.test.ts
* Always return data when requesting `initData`
* `Network` now contains genesis hash
* Default mainnet network will have hardcoded genesis hash
* Sync database initialization uses `Network` instead of network URL
> Mainnet network

- packages/neuron-ui/src/containers/Footer/index.tsx
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/services/localCache.ts
> Add disconnection info in footer

- packages/neuron-wallet/src/startup/sync-block-task/init-database.ts
> feat: Always load genesis hash and chain info when

- packages/neuron-wallet/src/services/sync/queue.ts
starts from block #1
This bug is very interesting.
The block `queue` scans a window of blocks in batch. It remembers the last scanned block `N`, and starts from `N + 1` for next round.
`N` was initialized as `-1` then the first round would start from genesis block.
But initially it also reads another DB saved number representing last block number. When Neuron launches without any wallets, that number will be zero and persisted.
Then when a wallet gets imported the queue scans from `1`, not genesis block!
Yet to see if this guard fixes completely. It seems too difficult to change the scan range and remove the `N + 1` operation, though.
> fix: Genesis block should be scanned when next scan range

- packages/neuron-wallet/src/services/sync/block-listener.ts
Sometimes when switch network , the subject will send a 0 number, and sync will stopped until tip number updated.
> fix: only resetEndBlockNumber if number > 0

- packages/neuron-wallet/src/listeners/address.ts
The bufferTime will cause the problem that addresses created after tx fetched, so can't check tx correctly, and tx will not save to local db
> fix: remove bufferTime for address created event

- packages/neuron-wallet/src/main.ts
- packages/neuron-wallet/src/services/networks.ts
- packages/neuron-wallet/src/services/node.ts
This fixes the maximum call stack size exceeded issue on launch.
When the app starts many parts call NetworkService.get/getAll, at which time
NetworkService get initialized and send notifications, which in turn makes
these subscribers call get/getAll again.
On Windows this has made the app unable to launch.
> Move network notifications sending out of NetworkService constructor

- packages/neuron-ui/src/components/Send/hooks.ts
- packages/neuron-ui/src/components/Send/index.tsx
Update the sending-all transaction when the price is changed.
> [ᚬrc/v0.26.0] fix: Sending all transaction should be updated on price changes

- packages/neuron-ui/src/components/Send/hooks.ts
`1,789` will be used on pasting `1,789.35`
> fix: Only integer should be accepted on inputting price.

- packages/neuron-ui/src/components/History/history.module.scss
- packages/neuron-ui/src/components/History/index.tsx
> feat: Fill the transaction list in the history view

- packages/neuron-wallet/src/startup/sync-block-task/init-database.ts
> Delete InitDatabase.previous property

- packages/neuron-ui/src/components/Overview/index.tsx
- packages/neuron-ui/src/components/Overview/overview.module.scss
Blockchain status will be hidden by clicking the button again or blur the info panel.
> feat: Hide blockchain status on clicking the button

- packages/neuron-ui/src/containers/Main/hooks.ts
- packages/neuron-ui/src/services/localCache.ts
- packages/neuron-ui/src/services/subjects.ts
- packages/neuron-ui/src/states/initStates/chain.ts
- packages/neuron-ui/src/states/stateProvider/actionCreators/app.ts
- packages/neuron-ui/src/states/stateProvider/reducer.ts
- packages/neuron-ui/src/types/App/index.d.ts
- packages/neuron-ui/src/types/Subject/index.d.ts
- packages/neuron-wallet/src/controllers/api.ts
- packages/neuron-wallet/src/controllers/app/subscribe.ts
- packages/neuron-wallet/src/models/lock-utils.ts
- packages/neuron-wallet/src/models/subjects/system-script.ts
Note: `codeHash` was used to show miner info. Even since mainnet launch that feature has been removed.
> Delete system script subject

- packages/neuron-ui/src/components/Overview/index.tsx
Display the syncing label when the synced block number is less than tip block number - 10, or the tip block timestamp is less than system time - 3mins.
> feat: Update the condition of syncing label

- packages/neuron-ui/src/components/CompensationPeriodDialog/index.tsx
- packages/neuron-ui/src/components/DepositDialog/index.tsx
- packages/neuron-ui/src/components/NervosDAO/index.tsx
- packages/neuron-ui/src/components/PasswordRequest/index.tsx
- packages/neuron-ui/src/components/WithdrawDialog/index.tsx
- packages/neuron-ui/src/utils/hooks.ts
- packages/neuron-ui/src/widgets/AlertDialog/index.tsx
Add an event listener to invoke the onDismiss method when the dialog is closed.
> fix: Fix the dismission of dialog by escape

- packages/neuron-ui/src/components/Addresses/addresses.module.scss
- packages/neuron-ui/src/components/Addresses/index.tsx
- packages/neuron-ui/src/components/TransactionList/index.tsx
- packages/neuron-ui/src/components/TransactionList/transactionList.module.scss
- packages/neuron-ui/src/locales/en.json
1. use a custom ellipsis
2. simplify the type of address label
Before
After
Before
After
> [ᚬrc/v0.26.1] feat: Refine History and Address List

- packages/neuron-wallet/package.json
- yarn.lock
The issue was due to a redirect bug from Electron 7.1.3 and above.
We'd have to stick with `7.1.2` until there's a new release with the fix (which is already in electron master).
> Downgrade to Electron 7.1.2 to fix the update failure issue

- packages/neuron-wallet/src/controllers/app/index.ts
- packages/neuron-wallet/src/main.ts
It's always running a single instance on macOS (unless launched from command line). This makes sure Neuron only runs one instance on Linux/Windows.
> Prevent multiple instances

- packages/neuron-ui/src/components/NetworkSetting/index.tsx
- packages/neuron-wallet/src/services/networks.ts
The default network `Mainnet` was not editable, but if some one brings up another chain other than the mainnet, it should connect to that (genesis hash and chain would update automatically, while the name will be kept as `Mainnet`.
This change also allows to edit(rename) the default network, but keeps it from being deleted.
> Allow to connect to any chain from the default Mainnet network

- packages/neuron-ui/src/components/Send/hooks.ts
- packages/neuron-ui/src/components/Send/index.tsx
- packages/neuron-ui/src/states/initStates/app.ts
- packages/neuron-ui/src/types/App/index.d.ts
- packages/neuron-ui/src/utils/formatters.ts
- packages/neuron-ui/src/utils/validators.ts
Remove the `set errors` out of the `onItemChange` hook and update it before each render.
> refactor: declarative update messages on the sending view.

- packages/neuron-wallet/package.json
- yarn.lock
This version fixes the net redirect bug causing app update failure.
> Update electron to 7.1.9

- packages/neuron-ui/src/utils/i18n.ts
- packages/neuron-wallet/electron-builder.yml
- packages/neuron-wallet/src/locales/i18n.ts
* Add `zh-TW`
* Fallback `zh-CN` to `zh`
* Make `zh-TW` available to macOS language list
Current implementation doesn't support switching language on the fly yet. For one thing, Electron doesn't have `app.setLocale`, for another, if we store user selected language in the app and skip `app.getLocale`, per-app language preferences on macOS might not work any more (haven't test this though).
This WON'T go into [`v0.27.0`](https://github.com/nervosnetwork/neuron/pull/1336).
> Language loading

- packages/neuron-wallet/src/block-sync-renderer/sync/queue.ts
`Queue.currentBlockNumber` is the block number to process, thus when notifying synced block number the value should be `currentBlockNumber - 1`.
> Fix synced block number offset one bug

- packages/neuron-ui/src/containers/Notification/index.tsx
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/utils/const.ts
Now that we have CKB node bundled, this message has become unnecessary.
> Remove how to run ckb node message

- packages/neuron-wallet/src/services/ckb-runner.ts
This probably will fix the issue that after around 10 minutes of spawning
the bundled CKB would stop writing log to run.log file
> Ignore CKB child process's stdin and stdout fd

- packages/neuron-ui/src/utils/getSyncStatus.ts
Skip sampling if `tipBlockNumber` is empty.
> fix: Ignore invalid data on caching network status

- packages/neuron-wallet/src/controllers/wallets.ts
Without this branch, an error will be thrown to UI.
> fix: return success if user cancels backup a wallet

- packages/neuron-ui/src/components/SpecialAsset/index.tsx
Use `transaction#index` instead of
> [ᚬrc/v0.28.1] fix: Fix the link to customized cell

- packages/neuron-ui/src/components/WithdrawDialog/withdrawDialog.module.scss
> [ᚬrc/v0.29.0] fix: Remove the height limitation of messages

- packages/neuron-wallet/package.json
- yarn.lock
We'll hold electron 8 upgrade; instead, update to 7.1.14 and test it completely.
> Upgrade electron to 7.1.14

- packages/neuron-ui/src/components/SpecialAssetList/index.tsx
This PR is for the situation that `epochIndex/epochLength > 1`.
The comparison between epochs starts from epoch number. If the current epoch and target epoch have the same epoch number, the value of `index/length` will be compared.
Say **epoch=579 index=65464 length=239**,
The cell is unavailable on the epoch 579 cuz 65464/234 > 1 while it's available on epoch 580 cuz 580 > 579
> [ᚬrc/v0.29.0] feat: limit index/length up to 1 on parsing epoch

- packages/neuron-ui/src/components/NetworkEditor/index.tsx
Disable the submit button if both of network name and its url are not modified.
Before this PR, the validation only checks the network name.
If only the network url is changed, the validation fails, which is not expected.
> [ᚬrc/v0.29.0] fix: Fix the validation on network update

- packages/neuron-ui/src/states/stateProvider/actionCreators/transactions.ts
- packages/neuron-ui/src/types/Controller/index.d.ts
- packages/neuron-ui/src/utils/hooks.ts
- packages/neuron-wallet/src/controllers/api.ts
- packages/neuron-wallet/src/controllers/transactions.ts
- packages/neuron-wallet/src/database/leveldb/index.ts
- packages/neuron-wallet/src/database/leveldb/transaction-description.ts
The current implementation cleans sqlite transaction table when clearing cache,
but description as user data should be kept.
> Persist transaction description in leveldb, separate from tx sqlite data

- packages/neuron-ui/src/components/NetworkStatus/index.tsx
- packages/neuron-ui/src/stories/NetworkStatus.stories.tsx
1. synced block number > tip block number and tip block number is not empty => synced block number should up to tip block number
2. sycned block number > tip block number and tip block number is empty => keep synced block number its own value
3. synced block number is -1 and tip block number is empty => do not show the tooltip
> feat: add the following cases of network status

- packages/neuron-ui/src/components/NervosDAO/index.tsx
- packages/neuron-ui/src/components/Overview/index.tsx
- packages/neuron-ui/src/components/Send/index.tsx
- packages/neuron-ui/src/containers/Navbar/index.tsx
- packages/neuron-ui/src/utils/getCurrentUrl.ts
- packages/neuron-ui/src/utils/getSyncStatus.ts
Update the cached timestamp and block number if the url is changed to avoid the comparison on data from different chains.
> fix: Fix the network pending status after network changes

- packages/neuron-wallet/package.json
- packages/neuron-wallet/src/controllers/app/menu.ts
- packages/neuron-wallet/src/controllers/export-debug.ts
- packages/neuron-wallet/src/locales/en.ts
- packages/neuron-wallet/src/locales/zh-tw.ts
- packages/neuron-wallet/src/locales/zh.ts
- yarn.lock
This PR adds a menu item in `help` to export information for debugging.
The information includes `status.json`, `main.log`, `renderer.log` and the `status.json` has the following content.
```json
{
"neuron": { "version": "0.29.0-rc2", "blockNumber": "4024" },
"ckb": { "url": "http://localhost:8114", "version": "", "blockNumber": "" }
}
```
> feat: enable exporting debug info from helper menu

- packages/neuron-wallet/src/controllers/wallets.ts
- packages/neuron-wallet/src/database/leveldb/index.ts
- packages/neuron-wallet/src/database/leveldb/transaction-description.ts
- packages/neuron-wallet/src/services/transaction-sender.ts
- packages/neuron-wallet/src/services/tx/transaction-persistor.ts
- packages/neuron-wallet/tests/services/tx/transaction-persistor.test.ts
Different wallets having the same transaction should not share the description.
> Only save tx description for the wallet to which it belongs

- packages/neuron-wallet/src/controllers/export-debug.ts
URL not starts with `http://localhost` or `https://localhost` will be replaced with `http://****:port` in the status.json
> feat: conceal real node address if it's not localhost for privacy

- packages/neuron-ui/src/components/NetworkStatus/networkStatus.module.scss
1. set the font size 12px
2. set the color #000
> feat: update the style of block number tooltip

- packages/neuron-ui/src/components/NetworkStatus/networkStatus.module.scss
> feat: align the block number tooltip closer to the side

- packages/neuron-wallet/src/controllers/app/index.ts
- packages/neuron-wallet/src/services/ckb-runner.ts
* If external CKB is running (by guessing from RPC call), do NOT spawn the bundled CKB.
* If `ckb.toml` under the bundled CKB's data folder exists, do NOT run `ckb init`.
> Improve bundled CKB startup process

- packages/neuron-ui/src/components/NervosDAO/index.tsx
- packages/neuron-ui/src/components/NervosDAORecord/index.tsx
- packages/neuron-ui/src/components/Overview/index.tsx
- packages/neuron-ui/src/components/Send/index.tsx
- packages/neuron-ui/src/components/SyncStatus/index.tsx
- packages/neuron-ui/src/containers/Main/hooks.ts
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/states/initStates/chain.ts
- packages/neuron-ui/src/states/stateProvider/reducer.ts
- packages/neuron-ui/src/types/App/index.d.ts
- packages/neuron-ui/src/utils/const.ts
ConnectionStatus.Connecting will be displayed in the first 10s since app launchs while the sync in is under error.
This status is for better UX during launching the CKB node.
> feat: add 10s buffer to display connection error for launching ckb node

- packages/neuron-ui/src/components/SyncStatus/index.tsx
- packages/neuron-ui/src/utils/const.ts
- packages/neuron-ui/src/utils/getSyncStatus.ts
It's a technical status and was used to avoid errors in the progress bar.  In most cases it is non-sense to users and is covered by ConnectionStatus.Offline.
> feat: remove the sync status of failing to get tip block number

- packages/neuron-wallet/src/controllers/export-debug.ts
Add the `client` field in the `status.json`
```
"client":{"platform":"darwin","arch":"x64","release":"19.3.0"}
```
> feat: add platform-related info in debug info

- packages/neuron-ui/src/components/NervosDAORecord/daoRecordRow.module.scss
It seems to be a bug of chromium in Electron that the -webkit-appearance doesn't work properly
> [ᚬrefactor-nervos-dao] fix: fix the default appearance of button

- packages/neuron-ui/src/components/CompensationPeriodTooltip/compensationPeriodTooltip.module.scss
- packages/neuron-ui/src/components/CompensationPeriodTooltip/index.tsx
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/stories/CompensationPeriodTooltip.stories.tsx
When it's in 16h since deposition, the tooltip of Nervos DAO Record should be "It takes at least about 16 hours (4epochs) to proceed the next action"
> feat: update the tooltip message of immature for withdraw stage

- packages/neuron-ui/src/components/Transaction/index.tsx
- packages/neuron-ui/src/components/Transaction/transaction.module.scss
- packages/neuron-ui/src/components/TransactionList/index.tsx
- packages/neuron-ui/src/components/TransactionList/transactionList.module.scss
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/stories/styles.scss
- packages/neuron-ui/src/widgets/Icons/Detail.svg
1. add the view-detail and view-in-explorer buttons in the transaction list and remove them from the transaction detail
2. make the description field 100% wide
> [ᚬsUDT] feat: adjust the layout of transaction history

- packages/neuron-ui/src/components/NetworkEditor/hooks.ts
- packages/neuron-ui/src/components/NetworkEditor/index.tsx
- packages/neuron-ui/src/states/initStates/app.ts
- packages/neuron-ui/src/states/stateProvider/actionCreators/settings.ts
- packages/neuron-ui/src/types/App/index.d.ts
remove the loading status from global context and hold it in the component by itself.
> refactor: move loading state of network editor internal

- packages/neuron-wallet/src/services/cells.ts
- packages/neuron-wallet/tests/services/tx/transaction-generator.test.ts
When sending anyone-can-pay tx, if multi inputs from one asset account, only keep down one in output
> Only keep down one cell in outputs when lockHash & typeHash are the some

- packages/neuron-ui/src/stories/CopyZone.stories.tsx
- packages/neuron-ui/src/stories/index.tsx
- packages/neuron-ui/src/widgets/CopyZone/copyZone.module.scss
- packages/neuron-ui/src/widgets/CopyZone/index.tsx
The overlay with text `copy` appears on mouse hover event to indicate the text is copiable.
> Add copy component

- packages/neuron-ui/src/components/SUDTAccountList/index.tsx
- packages/neuron-ui/src/tests/sortAccounts/fixtures.json
- packages/neuron-ui/src/tests/sortAccounts/index.test.ts
- packages/neuron-ui/src/utils/sortAccounts.ts
1. sort by token name
2. sort by account name
3. empty accounts are placed at the end
> feat: sort s-udt accounts

- packages/neuron-ui/src/components/SUDTSend/sUDTSend.module.scss
Align the right side of the description field to other inputs
> feat: add a padding to the desc field

- packages/neuron-ui/src/components/SUDTAccountList/index.tsx
The empty name won't be regarded as a repeated one by removing empty from existing names.
> fix: remove empty from existing names

- packages/neuron-ui/src/components/Send/index.tsx
- packages/neuron-ui/src/widgets/DatetimePicker/index.tsx
Use custom date formatter instead of toLocaleDateString to avoid confusion from dd/mm/YYYY
> fix: use custom date formatter

- packages/neuron-ui/src/components/NetworkSetting/index.tsx
- packages/neuron-ui/src/utils/hooks.ts
It's already handled by the onChange handler of the ChoiceGroup component
ref: https://github.com/nervosnetwork/neuron/blob/rc/v0.31.0/packages/neuron-ui/src/components/NetworkSetting/index.tsx#L108
> fix: remove redundant handler on setting network id

- packages/neuron-wallet/src/services/asset-account-service.ts
- packages/neuron-wallet/src/services/cells.ts
- packages/neuron-wallet/src/services/tx/transaction-generator.ts
- packages/neuron-wallet/src/services/tx/transaction-service.ts
- packages/neuron-wallet/src/utils/buffer.ts
- packages/neuron-wallet/tests/utils/buffer.test.ts
- Added `BufferUtils#parseAmountFromSUDTData(leHex)` 
- Restructured and added unit tests for `BufferUtils` 
- Uses `BufferUtils#parseAmountFromSUDTData(leHex)` to parse amounts for sUDT data
> Handle invalid sUDT data

- packages/neuron-wallet/src/services/cells.ts
- packages/neuron-wallet/tests/services/cells.test.ts
This is a temporary fix to the issue `SQLITE_ERROR: too many SQL variables`.
We will need to refactor the similar queries of this kind in the other places so that it only queries with the variables within a wallet's scope instead of all wallets'.
> Temporary fix for the sqlite too many variables error

- packages/neuron-ui/src/components/SUDTSend/sUDTSend.module.scss
- packages/neuron-ui/src/components/Send/send.module.scss
- packages/neuron-ui/src/components/SignAndVerify/index.tsx
- packages/neuron-ui/src/components/SignAndVerify/signAndVerify.module.scss
- packages/neuron-ui/src/widgets/TextField/textField.module.scss
- packages/neuron-wallet/src/controllers/app/menu.ts
1. set the width of the sign-and-verify dialog to 900px;
2. use textfield instead of textarea for the signature field;
3. set the height of the form to 100%;
> Adjust layout of sign and verify dialog

- packages/neuron-ui/src/components/History/history.module.scss
- packages/neuron-ui/src/components/History/index.tsx
Use smaller pagination when tx count >= 10000
> feat: use smaller pagination when tx count is too large

- packages/neuron-ui/src/containers/Navbar/index.tsx
Ignore the leading slash in the pathname
> fix: fix the active nav item filter

- azure-pipelines.yml
- package.json
- packages/neuron-wallet/package.json
- packages/neuron-wallet/src/block-sync-renderer/index.ts
- packages/neuron-wallet/src/block-sync-renderer/sync/indexer-cache-service.ts
- packages/neuron-wallet/src/block-sync-renderer/sync/indexer-connector.ts
- packages/neuron-wallet/src/block-sync-renderer/sync/queue.ts
- packages/neuron-wallet/src/models/subjects/wallet-deleted-subject.ts
- packages/neuron-wallet/src/services/tx/transaction-persistor.ts
- packages/neuron-wallet/src/services/wallets.ts
- packages/neuron-wallet/tests/block-sync-render/index.test.ts
- packages/neuron-wallet/tests/block-sync-render/indexer-cache-service.intg.test.ts
- packages/neuron-wallet/tests/block-sync-render/indexer-connector.test.ts
- packages/neuron-wallet/tests/block-sync-render/queue.intg.test.ts
- packages/neuron-wallet/tests/block-sync-render/queue.test.ts
- packages/neuron-wallet/tests/services/wallets.test.ts
- yarn.lock
* Upgrade to lumos indexer 0.4.8
* Refactors according to the API changes between lumos indexer 0.3.0 and 0.4.8
* Prevent unnecessary index rebuild after imported a wallet
* Fix the incorrect balance issue caused by the silenced errors when saving transactions
* Update yarn bootstrap script to deprecate building for lumos indexer
* Reload sync block render after deleted a wallet
> Backend fixes for 0.32-beta.1

- CHANGELOG.md
- lerna.json
- package.json
- packages/neuron-ui/package.json
- packages/neuron-wallet/package.json
v0.32.0-rc1, scheduled to be released on July 21st.
> chore: Bump version to v0.32.0-rc1 and update CHANGELOG.md

- packages/neuron-wallet/package.json
- packages/neuron-wallet/src/block-sync-renderer/sync/indexer-connector.ts
- packages/neuron-wallet/src/block-sync-renderer/sync/queue.ts
- packages/neuron-wallet/tests/block-sync-render/indexer-connector.test.ts
- packages/neuron-wallet/tests/block-sync-render/queue.test.ts
- yarn.lock
* Fix log export by upgrading `archiver` to 4.0.2,  which has the same major version of `async` dependency as wallet backend has.
* Avoid redundant processing on the blocks that have been processed already.
> Backend fixes

- packages/neuron-wallet/package.json
- yarn.lock
* Upgrade Lumos indexer to support node connection via TLS
@kellyshang Based on the current branching practice we are using, should I target this PR to another branch such as `hotfix/0.32.1` and leave it for you to handle the rest, such as the version bumping and updating release notes? Please feel free to suggest.
> Hot fix to TLS support on indexer

- azure-pipelines.yml
- package.json
Windows CI seems to purge files that have been created after each step, resulting in compiled files that cannot be found in the test.
This PR resolves the testing issue with #1800.
failed case:
https://dev.azure.com/nervosnetwork/neuron/_build/results?buildId=13509&view=logs&j=1dd1a9fa-5bd6-5a58-be75-4682264ffaf4&t=0fd07730-01dd-5646-2168-32456ff1e2aa&l=861
success case(in my own repo):
https://dev.azure.com/nervjs/Nervjs/_build/results?buildId=65&view=logs&j=1dd1a9fa-5bd6-5a58-be75-4682264ffaf4&t=0fd07730-01dd-5646-2168-32456ff1e2aa&l=232
> Build and test in same step in Windows CI

- packages/neuron-ui/src/components/ImportKeystore/index.tsx
- packages/neuron-ui/src/electron-modules.tsx
- packages/neuron-ui/src/services/remote/app.ts
- packages/neuron-ui/src/services/remote/index.ts
- packages/neuron-ui/src/services/remote/remoteApiWrapper.ts
- packages/neuron-ui/src/types/global/index.d.ts
- packages/neuron-ui/src/utils/hooks.ts
- packages/neuron-wallet/src/block-sync-renderer/index.ts
- packages/neuron-wallet/src/block-sync-renderer/tx-status-listener.ts
- packages/neuron-wallet/src/controllers/api.ts
- packages/neuron-wallet/src/controllers/app/index.ts
- packages/neuron-wallet/src/controllers/app/preload.ts
- packages/neuron-wallet/src/controllers/app/show-window.ts
- packages/neuron-wallet/src/models/subjects/address-created-subject.ts
- packages/neuron-wallet/src/models/subjects/address-db-changed-subject.ts
- packages/neuron-wallet/src/models/subjects/node.ts
- packages/neuron-wallet/src/models/subjects/tx-db-changed-subject.ts
- packages/neuron-wallet/src/models/subjects/wallet-deleted-subject.ts
- packages/neuron-wallet/src/services/file.ts
- packages/neuron-wallet/src/services/node.ts
Note that this PR using a undocumented and untyped method called `getOwnerBrowserWindow()`, more details and explanations can be found in the comments.
The usages of `remote` in the main process has also been removed, see the discussion in https://github.com/nervosnetwork/neuron/pull/1800#discussion_r472820886 for details.
This PR has rebase the latest changes to #1800 and #1802  for QA team.
> Deprecate the 'remote' module

- packages/neuron-wallet/src/controllers/app/index.ts
For some how, in Electron 9 packaged mode, BrowserWindow's `icon` can only accept a instance of `NativeImage`.
ref:
https://github.com/electron/electron/issues/24221
> Fix icon package issue in Electron 9

- packages/neuron-wallet/src/block-sync-renderer/index.ts
- packages/neuron-wallet/tests/block-sync-render/index.test.ts
- packages/neuron-wallet/tests/setup.ts
Currently, it throws unhandled rejection error in the console for this test suit even the tests are passed. This error is caused by the improper setup of the network service dependency during the tests and resolved by mocking up that dependency.
> Fix unhandled rejection error in test

- packages/neuron-wallet/src/services/addresses.ts
- packages/neuron-wallet/src/services/cells.ts
- packages/neuron-wallet/src/services/tx/transaction-service.ts
- packages/neuron-wallet/tests/services/cells.test.ts
* Fix incorrect inputs gathering, which could resulting in `InvalidCodeHash` error if a gathered input cell comes with an unexpected hash type in the lock script.
* Count transactions based on public key hash
> Fix `InvalidCodeHash` error when sending tx

- packages/neuron-wallet/src/block-sync-renderer/index.ts
- packages/neuron-wallet/src/block-sync-renderer/task-wrapper.ts
- packages/neuron-wallet/tests/block-sync-render/task.test.ts
In child process, the `electron` dependency won't be available in production environment. Thus it throws error when starting the child process which eventually loads the `env.ts`, and the child process can't be started. 
For now, this PR provides a quick workaround to mock up the `electron` dependency in the child process. Later on, we need to refactor the `env.ts` to handle the unavailability of `electron` into order stub the necessary variables such as the `fileBasePath` so that all these key variables are against accessible from the `env.ts`
> Mock electron dependency in child process

- packages/neuron-wallet/src/block-sync-renderer/sync/indexer-connector.ts
- packages/neuron-wallet/tests/block-sync-render/indexer-connector.test.ts
On windows, concurrent requests to the lumos cell query API could lead to a wrong result even the queries are the same. 
This PR is meant to prevent concurrent requests to lumos by queueing them and process one by one.
> Queue requests to lumos query on cells

- packages/neuron-wallet/src/controllers/anyone-can-pay.ts
- packages/neuron-wallet/src/controllers/transactions.ts
- packages/neuron-wallet/src/controllers/wallets.ts
- packages/neuron-wallet/src/database/chain/entities/tx-description.ts
- packages/neuron-wallet/src/database/chain/migrations/1599441769473-TxDescription.ts
- packages/neuron-wallet/src/database/chain/ormconfig.ts
- packages/neuron-wallet/src/database/leveldb/index.ts
- packages/neuron-wallet/src/services/tx/transaction-description.ts
- packages/neuron-wallet/src/utils/export-history.ts
- packages/neuron-wallet/tests/services/tx/transaction.description.intg.test.ts
- Refactor to use a sqlite table for storing the tx descriptions
- Migrate data from leveldb to the sqlite table
- leveldb dependency will be deprecated in the next minor version (0.34)
> Deprecating leveldb

- packages/neuron-wallet/src/block-sync-renderer/index.ts
- packages/neuron-wallet/src/block-sync-renderer/sync/indexer-cache-service.ts
- packages/neuron-wallet/src/block-sync-renderer/sync/indexer-connector.ts
- packages/neuron-wallet/src/controllers/sync.ts
- packages/neuron-wallet/src/utils/worker.ts
- packages/neuron-wallet/tests/block-sync-render/index.test.ts
- packages/neuron-wallet/tests/block-sync-render/indexer-connector.test.ts
- packages/neuron-wallet/tests/utils/worker.test.ts
- Process the requests in Worker child process in a queue so as to ensure the responses are channeled correctly back to the front end.
- Ensure the ongoing requests in the child process are drained and responded to the client when terminated the child process. 
- Refactor the `block-sync-renderer` to reset the child process in order in case there are concurrent calls to the reset function.
- Better logs from the child process.
> Refactor the messages handling between main and child process

- packages/neuron-wallet/src/services/asset-account-service.ts
- packages/neuron-wallet/src/services/cells.ts
- packages/neuron-wallet/tests/services/asset-account-service.test.ts
- packages/neuron-wallet/tests/services/tx/transaction-generator.test.ts
- Refactor the balance calculations for asset accounts
- Ignore CKB ACP cells with data for transfers
There will be refactors needed in the API for fetching customized assets. Displaying these ignored ACP cells in the customized asset view will be included in the refactor PR.
> Fix CKB ACP transfers

- packages/neuron-ui/src/components/SUDTSend/index.tsx
Remote error was dismissed when form was not ready, however the amount was left empty when generate-send-all-to-anyone-can-pay-tx threw an error, which led to an unexcepted situration that remote error was discarded since the transaction is invalid.
This commit removes the `isFormReady` condition of displaying remote error and the remote error will be left when amount is empty, and it will be reset on inputting.
> fix: display remote error when form is not ready

- packages/neuron-ui/src/components/SUDTSend/index.tsx
- packages/neuron-wallet/src/models/subjects/node.ts
- packages/neuron-wallet/src/services/node.ts
- packages/neuron-wallet/tests/services/node.test.ts
Added the two additional flags for the bundled node:
- isBundledNode
- startedBundledNode
These flags would help the front end refine the display of connection statuses, particularly for the bundled node.
> Additional flags for bundled node

- packages/neuron-wallet/src/block-sync-renderer/sync/indexer-cache-service.ts
- packages/neuron-wallet/src/database/address/meta.ts
- packages/neuron-wallet/tests/block-sync-render/indexer-cache-service.intg.test.ts
- packages/neuron-wallet/tests/block-sync-render/queue.intg.test.ts
- packages/neuron-wallet/tests/database/address/meta.test.ts
- Fix incorrect `args` for the multi-sign lock 
- Use `argsLen` lumos query filter to locate the cells by multi-sign lock and cache their corresponding transaction hashes for indexing.
> Fix lumos query for multisign lock

- packages/neuron-wallet/src/block-sync-renderer/sync/indexer-connector.ts
Concurrent SQLite queries are slower than the ones running in sequence. This PR make the concurrent queries run in order.
> Optimize query performance for tx hash upsert

- packages/neuron-wallet/src/services/anyone-can-pay.ts
- packages/neuron-wallet/src/services/tx/transaction-generator.ts
- packages/neuron-wallet/tests/services/tx/transaction-generator.test.ts
- Internally supports transfers from ckb asset account to sudt asset account
- For now, reject requests to transfer from ckb asset account to sudt asset account
> Disable transfers from ckb asset account to sudt asset account

- packages/neuron-ui/src/components/SUDTReceive/index.tsx
- packages/neuron-ui/src/components/SUDTReceive/sUDTReceive.module.scss
Address: `ckt1q9gry5zg8stq8ruq5wfz3lm5wn2k7qw3ulsfmdhe98f2j1`
Address: `ckt1q9gry5zg8stq8ruq5wfz3lm5wn2k7qw3ulsfmdhe98f2j11`
> feat: insert ellipsis if asset account address is too long

- packages/neuron-ui/src/containers/Main/hooks.ts
- packages/neuron-ui/src/services/subjects.ts
- packages/neuron-ui/src/types/Subject/index.d.ts
- packages/neuron-wallet/src/block-sync-renderer/index.ts
- packages/neuron-wallet/src/block-sync-renderer/sync/indexer-connector.ts
- packages/neuron-wallet/src/block-sync-renderer/sync/queue.ts
- packages/neuron-wallet/src/controllers/app/subscribe.ts
- packages/neuron-wallet/src/controllers/sync-api.ts
- packages/neuron-wallet/src/models/subjects/node.ts
- packages/neuron-wallet/src/models/subjects/sync-state-subject.ts
- packages/neuron-wallet/src/models/synced-block-number.ts
- packages/neuron-wallet/tests/block-sync-render/index.test.ts
- packages/neuron-wallet/tests/block-sync-render/indexer-connector.test.ts
- packages/neuron-wallet/tests/block-sync-render/queue.intg.test.ts
- packages/neuron-wallet/tests/block-sync-render/queue.test.ts
- packages/neuron-wallet/tests/controllers/sync-api.test.ts
- packages/neuron-wallet/tests/models/synced-block-number.intg.test.ts
- Deprecated the `synced-block-number-updated` by `sync-estimate-updated`. 
- Updated the front end code to account for this change, so the sync status still works in this PR.
- `sync-estimate-updated` event has the following schema.
- For now, it uses a custom call to fetch sync state from node instead of using the built-in API of SDK +0.35. We will need to go through a refactor to get the code base adapted to typescript 4, which is required by SDK version greater than 0.35
```javascript
{
nodeUrl: 'http://localhost:8224', // current node url
timestamp: 1601044101705, // the time when delivered this estimation event
indexerTipNumber: 369397, // current block tip on indexer
cacheTipNumber: 367434, // current cached block tip 
bestKnownBlockNumber: 493640, // best known block number from …
```
> Estimation on synchronization

- packages/neuron-wallet/src/database/chain/entities/hd-public-key-info.ts
- packages/neuron-wallet/src/database/chain/migrations/1601447406035-RemoveKeyInfoAddress.ts
- packages/neuron-wallet/src/database/chain/ormconfig.ts
- packages/neuron-wallet/src/models/keys/hd-public-key-info.ts
- packages/neuron-wallet/tests/models/keys/hd-public-key-info.test.ts
- packages/neuron-wallet/tests/services/asset-account-service.test.ts
- packages/neuron-wallet/tests/services/cells.test.ts
Since the address can be derived from the `publicKeyInBlake160` column in the key info table, the `address` can be removed to better ensure data consistency.
> Remove address column from key info table

- packages/neuron-ui/package.json
- packages/neuron-wallet/package.json
- yarn.lock
Since `node-hid`(a core dep of ledgerjs) does not yet support Electron 10 [1][2], we are unable to upgrade to `electron@10` at this time.
We can use `electron@9.3.2` to fix Electron security vulnerability[3].
ref:
[1]: https://github.com/node-hid/node-hid/issues/392#issuecomment-689851753
[2]: https://dev.azure.com/nervosnetwork/neuron/_build/results?buildId=14339&view=logs&j=40a2506f-20a1-5aae-73bc-340188bb2ddc&t=c2e6b964-e27a-5612-839d-af8b35c5c1c4&l=107
[3]: https://github.com/electron/electron/security/advisories/GHSA-2q4g-w47c-4674
> bump electron from 10.1.3 to 9.3.2

- packages/neuron-ui/src/components/PasswordRequest/index.tsx
- packages/neuron-ui/src/containers/Main/hooks.ts
- packages/neuron-ui/src/services/remote/remoteApiWrapper.ts
- packages/neuron-ui/src/services/remote/sudt.ts
- packages/neuron-ui/src/states/stateProvider/actionCreators/sudt.ts
- packages/neuron-ui/src/types/App/index.d.ts
- packages/neuron-ui/src/types/Controller/index.d.ts
- packages/neuron-ui/src/types/Subject/index.d.ts
Add 'migrate-acp' handler in the PasswordRequest Component to send acp-migration transaction with wallet_id and password.
> feat: handle 'migrate-acp' command in UI

- packages/neuron-ui/src/containers/Navbar/navbar.module.scss
This commit sets the sync-status-text fit in the rest space so that the ring-progress-bar will not be squeezed.
> fix: fix layout of sync status in the navbar

- package.json
- packages/neuron-wallet/package.json
- yarn.lock
Please note that the version of yarn is now specified because of a problem with `hw-app-ckb`[1]. I've created a PR fix for `hw-app-ckb`, but if `hw-app-ckb` hasn't released a new version this Friday, we may need to merge this PR.
ref:
[1]: https://github.com/obsidiansystems/hw-app-ckb/issues/9
> chore: bump ledgerjs version

- packages/neuron-ui/src/components/HardwareSign/index.tsx
- packages/neuron-ui/src/services/remote/index.ts
- packages/neuron-ui/src/utils/enums.ts
- packages/neuron-wallet/src/services/transaction-sender.ts
* If the connection to the device fails, win32 needs to search the device again to get the correct status
* fix the device calls the `getDeviceCkbAppVersion` API in sleep mode, renderer process loses response
> fix: hardware wallet windows compatibility

- packages/neuron-wallet/src/block-sync-renderer/sync/indexer-cache-service.ts
- packages/neuron-wallet/src/block-sync-renderer/sync/queue.ts
- packages/neuron-wallet/src/database/address/meta.ts
- packages/neuron-wallet/src/models/asset-account-info.ts
- packages/neuron-wallet/src/services/cells.ts
- packages/neuron-wallet/tests/block-sync-render/indexer-cache-service.intg.test.ts
It has to add indexing for the legacy acp cells, otherwise it couldn't correctly reconstruct the transaction history for a wallet in certain circumstances.
> fix: include legacy acp script for indexing

- packages/neuron-ui/src/components/SUDTAccountList/index.tsx
- packages/neuron-ui/src/utils/hooks/createSUDTAccount.ts
- packages/neuron-ui/src/utils/hooks/index.ts
- packages/neuron-ui/src/utils/hooks/isInsufficient.ts
This commit moves two hooks from `sudt account list` to `utils hooks`
1. hook to check if it's sufficient to create a sudt account
2. hook to generate a transaction to a create sudt account
> refactor: add public hooks

- azure-pipelines.yml
@kellyshang 
Let's see if this `or` expression works on for both master and rc branches on the release pipeline.
> fix: release pipeline for both master and rc branches

- packages/neuron-wallet/src/services/asset-account-service.ts
- packages/neuron-wallet/tests/services/asset-account-service.test.ts
This commit filters invalid token info(empty token info) out of the token info list
> fix: filter invalid token info out

- packages/neuron-wallet/tests/services/asset-account-service.test.ts
After upgrading to 0.2.4, typeorm's `findMetadata` method no longer accepts normal JavaScript objects.
This pr should fix https://github.com/nervosnetwork/neuron/pull/2022
ref: https://github.com/typeorm/typeorm/issues/5676#issuecomment-599008952
> fix: typeorm validation

- .github/workflows/package.yml
- .github/workflows/unit_tests.yml
This commit flushes caches by updating the cache key to remove a cached broken package in the CI, which made CI always failed.
> ci: flush caches

- .github/workflows/package.yml
Enable it when windows certificate is ready and Azure is disabled.
> Disable github action for packaging

- .github/workflows/merge_released_into_develop.yml
use ubuntu-latest instead of ubuntu-16.04 since it's deprecated
> ci: update runner in Merge released into develop action

- packages/neuron-ui/config-overrides.js
Fix spelling of `webpackCofnig` -> `webpackConfig`
> Update config-overrides.js by fixing variable spelling

- .github/workflows/package.yml
- .github/workflows/unit_tests.yml
- azure-pipelines.yml
MacOS 10.14 has been removed from Azure Pipeline
Ref: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml
> ci: update macos vm image to 11

- packages/neuron-wallet/src/controllers/api.ts
The original RPC error was wrapped in `err.message`, this commit unwraps it so that the original message will be displayed directly
> fix: fix error message of fee rate not enough

- packages/neuron-ui/src/components/TransactionList/index.tsx
When decimal of sudt is greater than 8, the copied value was
truncated by ellipsis, this commit fixes it to be an entire
value.
> Fix copying sudt amount

- packages/neuron-wallet/tests/services/tx/transaction-sender.test.ts
The mock in tests should be updated due to https://github.com/nervosnetwork/neuron/pull/2290/files#diff-6b4e52aade78db37f085688194f39382d8411f142f051ac17a199f52f6953babR547
> fix: fix test which is broken due to deprecated dao api

- packages/neuron-wallet/src/controllers/api.ts
The error.code was covered even error.message.code was undefined,
with that some errors are not handled by UI. This commit fix
this bug by adding a pre-condition that error.message.code
should not be undefined
> fix: fix code of error

- .github/workflows/check_checksums.yml
This workflow compares checksums generated from release artifacts
with those listed in release note to check if artifacts are
valid.
> ci: check checksums after publishment

- packages/neuron-ui/src/components/SUDTAccountList/index.tsx
- packages/neuron-ui/src/components/SUDTCreateDialog/index.tsx
- packages/neuron-ui/src/utils/hooks/createSUDTAccount.ts
1. add an error message box to prompt the error message
2. next button is disabled when account type is missing
3. 
Before:
After:
> fix: fix error message of creating sudt/acp account

- .github/workflows/package.yml
- .github/workflows/package_for_test.yml
- .github/workflows/unit_tests.yml
Node.js 16.14.2, which is default in GitHub Action, introduces
a bug of npm, and should be fixed in 2022/04/05 but actually not.
Specify Node.js to 16.4.0 to avoid this exception.
Ref: https://github.com/nodejs/node/issues/42397
> ci: set node version to 16.4.0

- packages/neuron-wallet/src/models/chain/live-cell.ts
- packages/neuron-wallet/tests/models/chain/live-cell.test.ts
Caveat: Since there're no scripts of hash type `data1`, on-chain testing is suspended.
> feat: support syncing cells those have script of hash type 'data1'

- packages/neuron-wallet/tests/setupAndTeardown/transactions.fixture.ts
use acp code hash from sdk instead of a fake one
> test: fix test fixture

- packages/neuron-wallet/src/controllers/api.ts
error.message is serialized in some cases so the error.message.code
cannot be read directly. This pr try to deserialize the message to
get error code from RPC
> fix: fix api wrapper

- packages/neuron-ui/src/components/SendFieldset/index.tsx
Timelock should be available for any format of secp256k1 address
but not only short version one.
--- screenshots ---
Before
After
> feat: allow secp256k1 address to be timelocked

- packages/neuron-ui/src/components/Overview/index.tsx
- packages/neuron-ui/src/components/TransactionList/index.tsx
- packages/neuron-wallet/src/locales/en.ts
- packages/neuron-wallet/src/locales/zh-tw.ts
- packages/neuron-wallet/src/locales/zh.ts
- packages/neuron-wallet/src/services/tx/transaction-service.ts
- packages/neuron-wallet/src/utils/export-history.ts
- packages/neuron-wallet/src/utils/to-csv-row.ts
- packages/neuron-wallet/tests/utils/export-history/index.test.ts
- packages/neuron-wallet/tests/utils/to-csv-row/fixtures.json
- packages/neuron-wallet/tests/utils/to-csv-row/index.test.ts
1. fix sudt amount of creating sudt asset account, it was not
set when txType is one of 'create' and 'destroy'
2. update export-history to make exported history consistent
with those displayed in window
--- screenshots ---
Before
After
Before
After
> fix: fix tx history

- packages/neuron-ui/package.json
- packages/neuron-wallet/package.json
- yarn.lock
This commit reinforces address validation by sdk
Address like `ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsq20k2lzuhgvrgacv4tmr88`, which adopts new address format but payload is encoded by bech32 will be disallowed.
Sidenote: new address format requires bech32 encoded payload
> chore: bump ckb sdk to v0.103.1

- packages/neuron-ui/src/components/Receive/index.tsx
- packages/neuron-ui/src/components/Receive/receive.module.scss
- packages/neuron-ui/src/components/SUDTReceive/index.tsx
- packages/neuron-ui/src/components/SUDTReceive/sUDTReceive.module.scss
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/widgets/Icons/AddressTransform.svg
Add a button next to the address in receive tabs to toggle
address foramts between full version and deprecated version.
The switch is designed to be neglectable because the deprecated
format is discouraged.
Ref: https://github.com/Magickbase/neuron-public-issues/issues/22
https://user-images.githubusercontent.com/7271329/171185344-eef47104-d05a-4270-a1b1-e12717430de5.mov
> feat: add address format toggle in receive tabs

- packages/neuron-ui/src/components/HardwareSign/index.tsx
- packages/neuron-ui/src/components/PasswordRequest/index.tsx
- packages/neuron-ui/src/widgets/DropdownButton/dropdownButton.module.scss
- packages/neuron-wallet/src/controllers/offline-sign.ts
- packages/neuron-wallet/src/exceptions/offline-sign.ts
- packages/neuron-wallet/src/locales/en.ts
- packages/neuron-wallet/src/locales/zh-tw.ts
- packages/neuron-wallet/src/locales/zh.ts
- packages/neuron-wallet/tests/controllers/offline-sign.test.ts
1. export tx
i. hd wallet
https://user-images.githubusercontent.com/12881040/171125983-b62753a1-7b85-4237-8762-2cd167fbd7cb.mov
ii. hard wallet
https://user-images.githubusercontent.com/12881040/171126111-6e67d87f-b796-4ed6-ac38-d481bf0b0b96.mov
2. sign and export tx
i. hd wallet
https://user-images.githubusercontent.com/12881040/171126153-ea7d34d9-5214-4811-aedf-0d63441d3387.mov
ii. hard wallet
https://user-images.githubusercontent.com/12881040/171126240-b4097267-428b-490d-9d35-587ee5be15ed.mov
> Refine export tx

- packages/neuron-ui/src/components/ImportHardware/common.ts
- packages/neuron-ui/src/components/ImportHardware/confirming.tsx
- packages/neuron-ui/src/components/ImportHardware/detect-device.tsx
- packages/neuron-ui/src/components/ImportHardware/import-error.tsx
- packages/neuron-ui/src/components/ImportHardware/import-success.tsx
- packages/neuron-ui/src/components/ImportHardware/index.tsx
- packages/neuron-ui/src/components/ImportHardware/name-wallet.tsx
- packages/neuron-ui/src/components/ImportHardware/select-model.tsx
https://user-images.githubusercontent.com/12881040/174038403-909d07e5-2f3e-467f-a749-d3507518346c.mov
> fix: Fix open create hardware wallet after open import seed.

- .github/ISSUE_TEMPLATE/synchronization-issue.yml
Add a user-friendly issue template for synchronization issues
> chore: add issue template for synchronization issue

- packages/neuron-wallet/package.json
- packages/neuron-wallet/src/controllers/multisig.ts
- packages/neuron-wallet/tests/controllers/multisig.test.ts
Multisig config created by ckb-cli can also import by Neuron.
https://user-images.githubusercontent.com/12881040/177503032-6392fb72-4881-49d9-8e64-2043efa990d9.mov
> feat: Multisig import and export config compatible with ckb-cli

- packages/neuron-wallet/src/controllers/app/menu.ts
- packages/neuron-wallet/src/locales/en.ts
- packages/neuron-wallet/src/locales/zh-tw.ts
- packages/neuron-wallet/src/locales/zh.ts
This PR adds an extra contact method via mail for users who
are not programmers and don't know GitHub.
A sub-menu named 'Contact Us' is added in "Menu -> Help" that
invokes a local mail client to send help request to
"neuron@magickbase.com"
Ref: https://github.com/Magickbase/neuron-public-issues/issues/30
> feat: add 'contact us' in the menu -> help submenu

- package.json
- packages/neuron-ui/src/components/CompensationPeriodTooltip/index.tsx
- packages/neuron-ui/src/components/NervosDAORecord/index.tsx
- packages/neuron-ui/src/tests/getDAOCellStatus/fixtures.json
- packages/neuron-ui/src/utils/const.ts
- packages/neuron-ui/src/utils/getDAOCellStatus.ts
1. Nervos DAO can withdraw after deposit right now
https://user-images.githubusercontent.com/12881040/182278063-7a1cd917-f5bb-40ab-8f11-95430dd138f8.mov
2. Nervos DAO can unlock after `180 epoch`
https://user-images.githubusercontent.com/12881040/183242339-97810095-9712-4d56-841b-5784b551b63d.mov
> feat: The header dep's block no need 4 epochs ago.

- packages/neuron-wallet/src/controllers/api.ts
- packages/neuron-wallet/src/services/indexer.ts
- packages/neuron-wallet/src/services/monitor/base.ts
- packages/neuron-wallet/src/services/monitor/index.ts
- packages/neuron-wallet/tests/services/monitor.test.ts
1. Set ckb node data path to an empty directory, always delete mainnet ckb indexer data.
2. Delete ckb indexer data after start ckb to ensure ckb indexer data directory is correctly.
> fix: Fix some exception from set ckb node path

- packages/neuron-wallet/package.json
- packages/neuron-wallet/src/utils/rpc-request.ts
- packages/neuron-wallet/tests/controllers/sync-api.test.ts
- packages/neuron-wallet/tests/utils/rpc-request.test.ts
- packages/neuron-wallet/tsconfig.json
- yarn.lock
`undici` is created by Node.js org. Using it in Node.js is better.
> feat: use undici to replace axios

- .github/workflows/check_checksums.yml
- .github/workflows/package.yml
- .github/workflows/package_for_test.yml
- packages/neuron-wallet/electron-builder.yml
- packages/neuron-wallet/package.json
- scripts/release-checksums.rb
- yarn.lock
------
apple silicon support
Ref: https://github.com/Magickbase/neuron-public-issues/issues/62
Check List
------
default
none
> Fix:apple silicon support #2510

- .github/workflows/package.yml
- .github/workflows/package_for_test.yml
- .github/workflows/unit_tests.yml
- README.md
- package.json
- packages/neuron-wallet/package.json
- packages/neuron-wallet/src/utils/to-csv-row.ts
- packages/neuron-wallet/tests/services/address.test.ts
- packages/neuron-wallet/tests/utils/redist-check/index.test.ts
- yarn.lock
------
Bump Node.js from 16 to 18
Ref: https://github.com/Magickbase/neuron-public-issues/issues/72
Check List
------
default
none
> chore: bump node from 16 to 18

- package.json
- packages/neuron-ui/src/widgets/GlobalDialog/index.tsx
- yarn.lock
------
After updating our node version to v18, we got a problem that the neuron client cannot be opened automatically.
Ref: https://github.com/Magickbase/neuron-public-issues/issues/80
before: 
after:
Check List
------
e2e Test
none
> Fix:resolve cannot open electron window automatically after update node version to v18

- packages/ckb-indexer/package.json
- packages/neuron-ui/package.json
- packages/neuron-wallet/package.json
- yarn.lock
------
As title.
This error(https://github.com/Magickbase/neuron/actions/runs/3627132547/jobs/6116742113#step:8:54) has been found several times in CI.
we used `npx` to replace installing `rimraf` to avoid `not recognized as an internal or external command`.
Ref: https://github.com/Magickbase/neuron-public-issues/issues/86
Check List
------
e2e Test
none
> Chore: call rimraf with npx

- .github/workflows/package.yml
- .github/workflows/package_for_test.yml
- CHANGELOG.md
- lerna.json
- packages/neuron-ui/package.json
- packages/neuron-ui/src/components/PasswordRequest/index.tsx
- packages/neuron-wallet/package.json
- packages/neuron-wallet/src/services/transaction-sender.ts
- packages/neuron-wallet/tests/services/tx/transaction-sender.test.ts
We've updated the certificate of Neuron for windows, which is issued by **DigiCert** and distributed to [Magickbase](https://github.com/Magickbase/), the active developer team of Neuron. With this update, a warning may appear on updating Neuron by `check for update` inside Neuron, please don't worry and download Neuron from [GitHub Release](https://github.com/nervosnetwork/neuron/releases) to adopt the new certificate.
* #2551: Fix sending multisig tx when input cell's length is greater than 1.(@yanguoyu)
**Full Changelog**: https://github.com/nervosnetwork/neuron/compare/v0.103.2...v0.103.3
> Release v0.103.3

- packages/neuron-ui/src/components/NervosDAO/hooks.ts
- packages/neuron-wallet/src/services/cells.ts
- packages/neuron-wallet/src/services/tx/transaction-service.ts
- packages/neuron-wallet/tests/services/cells.test.ts
1. For the nerovs dao page, there are many rpc requests, use batch request.
2. Because some users have many relations with others cells, left join twice to search inputs and outputs.
3. Find unlock transactions with the status that equal Dead or Pending.
> fix: Use batch rpc to request result. Optimization sql search.

- .github/workflows/update-issue-status.yml
Add a github action to manage stale issues,
a replied issue will be marked stale if no
activity for 60 days and closed after 7 days
without updates.
The task is set to run on UTC 5:30 everyday
Ref: https://github.com/Magickbase/neuron-public-issues/issues/94
> ci: add github action to manage stale issues

- .github/workflows/update-issue-status.yml
The option close-issue-reason is an enum of completed and 
not_planned. I missed it and set it to a custom value which led 
to ci failure.
Ref: https://github.com/marketplace/actions/close-stale-issues#close-issue-reason
> fix: fix close-issue-reason in close stale issue action

- packages/neuron-wallet/src/services/ckb-runner.ts
- packages/neuron-wallet/src/services/monitor/base.ts
- packages/neuron-wallet/tests/services/ckb-runner.test.ts
1. Try to check ckb is alive every 30s.
2. When startCkb try to check the ckb is null.
> fix: Sometimes RPC timeout but ckb is living

- packages/neuron-ui/src/locales/zh.json
Simplified Chinese of "migrate" should be "迁移"
> fix: fix typo of migrate

- packages/neuron-wallet/src/controllers/networks/index.ts
- packages/neuron-wallet/src/main.ts
- packages/neuron-wallet/src/services/ckb-runner.ts
This pr will fix https://github.com/Magickbase/neuron-public-issues/issues/96. Here is why I changed the code like this:
When starting the sync process in `ckb-runner`, the network `genesisHash` has not refresh, so it will start a wrong sync process that connects the `mainnet` database and use the `testnet` data, so I remove the start and stop from `ckb-runner`. But after I remove the stop sync process from `ckb-runner`, `NetworksController` may delay stop the sync process because of `debounceTime`. We should stop the sync process right now when the `ckb` node is stopped otherwise the sync process may use the wrong net data. So I remove `debounceTime` from `NetworksController` otherwise the sync process may delay stopping.
1. Remove `debounceTime` because it has `distinctUntilChanged` …
> fix: Restart or stop sync process by connectionStatusSubject.

- packages/neuron-wallet/src/utils/ckb-rpc.ts
Because the light client's send_transaction only has one parameter.
> fix: Adapt light client send transaction.

- scripts/download-ckb.sh
ckb light client portable@v0.2.2 works on ubuntu 20.04 while ckb
light client@v0.2.2 doesn't due to openssl compatibility
> fix: use linux portable for compatibility

- packages/neuron-ui/src/components/NervosDAO/index.tsx
When the `depositValue` is invalid, it displays the error in the textField, but it will throw an exception when valid wheater it's big than the max deposit value, and when the `depositValue` is invalid, it's no need to set max `depositValue`.
https://user-images.githubusercontent.com/12881040/230840833-6f981c6f-22ba-4c8f-9985-88e35fa5495c.mov
> fix: Fix when enter over 8 decimal crash.

- .github/workflows/add-replied-label.yml
The "replied" label will be added if an issue has been replied by a user who has write access.
It's expected to work with the update-issue-status action to manage issues automatically.
> ci: add an action to add "replied" label automatically

- .github/workflows/add-replied-label.yml
This action(https://github.com/nervosnetwork/neuron/actions/runs/4760813903)
was triggered by a comment in pull request because pull request
is also regarded as an issue in GitHub. And this action threw
an exception that `actions-ecosystem/action-add-label` is not
found.
This commit fixed the typo of `actions-ecosystem/action-add-labels`
And add a step to filter pull request out
Ref:
actions-ecosystem/action-add-labels: https://github.com/actions-ecosystem/action-add-labels
> ci: fix the add-label action

- .github/workflows/add-replied-label.yml
The external action is out-of-date on permission management in github action, so the label action is re-written in github rest api for maintenance.
Ref: https://github.com/actions-ecosystem/action-add-labels/issues/444
> refactor: use github rest api to update labels

- packages/neuron-ui/src/containers/Notification/index.tsx
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/services/subjects.ts
- packages/neuron-ui/src/stories/GlobalDialog.stories.tsx
- packages/neuron-ui/src/utils/const.ts
- packages/neuron-ui/src/utils/hooks/index.ts
- packages/neuron-ui/src/widgets/GlobalDialog/index.tsx
When we get the `migrate` log from `ckb` node log.
If the user has clicked migrate, it will continue to migrate. If the user has not clicked migrate, there will show the migrate dialog.
After clicking `Cancel`, the dialog will hide until the user refreshes the page or reopen `Neuron`.
When clicking `Backup`, `Neuron` will open the data dictionary, when clicking `migrate`, `Neuron` will record the migrated version. Then If we need to migrate in the future, we only need to change the migrated version.
https://user-images.githubusercontent.com/12881040/234271807-2201f1a4-c3c7-42d7-9c5c-d67359bc7ebf.mov
> feat: Add dialog warn for migrate date to 0.108

- packages/neuron-ui/src/components/TransactionList/index.tsx
- packages/neuron-ui/src/components/TransactionList/transactionList.module.scss
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-wallet/src/controllers/api.ts
- packages/neuron-wallet/src/controllers/app/show-window.ts
feat: provide loading for the detail button on the history page
https://user-images.githubusercontent.com/9160743/236616145-b1ffce10-2aaf-4c6d-bd34-8d7cb78d11f3.mp4
> feat: provide loading for the detail button on the history page

- packages/neuron-ui/src/components/SUDTUpdateDialog/sUDTUpdateDialog.module.scss
1. before the change
2. after the change
> fix: Add min-height avoid dialog truncation

- README.md
Add some description for speed up electron download
> docs: proxy when install

- packages/neuron-wallet/src/block-sync-renderer/sync/light-connector.ts
- packages/neuron-wallet/src/block-sync-renderer/sync/queue.ts
- packages/neuron-wallet/src/database/chain/index.ts
- packages/neuron-wallet/src/services/indexer.ts
- packages/neuron-wallet/src/services/multisig.ts
- packages/neuron-wallet/src/services/sync-progress.ts
- packages/neuron-wallet/src/utils/ckb-rpc.ts
- packages/neuron-wallet/tests/block-sync-renderer/queue.test.ts
- packages/neuron-wallet/tests/controllers/multisig.test.ts
- packages/neuron-wallet/tests/controllers/sync-api.test.ts
- packages/neuron-wallet/tests/services/light-runner.test.ts
1. When append scripts are empty means remove append scripts, so remove empty judgment
2. resultFormatters should not return null. Because the Method will ignore null or undefined.
3. When clear cache start monitor should start node right now and only delete current wallet sync progress.
4. Save decimal number to SQLite when the field is `timestamp` or `blockNumber`
> fix: fix some bugs

- packages/neuron-ui/src/components/NervosDAO/hooks.ts
- packages/neuron-ui/src/components/NervosDAO/index.tsx
- packages/neuron-ui/src/utils/hooks/useGetCountDownAndFeeRateStats.ts
1. When refreshing in DAO page, the network is not ready, so ignore 404.
2. Reset deposited DAO capacity when opening dialog to fix https://github.com/Magickbase/neuron-public-issues/issues/146.
3. Create a common `generateDaoDepositTx` hook to create a deposit tx whether `despositeValue` change or `suggestFeeRate` change.
> fix: Fix deposit dao

- packages/neuron-ui/src/components/HardwareSign/index.tsx
- packages/neuron-ui/src/components/VerifyHardwareAddress/index.tsx
- packages/neuron-ui/src/states/stateProvider/actionCreators/sudt.ts
- packages/neuron-wallet/src/block-sync-renderer/sync/indexer-cache-service.ts
- packages/neuron-wallet/src/block-sync-renderer/task-wrapper.ts
- packages/neuron-wallet/src/types/module.d.ts
- packages/neuron-wallet/tests/setupAndTeardown/index.ts
refactor: resolve some eslint warnings
> refactor: resolve some eslint warnings

- packages/neuron-wallet/src/block-sync-renderer/sync/light-connector.ts
- packages/neuron-wallet/src/controllers/app/index.ts
- packages/neuron-wallet/src/controllers/networks/index.ts
- packages/neuron-wallet/src/services/ckb-runner.ts
- packages/neuron-wallet/src/services/indexer.ts
- packages/neuron-wallet/src/services/light-runner.ts
- packages/neuron-wallet/src/services/monitor/ckb-monitor.ts
- packages/neuron-wallet/src/utils/ckb-rpc.ts
- packages/neuron-wallet/src/utils/common.ts
- packages/neuron-wallet/tests/services/ckb-runner.test.ts
- packages/neuron-wallet/tests/services/indexer.test.ts
- packages/neuron-wallet/tests/services/light-runner.test.ts
1. When the light client just started, some dep cells should wait for a moment to get. So if the current light client can not get the dep cells, wait for 10 seconds and try it again.
2. If process. stdout is `pipe`, it should add event listener, otherwise when call process. kill, we need to destroy the stdout
3. If we clean data without cleaning the indexer data, we should not restart the ckb node.
4. When we clean data, restart the sync task to avoid the check node skipping.
> fix: Fix some bugs.

- packages/neuron-wallet/package.json
- packages/neuron-wallet/tests/controllers/sync-api.test.ts
- yarn.lock
chore: upgrade typeorm to 0.2.45
`typeorm` introduced `glob` starting from version `0.2.26`. This library has a dependency on `events`.
The original test code had issues with the mock implementation of `events`, which have now been fixed.
> chore: upgrade typeorm to 0.2.45

- packages/neuron-ui/src/components/Send/index.tsx
- packages/neuron-ui/src/styles/mixin.scss
- packages/neuron-ui/src/widgets/Calendar/focusControl.tsx
- packages/neuron-ui/src/widgets/Calendar/index.tsx
- packages/neuron-ui/src/widgets/DatetimePicker/index.tsx
feat: improve the interaction design of the DatetimePicker component
Ref: https://github.com/Magickbase/neuron-public-issues/issues/151 
https://github.com/nervosnetwork/neuron/assets/9160743/a6775127-a1df-437a-b5f9-d6770e466d97
> feat: improve the interaction design of the DatetimePicker component

- packages/neuron-ui/src/components/MultisigAddress/hooks.ts
- packages/neuron-wallet/src/block-sync-renderer/sync/light-connector.ts
- packages/neuron-wallet/src/services/sync-progress.ts
- packages/neuron-wallet/tests/block-sync-renderer/light-connector.test.ts
1. Any multisig script should sync from 0.
2. When adding multisig address after deletion, it should start syncing again.
3. Every 10s to refresh multisig sync height, not when multisig address changes.
> fix: Fix multisig with light client

- packages/neuron-wallet/src/services/ckb-runner.ts
- scripts/download-ckb.sh
1. Some arm64 can not run not portable x64 ckb
2. When starting neuron to develop, the ckb file should add arch.
> fix: download x64 portable and fix running neuron locally

- .github/workflows/comment_for_pr_package.yml
- .github/workflows/package_for_test.yml
- packages/neuron-wallet/scripts/notarize.js
Because the trigger on `workflow_run` needs the action's yml file to exist on the default branch.
https://github.com/yanguoyu/neuron/pull/38#issuecomment-1569914593 is an example of a comment package for committing to PR.
1. Add pull_request trigger for the `Package Neuron for Test` action
2. Skip the code sign if there not exist certificate
3. Because for pull_request action, there is no access to write comments. Add a workflow to add comments on the PR. https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#restrictions-on-repository-forks. Then when the trigger on push event, add a comment on the commit, else add a comment on the PR.
> feat: Add package for pull request and comment

- packages/neuron-wallet/src/services/multisig.ts
- packages/neuron-wallet/tests/services/multisig.test.ts
The same `multisig` configs will create [MultisigOutput](https://github.com/nervosnetwork/neuron/blob/develop/packages/neuron-wallet/src/database/chain/entities/multisig-output.ts) entity. So we should remove duplicate config before calling `get_cells`.
> fix: Remove duplicate config when get cells.

- packages/neuron-ui/src/components/NervosDAO/hooks.ts
- packages/neuron-ui/src/components/NervosDAO/index.tsx
- packages/neuron-ui/src/tests/formatters/padFractionDigitsIfDecimal/index.test.ts
- packages/neuron-ui/src/utils/formatters.ts
Automatically pad decimal places when the deposit dialog automatically provides a maximum value with decimals
Ref: https://github.com/Magickbase/neuron-public-issues/issues/172
https://github.com/nervosnetwork/neuron/assets/9160743/564ada69-e6b4-4245-afa6-1c5706973d3c
> Automatically pad decimal places when the deposit dialog automatically provides a maximum value with decimals

- packages/neuron-wallet/src/block-sync-renderer/sync/indexer-cache-service.ts
- packages/neuron-wallet/src/block-sync-renderer/sync/queue.ts
- packages/neuron-wallet/src/database/chain/entities/sync-info.ts
- packages/neuron-wallet/src/database/chain/entities/tx-lock.ts
- packages/neuron-wallet/src/database/chain/index.ts
- packages/neuron-wallet/src/database/chain/migrations/1684488676083-TxLock.ts
- packages/neuron-wallet/src/database/chain/ormconfig.ts
- packages/neuron-wallet/src/services/tx/transaction-persistor.ts
- packages/neuron-wallet/src/services/tx/transaction-service.ts
- packages/neuron-wallet/src/utils/const.ts
- packages/neuron-wallet/tests/block-sync-renderer/indexer-cache-service.intg.test.ts
- packages/neuron-wallet/tests/block-sync-renderer/queue.test.ts
- packages/neuron-wallet/tests/services/tx/transaction-persistor.test.ts
- packages/neuron-wallet/tests/services/tx/transaction-service.test.ts
To search others' addresses at the history page, I create a table `tx_lock` to save `tx_hash` map `lockHash`
1. Only save local wallets' lock into `input` and `output`, and save others' cell lockHash to `tx_lock`
2. When searching by address, search addresses from `input`, `output` and `tx_lock`.
3. When getting transaction detail, get the transaction detail from RPC.
4. Record the last block number when caching tx to `indexer_tx_hash_cache`
> refactor: Optimize input and output storage

- packages/neuron-ui/package.json
- packages/neuron-wallet/package.json
When Lerna executes package scripts, it uses the package directory as the execution directory.
However, Prettier only reads the `.prettierignore` file in the execution directory, so the root-level `.prettierignore` file is not effective when running `npx lerna run --no-bail --stream precommit`.
Since VSCode only reads the `.prettierignore` file in the opened folder, the file must exist in the root directory. Therefore, the current solution is adapted from https://github.com/prettier/prettier/issues/4081#issuecomment-1157180927.
> fix: the .prettierignore file did not take effect during precommit

- .github/workflows/check-code-style.yml
Keeping the same code style will make the project more predictable, especially when finding some code in the whole project.
To keep the code in the same style, we can 
- A. add the `"prettier/prettier": "error"` in the eslint config, and run eslint in the CI
- B. run prettier when we commit, and run `prettier && git diff --exit-code` in the CI
- C. or something others
This PR using the option A as the solution, but this solution may not fit the habits of most Neuron contributors, so I need some feedback to continue this PR
> chore: enable prettier check in ci

- .github/workflows/package.yml
- .github/workflows/package_for_test.yml
- .github/workflows/unit_tests.yml
- packages/neuron-ui/src/components/Overview/index.tsx
- packages/neuron-ui/src/components/Overview/overview.module.scss
- packages/neuron-ui/src/widgets/CopyZone/copyZone.module.scss
- packages/neuron-ui/src/widgets/CopyZone/index.tsx
------
As title.
Ref:https://github.com/Magickbase/neuron-public-issues/issues/162
Check List
------
e2e Test
> Fix: style issue in balance module

- .github/workflows/check-code-style.yml
This PR picks the supported files of prettier when running the code style checking. 
The below example shows it skip the `*.lock` and pick the `*.ts`
- commit: https://github.com/homura/neuron/commit/6a3afbc0f09ac2941e62512a375d1897daa3ec2c
- workflow result: https://github.com/homura/neuron/actions/runs/5412266831/jobs/9836139129#step:7:2
> chore: check only the supported types

- .github/workflows/add-replied-label.yml
A breaking change was introduced in github-scripts@v5 that all rest apis are moved from top-level to top-level.rest.
The breaking change in v5 was not noticed when the script was upgraded from v4 to v6
Ref: https://github.com/octokit/plugin-rest-endpoint-methods.js/releases/tag/v5.0.0
---
Before:
After:
> ci: fix api of github-scripts

- .github/workflows/package_for_test.yml
Because the `outputs.ref` is the fork repo's branch name. So we should add the repo parameter for `checkout` action when the event is `issue_comment`.
Examples:
Trigger by push: https://github.com/yanguoyu/neuron/actions/runs/5419801750
Trigger by issue_comment with current repo: [pr](https://github.com/yanguoyu/neuron/pull/52), action: https://github.com/yanguoyu/neuron/actions/runs/5441117221
Trigger by issue_comment with fork repo: [pr](https://github.com/yanguoyu/neuron/pull/51), action: https://github.com/yanguoyu/neuron/actions/runs/5441115012
> chore(CI): Checkout pr branch when event is issue_comment

- packages/neuron-ui/src/components/FormattedTokenAmount/formattedTokenAmount.module.scss
- packages/neuron-ui/src/components/FormattedTokenAmount/index.tsx
- packages/neuron-ui/src/components/History/RowExtend.tsx
- packages/neuron-ui/src/components/History/history.module.scss
- packages/neuron-ui/src/components/History/index.tsx
- packages/neuron-ui/src/components/Overview/index.tsx
- packages/neuron-ui/src/components/Overview/overview.module.scss
- packages/neuron-ui/src/components/SUDTSend/sUDTSend.module.scss
- packages/neuron-ui/src/components/TransactionList/index.tsx
- packages/neuron-ui/src/components/TransactionStatusWrap/index.tsx
- packages/neuron-ui/src/components/TransactionStatusWrap/transactionStatusWrap.module.scss
- packages/neuron-ui/src/components/UANDisplay/index.module.scss
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/widgets/Table/table.module.scss
------
As title.
Ref: https://github.com/Magickbase/neuron-public-issues/issues/168
Check List
------
e2e Test
> fix: recent activities style questions

- packages/neuron-ui/src/components/History/history.module.scss
- packages/neuron-ui/src/components/History/index.tsx
- packages/neuron-ui/src/components/HistoryDetailPage/historyDetailPage.module.scss
- packages/neuron-ui/src/components/HistoryDetailPage/index.tsx
- packages/neuron-ui/src/components/Overview/index.tsx
- packages/neuron-ui/src/containers/Navbar/index.tsx
- packages/neuron-ui/src/widgets/Icons/GoBack.svg
- packages/neuron-ui/src/widgets/Icons/icon.tsx
- packages/neuron-ui/src/widgets/Table/index.tsx
- packages/neuron-ui/src/widgets/Table/table.module.scss
------
As title.
Ref: https://github.com/Magickbase/neuron-public-issues/issues/170
Check List
------
e2e Test
> Fix: hover click transaction style exception

- .github/workflows/package.yml
- .github/workflows/package_for_test.yml
- .github/workflows/unit_tests.yml
- .husky/pre-commit
- README.md
- lerna.json
- package.json
- packages/neuron-ui/src/components/NervosDAO/hooks.ts
- packages/neuron-ui/src/components/NervosDAO/index.tsx
- yarn.lock
When on the DAO page, the deposit DAO transaction will generate when the suggestion fee changes. So when the users withdraw DAO, the withdraw DAO transaction may change to a deposit transaction.
When the deposit dialog is not open, the deposit transaction will not generate.
> fix: Avoid generate deposit DAO when the dialog is not visible.

- .github/workflows/package.yml
- .github/workflows/package_for_test.yml
- .github/workflows/unit_tests.yml
- .husky/pre-commit
- CHANGELOG.md
- README.md
- lerna.json
- package.json
- packages/neuron-ui/package.json
- packages/neuron-ui/src/components/NervosDAO/hooks.ts
- packages/neuron-ui/src/components/NervosDAO/index.tsx
- packages/neuron-wallet/package.json
- yarn.lock
- [CKB@v0.110.0](https://github.com/nervosnetwork/ckb/releases/tag/v0.110.0) was released on May. 17th, 2023. This version of CKB node is now bundled and preconfigured in Neuron.
- [CKB Light Client@v0.2.4](https://github.com/nervosnetwork/ckb-light-client/releases/tag/v0.2.4) was released on May. 28th, 2023. This version of CKB Light Client is now bundled and preconfigured in Neuron
◆ **CKB Light Client** is only activated on testnet, thus only `light testnet` is enabled in Neuron. **CKB Light Client on Mainnet** requires a hardfork on the mainnet in the future.
◆ **CKB@v0.110** requires data migration, which is irreversible. Be cautious to start the migration without a backup. [How to back up data of ckb node](https://github.com/nervosnetwork/neuron/issues/2557#issue-1512510978)
> On …
> Release v0.110.2

- packages/neuron-ui/src/components/MultisigAddress/index.tsx
- packages/neuron-ui/src/components/OfflineSignDialog/index.tsx
- packages/neuron-ui/src/components/OfflineSignDialog/offlineSignDialog.module.scss
- packages/neuron-ui/src/components/PricePanel/index.tsx
- packages/neuron-ui/src/components/SUDTSend/hooks.ts
- packages/neuron-ui/src/components/SUDTSend/index.tsx
- packages/neuron-ui/src/components/SUDTSend/sUDTSend.module.scss
- packages/neuron-ui/src/components/SendFromMultisigDialog/sendFromMultisigDialog.module.scss
- packages/neuron-ui/src/components/TransactionFeePanel/index.tsx
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/states/stateProvider/reducer.ts
- packages/neuron-ui/src/types/App/index.d.ts
- packages/neuron-ui/src/utils/enums.ts
fix issue: 
- https://github.com/Magickbase/neuron-public-issues/issues/208
> Fix asset accounts

- packages/neuron-ui/src/components/ApproveMultisigTxDialog/index.tsx
- packages/neuron-ui/src/components/DepositDialog/depositDialog.module.scss
- packages/neuron-ui/src/components/DepositDialog/hooks.ts
- packages/neuron-ui/src/components/DepositDialog/index.tsx
- packages/neuron-ui/src/components/HardwareSign/index.tsx
- packages/neuron-ui/src/components/NervosDAO/hooks.ts
- packages/neuron-ui/src/components/NervosDAO/index.tsx
- packages/neuron-ui/src/components/PageContainer/pageContainer.module.scss
- packages/neuron-ui/src/components/Send/hooks.ts
- packages/neuron-ui/src/components/SendFromMultisigDialog/hooks.ts
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/services/remote/offline.ts
- packages/neuron-ui/src/services/remote/wallets.ts
- packages/neuron-ui/src/states/init/app.ts
- packages/neuron-ui/src/states/stateProvider/reducer.ts
- packages/neuron-ui/src/types/App/index.d.ts
- packages/neuron-ui/src/utils/getMultisigSignStatus.ts
- packages/neuron-ui/src/utils/hooks/index.ts
- packages/neuron-wallet/src/utils/ckb-rpc.ts
Reference to https://github.com/Magickbase/neuron-public-issues/issues/216#issuecomment-1630039869
> fix: Fix generate transaction when deposit all without balance.

- compatible.csv
- packages/neuron-ui/src/containers/Main/index.tsx
- packages/neuron-ui/src/containers/Navbar/index.tsx
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/services/remote/app.ts
- packages/neuron-ui/src/services/remote/remoteApiWrapper.ts
- packages/neuron-ui/src/types/App/index.d.ts
- packages/neuron-ui/src/types/Subject/index.d.ts
- packages/neuron-ui/src/widgets/AlertDialog/index.tsx
- packages/neuron-wallet/electron-builder.yml
- packages/neuron-wallet/package.json
- packages/neuron-wallet/src/controllers/api.ts
- packages/neuron-wallet/src/locales/en.ts
- packages/neuron-wallet/src/locales/zh-tw.ts
- packages/neuron-wallet/src/locales/zh.ts
- packages/neuron-wallet/src/models/subjects/show-global-dialog.ts
- packages/neuron-wallet/src/services/node.ts
- packages/neuron-wallet/tests/services/node.test.ts
All of the scenes should start ckb external.
1. When Neuron has an updated version, and the running external ckb version is bigger than Neuron's internal ckb version
This scene can test with https://github.com/nervosnetwork/neuron/pull/2807, the external ckb version should be bigger than v0.109.0
2. When the running external ckb version is not compatible with Neuron.
This scene can be tested with the current pr package, and the external ckb version should not be 0.109 ~ 0.110
> feat: Add check ckb node update or compatibility

- packages/neuron-wallet/src/block-sync-renderer/index.ts
- packages/neuron-wallet/src/block-sync-renderer/sync/indexer-cache-service.ts
- packages/neuron-wallet/src/database/chain/entities/indexer-tx-hash-cache.ts
- packages/neuron-wallet/src/database/chain/entities/sync-info.ts
- packages/neuron-wallet/src/database/chain/entities/tx-lock.ts
- packages/neuron-wallet/src/database/chain/migrations/1694746034975-TxLockAddArgs.ts
- packages/neuron-wallet/src/database/chain/ormconfig.ts
- packages/neuron-wallet/src/services/addresses.ts
- packages/neuron-wallet/src/services/tx/transaction-persistor.ts
- packages/neuron-wallet/src/services/wallets.ts
- packages/neuron-wallet/src/utils/queue.ts
- packages/neuron-wallet/tests/block-sync-renderer/index/resetSyncTask.test.ts
- packages/neuron-wallet/tests/services/address.test.ts
- packages/neuron-wallet/tests/services/tx/transaction-persistor.test.ts
- packages/neuron-wallet/tests/services/wallets.test.ts
Fixed https://github.com/Magickbase/neuron-public-issues/issues/282.
1. Save entity into `indexer_tx_hash_cache` order by the block number
2. Create a queue to check generate address
3. When starting the sync process, check whether there exist some lock args belonging to the Neuron wallet
> fix: Fix miss saving some inputs and outputs with optimize input and output storage

- packages/neuron-ui/src/widgets/TextField/index.tsx
This PR patches the label of a textfield by a fallback that uses a field name. It should be fixed in the next release that `label` should be limited to a string because it has its own semantic meaning.
Before
After
> fix: patch label of textfield when it's not a string

- packages/neuron-ui/src/components/DepositDialog/hooks.ts
- packages/neuron-ui/src/components/DepositDialog/index.tsx
- packages/neuron-ui/src/components/History/RowExtend.tsx
- packages/neuron-ui/src/components/History/index.tsx
- packages/neuron-ui/src/components/SUDTAccountList/sUDTAccountList.module.scss
- packages/neuron-ui/src/components/SUDTAccountPile/sUDTAccountPile.module.scss
- packages/neuron-ui/src/components/SUDTMigrateToExistAccountDialog/index.tsx
- packages/neuron-ui/src/components/SUDTMigrateToNewAccountDialog/index.tsx
- packages/neuron-ui/src/components/SUDTReceiveDialog/index.tsx
- packages/neuron-ui/src/components/SUDTReceiveDialog/sUDTReceiveDialog.module.scss
- packages/neuron-ui/src/components/SpecialAssetList/index.tsx
- packages/neuron-ui/src/components/UANDisplay/index.module.scss
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/states/stateProvider/actionCreators/sudt.ts
- packages/neuron-ui/src/states/stateProvider/actionCreators/wallets.ts
- packages/neuron-ui/src/utils/baseActions.ts
- packages/neuron-ui/src/widgets/SUDTAvatar/sUDTAvatar.module.scss
- packages/neuron-wallet/src/block-sync-renderer/tx-status-listener.ts
1. Fix styles when the desc or symbol is overlong
2. Close dialog when submitting success with migrating to create a new account
3. Reset the deposit value when the dialog's visible changes and show an error dialog when the deposit fails.
4. Ignore update the transaction that calls `get_transaction` failed.
> Fix: fix rc/110.3 bugs, detail in comments

- packages/neuron-ui/src/components/PageContainer/index.tsx
- packages/neuron-ui/src/components/SUDTSend/index.tsx
- packages/neuron-ui/src/components/SUDTSend/sUDTSend.module.scss
- packages/neuron-ui/src/components/SignAndVerify/index.tsx
- packages/neuron-ui/src/widgets/Dialog/dialog.module.scss
- packages/neuron-ui/src/widgets/Table/table.module.scss
- packages/neuron-wallet/src/services/multisig.ts
- packages/neuron-wallet/src/services/tx/transaction-persistor.ts
1. Lock time cells should be saved into the local database.
2. For the light client skip update the multisig sync block number if the address is not the current wallet. Because of light client only subscribe current wallet multisig address
3. Fixed able head style.
4. Fix styles when the asset name is too long
5. Fix some elements that are hidden when Neuron height is the smallest
> fix: fixed locktime cell,multisig sync blocknumber, table head style

- .github/workflows/update_valid_target.yml
- scripts/update-valid-target.js
https://github.com/yanguoyu/neuron/pull/92 is create by the action.
> fix: use create event to update valid target

- packages/neuron-ui/src/components/PageContainer/index.tsx
- packages/neuron-ui/src/containers/Main/index.tsx
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/services/subjects.ts
- packages/neuron-ui/src/utils/hooks/index.ts
If we need to run `ckb migrate` for the ckb data, the neuron will show a dialog to help users migrate ckb data. Once users have selected migrate, the neuron will auto-migrate next time if the before-migrate version is the same. The migrating version will be saved in the electron local storage, if we want to show the migrate dialog again, we can delete the local storage, which can be found at `/Users/${username}/Library/Application Support/Neuron/Local Storage`.
https://github.com/nervosnetwork/neuron/assets/12881040/3da60666-e6ba-47c3-a392-cbc0276ed4f8
> fix: Show the migrate ckb data dialog

- packages/neuron-wallet/src/controllers/export-debug.ts
- packages/neuron-wallet/src/utils/logger.ts
1. Format date for electron-log, define for `file` and `console` to output unified date.
2. Sometimes user's DB connection is not opened with an unknown exception, so catch the exception when exporting public key info.
> fix: Format date when output log. Catch exception when export public key info.

- scripts/release-checksums.rb
Remove the unexpected whitespace so the checksum table can be generated by a loop in the future
> chore: remove unexpected whitespace in checksum table

- packages/neuron-wallet/src/utils/logger.ts
1. Before
```
[2023-10-19T06:44:40.522Z] [info] Network:      switched to:,[object Object]
```
2. After
```
[2023-10-19T06:39:15.782Z] [info]  Network:     switched to: {
id: '4a04d0de-cbf4-46c9-b383-5c73372387d6',
name: 'devdd',
remote: 'http://127.0.0.1:8114',
genesisHash: '0x10639e0895502b5688a6be8cf69460d76541bfa4821629d86d62ba0aae3f9606',
type: 1,
chain: 'ckb_testnet',
readonly: false
}
```
> fix: use electron-log format styles. The function can not transform object correctly.

- .github/workflows/package.yml
- .github/workflows/package_for_test.yml
- packages/neuron-wallet/electron-builder.yml
- packages/neuron-wallet/scripts/customSign.js
ref: 
- why use key locker: https://knowledge.digicert.com/solution/digicert-keylocker.html
- how to use key locker in github action: https://docs.digicert.com/en/digicert-keylocker/ci-cd-integrations/script-integrations/github-integration-ksp.html
- Update certificate of Neuron for windows: https://github.com/Magickbase/neuron-public-issues/issues/188
---
Package Neuron for test: https://github.com/nervosnetwork/neuron/actions/runs/6658266030/job/18094724690#step:17:124
Package Neuron for Release Draft: https://github.com/nervosnetwork/neuron/actions/runs/6658347469/job/18094990967#step:15:120
> ci: use key locker to sign neuron for windows

- .github/workflows/check_checksums.yml
Issue: 
https://github.com/Magickbase/neuron-public-issues/issues/295
Test Job:
https://github.com/devchenyan/neuron/actions/runs/6687543940
Test check_checksums.yml:
```
name: Check Checksums
on:
push:
release:
types: [published, prereleased]
jobs:
compare:
name: Compare checksums
runs-on: macos-latest
steps:
- name: Checkout
uses: actions/checkout@v3
- name: Generate checksums from artifacts
run: ruby ./scripts/release-checksums.rb v0.111.0 | tee generated_checksums.txt
- name: Fetch checksums from release note
run: |
curl "https://api.github.com/repos/nervosnetwork/neuron/releases/tags/v0.111.0" |\
python3 -c "import sys, json; print(\"\n\".join(json.load(sys.stdin)['body'].splitlines()[-11:]))" |\
tee release_note_checksums.txt
- name: Compare
run: diff generated_checksums.txt …
```
> feat: upgrade "Compare checksums" action

- packages/neuron-ui/src/widgets/TextField/index.tsx
issue: https://github.com/Magickbase/neuron-public-issues/issues/311
https://github.com/nervosnetwork/neuron/assets/11756869/0735ccf1-8947-4e11-906f-25b50ab28bc5
> fix: address input issue

- packages/neuron-ui/src/components/NetworkSetting/index.tsx
- packages/neuron-ui/src/components/NetworkSetting/networkSetting.module.scss
1. Click here to switch the network type, the tooltip is just a information
> fix: Click current network button to switch type.

- packages/neuron-wallet/src/services/networks.ts
- packages/neuron-wallet/src/services/settings.ts
Refer to https://github.com/Magickbase/neuron-public-issues/issues/320.
Delete the settings and network file, download the 0.103.1 Neuron, and start. Then update to 0.110.1.
The settings file location:
Mac OS: /Users/${username}/Library/Application Support/Neuron/settings.json
Windows: C:/Users/${username}/AppData/Roaming/Neuron/settings.json
The network file location:
Mac OS: /Users/${username}/Library/Application Support/Neuron/networks/index.json
Windows: C:/Users/${username}/AppData/Roaming/Neuron/networks/index.json
> fix: Fix migrate settings and network.

- packages/neuron-ui/src/components/NervosDAO/index.tsx
- packages/neuron-ui/src/states/stateProvider/reducer.ts
- packages/neuron-ui/src/utils/getSyncStatus.ts
- packages/neuron-wallet/src/controllers/export-debug.ts
- packages/neuron-wallet/src/services/ckb-runner.ts
- packages/neuron-wallet/src/services/light-runner.ts
- packages/neuron-wallet/src/services/node.ts
- packages/neuron-wallet/tests/controllers/export-debug.test.ts
- packages/neuron-wallet/tests/services/node.test.ts
To avoid unexpected dialog that notifies the user of an external node shown.
1. Set the process to null when the started pid equals the current process pid.
2. Stop the get tip number when switching the network and start after starting the node.
3. Add debounce time to start node, that is avoid the user switching the internal network faster.
> fix: Avoid unexpected dialog shown.

- packages/neuron-wallet/src/block-sync-renderer/sync/light-connector.ts
- packages/neuron-wallet/src/block-sync-renderer/sync/queue.ts
Refer to https://github.com/Magickbase/neuron-public-issues/issues/322
[wallet.json](https://github.com/nervosnetwork/neuron/files/13388483/issue-322-xpubkey.json) Here is a watched wallet to test this issue. The wallet has a transaction that receives over 3000 cells' inputs. https://pudge.explorer.nervos.org/transaction/0x1731a226064e9b8b51b7238420452191872dfaf65a91ba1d4ccaec2cf3ed3b2e
We can compare the difference between the release and the current PR package.
> fix: Fix light client sync slow when fetch much transactions.

- packages/neuron-wallet/src/block-sync-renderer/sync/connector.ts
- packages/neuron-wallet/src/block-sync-renderer/sync/indexer-cache-service.ts
- packages/neuron-wallet/src/block-sync-renderer/sync/indexer-connector.ts
- packages/neuron-wallet/src/block-sync-renderer/sync/light-connector.ts
- packages/neuron-wallet/src/block-sync-renderer/sync/queue.ts
- packages/neuron-wallet/src/database/chain/entities/indexer-tx-hash-cache.ts
- packages/neuron-wallet/src/database/chain/entities/sync-progress.ts
- packages/neuron-wallet/src/database/chain/index.ts
- packages/neuron-wallet/src/database/chain/migrations/1701234043431-IndexerTxHashCacheRemoveField.ts
- packages/neuron-wallet/src/database/chain/ormconfig.ts
- packages/neuron-wallet/src/services/light-runner.ts
- packages/neuron-wallet/src/services/sync-progress.ts
- packages/neuron-wallet/src/utils/ckb-rpc.ts
- packages/neuron-wallet/tests/block-sync-renderer/connector.test.ts
- packages/neuron-wallet/tests/block-sync-renderer/indexer-cache-service.intg.test.ts
- packages/neuron-wallet/tests/block-sync-renderer/indexer-connector.test.ts
- packages/neuron-wallet/tests/block-sync-renderer/light-connector.test.ts
Refer to https://github.com/Magickbase/neuron-public-issues/issues/329
> fix: Fix light client sync tx type.

- packages/neuron-wallet/src/controllers/anyone-can-pay.ts
- packages/neuron-wallet/src/controllers/offline-sign.ts
- packages/neuron-wallet/src/services/hardware/hardware.ts
- packages/neuron-wallet/src/services/transaction-sender.ts
- packages/neuron-wallet/tests/controllers/anyone-can-pay.test.ts
- packages/neuron-wallet/tests/controllers/offline-sign.test.ts
- packages/neuron-wallet/tests/services/tx/transaction-sender.test.ts
The sign method is refactored to allow unidentified lock scripts
while skipped lock scripts are prevented outside the sign method
Notice that skipped lock scripts validation is not adopted when
a multisig transaction because it's explictly thrown
when no private key is found. It may be intended.
> refactor: refactor sign method to allow unidentified lock scripts

- packages/neuron-ui/src/components/Send/hooks.ts
- packages/neuron-ui/src/components/Send/index.tsx
- packages/neuron-ui/src/components/Send/send.module.scss
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/states/init/chain.ts
- packages/neuron-ui/src/types/App/index.d.ts
- packages/neuron-ui/src/types/Controller/index.d.ts
- packages/neuron-wallet/src/controllers/api.ts
- packages/neuron-wallet/src/controllers/wallets.ts
- packages/neuron-wallet/src/models/chain/transaction.ts
- packages/neuron-wallet/src/services/cells.ts
- packages/neuron-wallet/src/services/transaction-sender.ts
- packages/neuron-wallet/src/services/tx/transaction-generator.ts
- packages/neuron-wallet/tests/services/cells.test.ts
- packages/neuron-wallet/tests/services/tx/transaction-generator.test.ts
- packages/neuron-wallet/tests/services/tx/transaction-sender.test.ts
Refer to https://github.com/Magickbase/neuron-public-issues/issues/217
After broading a tx successfully, disconnect the network, and then the cell status will always be sent.
https://github.com/nervosnetwork/neuron/assets/12881040/6ff9899b-0f30-4784-ad69-9bbea7e0e930
> feat: Support use sent cell when send CKB

- packages/neuron-ui/src/widgets/AlertDialog/alertDialog.module.scss
fix issue: https://github.com/Magickbase/neuron-public-issues/issues/337
> fix: Pop up window can be rolled when error message is long

- packages/neuron-wallet/package.json
- packages/neuron-wallet/src/services/cells.ts
- packages/neuron-wallet/src/services/transaction-sender.ts
- yarn.lock
The latest spore SDK includes some breaking changes that make Renovate cannot upgrade it automatically by bumping only
https://github.com/Magickbase/neuron/pull/301
> refactor: upgrade spore sdk

- packages/neuron-ui/src/components/MultisigAddress/hooks.ts
- packages/neuron-ui/src/components/MultisigAddress/index.tsx
- packages/neuron-ui/src/services/remote/multisig.ts
- packages/neuron-wallet/src/controllers/api.ts
- packages/neuron-wallet/src/controllers/multisig.ts
- packages/neuron-wallet/src/services/multisig.ts
- packages/neuron-wallet/src/services/sync-progress.ts
- packages/neuron-wallet/tests/controllers/multisig.test.ts
- packages/neuron-wallet/tests/services/multisig.test.ts
Refer to https://github.com/Magickbase/neuron-public-issues/issues/348
1. Remove `walletId` for `get-multisig-config` API
2. Disabled `Approve` button when the current wallet can not sign for the multisig config.
https://github.com/nervosnetwork/neuron/assets/12881040/32906371-9c4e-4421-951f-2edfe9fd372f
> fix: Remove walletId for `get-multisig-config` API

- packages/neuron-ui/src/components/NervosDAO/index.tsx
- packages/neuron-ui/src/components/NervosDAORecord/daoRecordRow.module.scss
- packages/neuron-ui/src/components/NervosDAORecord/index.tsx
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/fr.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-wallet/src/controllers/app/index.ts
Refer to https://github.com/Magickbase/neuron-public-issues/issues/350
1. Disabled withdraw when there is no ckb balance
2. Enable withdraw when there exists ckb balance
> fix: Disable unlock when there is no ckb.

- packages/neuron-ui/src/components/PageContainer/hooks.ts
- packages/neuron-ui/src/components/PageContainer/index.tsx
- packages/neuron-ui/src/components/PageContainer/pageContainer.module.scss
- packages/neuron-ui/src/components/SyncStatus/index.tsx
- packages/neuron-ui/src/components/SyncStatus/syncStatus.module.scss
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/fr.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/services/remote/remoteApiWrapper.ts
- packages/neuron-ui/src/services/remote/wallets.ts
- packages/neuron-ui/src/types/App/index.d.ts
- packages/neuron-ui/src/types/Controller/index.d.ts
- packages/neuron-wallet/src/controllers/api.ts
Refer to https://github.com/Magickbase/neuron-public-issues/issues/304.
1. Show the last setted start block number
2. If the current set start block number is less than before
3. If the current set start block number is bigger than the header tip block number
> feat: Optimize the setting of sync start block in light client mode.

- packages/neuron-ui/src/containers/Navbar/index.tsx
- packages/neuron-ui/src/containers/Navbar/navbar.module.scss
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/es.json
- packages/neuron-ui/src/locales/fr.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/types/App/index.d.ts
- packages/neuron-ui/src/widgets/AlertDialog/alertDialog.module.scss
- packages/neuron-ui/src/widgets/AlertDialog/index.tsx
Refer to https://github.com/Magickbase/neuron-public-issues/issues/254
Currently, the compatible table explorer is ready, so add the link to view the compatible table.
https://github.com/nervosnetwork/neuron/assets/12881040/c786ef84-d742-43b4-a176-c0617050427d
> fix: Add learn more link for compatible table

- packages/neuron-ui/src/components/HardwareSign/HardwareSignOnPage.tsx
- packages/neuron-ui/src/components/HardwareSign/hardwareSign.module.scss
- packages/neuron-ui/src/components/HardwareSign/hooks.ts
- packages/neuron-ui/src/components/MultisigAddress/index.tsx
- packages/neuron-ui/src/components/OfflineSignDialog/index.tsx
- packages/neuron-ui/src/components/PasswordRequest/PasswordRequestInPage.tsx
- packages/neuron-ui/src/components/PasswordRequest/hooks.ts
- packages/neuron-ui/src/components/PasswordRequest/index.tsx
- packages/neuron-ui/src/components/PasswordRequest/passwordRequest.module.scss
- packages/neuron-ui/src/components/Send/hooks.ts
- packages/neuron-ui/src/components/SendTxDetail/TxTopology.tsx
- packages/neuron-ui/src/components/SendTxDetail/hooks.ts
- packages/neuron-ui/src/components/SendTxDetail/index.tsx
- packages/neuron-ui/src/components/SendTxDetail/sendTxDetail.module.scss
- packages/neuron-ui/src/components/SendTxDetail/txTopology.module.scss
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/es.json
- packages/neuron-ui/src/locales/fr.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/router.tsx
- packages/neuron-ui/src/states/init/chain.ts
- packages/neuron-ui/src/types/App/index.d.ts
- packages/neuron-ui/src/utils/enums.ts
- packages/neuron-ui/src/widgets/Tooltip/tooltip.module.scss
- packages/neuron-wallet/src/models/chain/input.ts
- packages/neuron-wallet/src/models/chain/output.ts
- packages/neuron-wallet/src/services/cells.ts
- packages/neuron-wallet/src/services/tx/transaction-generator.ts
- packages/neuron-wallet/tests/services/cells.test.ts
Refer to https://github.com/Magickbase/neuron-public-issues/issues/217.
When select `Unconfirmed Outputs are allowed in this transaction.`, we can view the transaction detail.
https://github.com/nervosnetwork/neuron/assets/12881040/6fc0db6e-ce8a-43a8-9f44-ee6c9a7fdd4b
> Feat: view chain transaction detail

- .github/workflows/package.yml
- .github/workflows/update_ckb_client_versions.yml
- .github/workflows/update_neuron_compatible.yml
Secrets are defined in specific environment to be protected by
rules, so the environment should be specified in workflow to
load secrets correspondingly.
Ref: https://github.com/Magickbase/neuron-public-issues/issues/364
> ci: specify environments in some workflows

- packages/neuron-ui/src/locales/es.json
- packages/neuron-ui/src/locales/fr.json
So target language option can be recognized by the target language label
> fix: no translation of language options

- packages/neuron-ui/src/components/History/RowExtend.tsx
Before network connect
After network connect
> fix: If node is connecting, show '--' for confirmation

- packages/neuron-ui/src/components/History/RowExtend.tsx
When the tx is confirming also shows --
https://github.com/nervosnetwork/neuron/assets/12881040/72a0194a-0f7a-42df-9d26-90443327677a
> fix: When the tx is confirming also show --

- packages/neuron-wallet/src/services/node.ts
- packages/neuron-wallet/tests/services/node.test.ts
Because the first sync dialog only shows when the network is the default full ckb node, the sync will stuck and wait for the user to confirm when the first sync and the select network is the default mainnet
> fix: The first sync only stuck full ckb node start.

- packages/neuron-wallet/src/utils/shannonToCKB.ts
- packages/neuron-wallet/src/utils/to-csv-row.ts
After the discussion in https://github.com/nervosnetwork/neuron/pull/3111, I realized that we just need to rewrite `shannonToCKB` with `formatUnit`.
> refactor: rewrite shannonToCKB with lumos formatUnit

- packages/neuron-ui/src/components/GeneralSetting/generalSetting.module.scss
- packages/neuron-ui/src/components/GeneralSetting/index.tsx
- packages/neuron-ui/src/components/Settings/settings.module.scss
- packages/neuron-ui/src/containers/Main/index.tsx
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/es.json
- packages/neuron-ui/src/locales/fr.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/services/localCache.ts
- packages/neuron-ui/src/utils/index.ts
- packages/neuron-ui/src/utils/wakeScreen.ts
Add an option for users to keep the screen awake. Refer to https://github.com/Magickbase/neuron-public-issues/issues/319
Because the screen recording cannot capture the screen lock, the video was not uploaded.
> feat: Keep screen awake

- packages/neuron-wallet/src/utils/sudt-value-to-amount.ts
- packages/neuron-wallet/tests/utils/sudt-value-to-amount/fixtures.json
Refactor and add two test cases. Verified.
> refactor: rewrite sudtValueToAmount with formatUnit in neuron-wallet

- packages/neuron-wallet/src/block-sync-renderer/sync/light-synchronizer.ts
If calling `createBatchRequest` with an empty array, will throw the error `Rpc(JsonRpcError(Error { code: MethodNotFound, message: "Method not found", data: None }))`
> fix: If all of the previous Tx hashes are cell base, skip fetch tx.

- .github/workflows/unit_tests.yml
- packages/neuron-ui/package.json
- packages/neuron-wallet/package.json
- yarn.lock
Electron 30: Chromium 124.0.6367.49, Node 20.11.1, V8 12.4
Update CI Node to v20.11.1 to match with Electron v30's Node version.
We are not using features mentioned in Breaking Changes.
https://releases.electronjs.org/release/v30.0.0
This upgrade fixes the `Intl.NumberFormat.prototype.format()` issue metioned in [#3219](https://github.com/nervosnetwork/neuron/pull/3129)
> build(ci): upgrade Electron to v30, ci Node to v20.11.1

- packages/neuron-wallet/src/block-sync-renderer/index.ts
- packages/neuron-wallet/src/block-sync-renderer/sync/light-synchronizer.ts
- packages/neuron-wallet/src/block-sync-renderer/sync/queue.ts
- packages/neuron-wallet/src/block-sync-renderer/sync/synchronizer.ts
- packages/neuron-wallet/src/services/addresses.ts
- packages/neuron-wallet/src/services/wallets.ts
- packages/neuron-wallet/tests/block-sync-renderer/index/resetSyncTask.test.ts
- packages/neuron-wallet/tests/block-sync-renderer/queue.test.ts
This is an issue from [`discord`](https://discord.com/channels/956765352514183188/1084671124211769364/1212615721897689088)
The reason is the generated address and sync process are not synchronized. So when there is not enough address, the sync process will stop saving `localSavedBlockNumber`. Then after the new address is derived, it will start syncing from the right block number.
> fix: When address is not enough, stop update localSavedBlockNumber

- packages/neuron-wallet/src/block-sync-renderer/sync/light-synchronizer.ts
- packages/neuron-wallet/src/services/sync-progress.ts
- packages/neuron-wallet/src/services/wallets.ts
- packages/neuron-wallet/tests/block-sync-renderer/light-synchronizer.test.ts
1. When setting a bigger number than the current synced block number, reset the start block number
Refer to https://github.com/Magickbase/neuron-public-issues/issues/387
3. Fix light client sync when importing an existed or existing wallet.
Refer to https://github.com/Magickbase/neuron-public-issues/issues/388
> Fix light sync

- packages/neuron-ui/package.json
- packages/neuron-ui/src/components/NervosDAO/hooks.ts
- packages/neuron-ui/src/components/WithdrawDialog/index.tsx
- packages/neuron-ui/src/containers/Main/hooks.ts
- packages/neuron-ui/src/services/chain.ts
- packages/neuron-ui/src/utils/hooks/useGetCountDownAndFeeRateStats.ts
- yarn.lock
1. `CKBRPC.createBatchRequest()` in Lumos currently has limited typing info: `any`
```ts
createBatchRequest: <N extends keyof Base, P extends (string | number | object)[], R = any[]>(params?: any) => any;
```
So in this PR I manually added response types in `then` blocks for `CKBRPC.createBatchRequest` calls, e.g. 
```ts
rpc
.createBatchRequest<'getTransaction', string[], CKBComponents.TransactionWithStatus[]>(
depositOutPointHashes.map(v => ['getTransaction', v])
)
.exec()
.then((txs: CKBComponents.TransactionWithStatus[]) => {
```
**I'm working on another PR for Lumos to bring back the right types for `CKBRPC.createBatchRequest()`**
2. In `packages/neuron-ui/src/components/WithdrawDialog/index.tsx`
```ts
calculateMaximumWithdraw(
tx.transaction.outputs[+record.outPoint.index] as …
```
> refactor: replace ckbCore with lumos CKBRPC

- packages/neuron-ui/config-overrides.js
This PR aims to fix a build error in CI caused by require `fs` in lumos config manager.
This is usually a warning, but in CI, it becomes an error.
```sh
neuron-ui: Module not found: Error: Can't resolve 'fs' in '/home/runner/work/neuron/neuron/node_modules/@ckb-lumos/config-manager/lib'
```
**With this PR, there will be no such warning or error.**
**Code in lumos**
https://github.com/ckb-js/lumos/blob/develop/packages/config-manager/src/manager.ts#L107
**Code in bundle.js WITHOUT this PR**, hence the warning in dev and error in CI
------
**Code in bundle.js WITH this PR**.  We don't call `initializeConfigLegacy()` in `neuron-ui` so it's not a problem.
**Job**
https://github.com/nervosnetwork/neuron/actions/runs/9022501373/job/24792170701
> fix: fix ci build error

- packages/neuron-wallet/src/controllers/export-debug.ts
- packages/neuron-wallet/tests/controllers/export-debug.test.ts
1. Export the start block number https://github.com/Magickbase/neuron-public-issues/issues/386
2. Slice the export light client log https://github.com/Magickbase/neuron-public-issues/issues/378
> feat: Export the start block number and slice the light client log.

- .github/workflows/check-code-style.yml
- .github/workflows/check_storybook.yml
- .github/workflows/package.yml
- .github/workflows/package_for_test.yml
- .github/workflows/unit_tests.yml
https://github.com/Magickbase/neuron-public-issues/issues/390
1. `actions/cache@3` => `actions/cache@4`
2. `microsoft/setup-msbuild@v1.3.1` => `microsoft/setup-msbuild@v2`
3. `peter-evans/create-or-update-comment@v3` => `peter-evans/create-or-update-comment@v4`
> ci: upgrade github actions version

- packages/neuron-wallet/src/services/settings.ts
Use the `hex` type when transferring the Buffer to the string to avoid unexpected strings.
> fix: Use hex to avoid unexpected string.

- packages/neuron-wallet/src/controllers/wallets.ts
- packages/neuron-wallet/src/services/sign-message.ts
`Buffer.from(string, 'hex')` the string value should be started without `0x`, so I use Lumos `bytes.bytify` to init Buffer.
> fix: Use lumos to init Buffer

- packages/neuron-ui/src/components/FormattedTokenAmount/index.tsx
- packages/neuron-ui/src/components/History/index.tsx
- packages/neuron-ui/src/components/Overview/index.tsx
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/es.json
- packages/neuron-ui/src/locales/fr.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/types/App/index.d.ts
- packages/neuron-wallet/src/models/chain/transaction.ts
- packages/neuron-wallet/src/services/tx/transaction-service.ts
Refer to https://github.com/Magickbase/neuron-public-issues/issues/335#issuecomment-1996306163
For [Optimize input and output storage](https://github.com/nervosnetwork/neuron/pull/2672), Neuron can not recognize whether the transaction is only sent to the current wallet. So, `For transactions sent to yourself, 'Asset' needs to be shown as '--'.` will not implement.
> fix: Replace `Asset` to `Amount` and better 'Asset' data format

- packages/neuron-wallet/src/block-sync-renderer/sync/light-synchronizer.ts
- packages/neuron-wallet/tests/block-sync-renderer/light-synchronizer.test.ts
Refer to https://github.com/Magickbase/neuron-public-issues/issues/352
I added a [threshold](https://github.com/nervosnetwork/neuron/compare/develop...yanguoyu:opt-light-sync?expand=1#diff-f2ef23eb2dbce7d890a6dc0dc96c7dd8784a29db3313faebefea5718de60227aR26) for different wallets that can sync simultaneously. If the block number difference between the synchronization block number of other wallets and the current wallet block number is not less than this threshold value, they can be synchronized together.
> perf: Optimize synchronization logic for multiple wallets in the light client.

- CHANGELOG.md
- lerna.json
- package.json
- packages/neuron-ui/package.json
- packages/neuron-wallet/package.json
- packages/neuron-wallet/src/services/hardware/ledger.ts
- packages/neuron-wallet/tests/services/hardware/ledger.test.ts
- [CKB@v0.116.1](https://github.com/nervosnetwork/ckb/releases/tag/v0.116.1) was released on May. 11st, 2024. This version of CKB node is now bundled and preconfigured in Neuron.
- [CKB Light Client@v0.3.7](https://github.com/nervosnetwork/ckb-light-client/releases/tag/v0.3.7) was released on Apr. 13th, 2024. This version of CKB Light Client is now bundled and preconfigured in Neuron
Block before `0x6dd077b407d019a0bce0cbad8c34e69a524ae4b2599b9feda2c7491f3559d32c`(at height `13,007,704`) will be skipped in validation.(https://github.com/nervosnetwork/neuron/pull/3157)
---
- 3173: Fix importing an account from a hardware wallet.(@yanguoyu)
**Full Changelog**: https://github.com/nervosnetwork/neuron/compare/v0.116.0...v0.116.1
> Release v0.116.1

- CHANGELOG.md
- lerna.json
- package.json
- packages/neuron-ui/package.json
- packages/neuron-ui/src/components/ImportHardware/detect-device.tsx
- packages/neuron-ui/src/services/remote/hardware.ts
- packages/neuron-ui/src/services/remote/remoteApiWrapper.ts
- packages/neuron-wallet/package.json
- packages/neuron-wallet/src/controllers/api.ts
- packages/neuron-wallet/src/controllers/hardware.ts
- packages/neuron-wallet/src/services/hardware/hardware.ts
- packages/neuron-wallet/src/services/hardware/ledger.ts
- [CKB@v0.116.1](https://github.com/nervosnetwork/ckb/releases/tag/v0.116.1) was released on May. 11st, 2024. This version of CKB node is now bundled and preconfigured in Neuron.
- [CKB Light Client@v0.3.7](https://github.com/nervosnetwork/ckb-light-client/releases/tag/v0.3.7) was released on Apr. 13th, 2024. This version of CKB Light Client is now bundled and preconfigured in Neuron
Block before `0x6dd077b407d019a0bce0cbad8c34e69a524ae4b2599b9feda2c7491f3559d32c`(at height `13,007,704`) will be skipped in validation.(https://github.com/nervosnetwork/neuron/pull/3157)
---
- 3179: Remove the display of the ledger firmware version because it causes the Nervos app to crash on the ledger device.(@yanguoyu)
**Full Changelog**: https://github.com/nervosnetwork/neuron/compare/v0.116.1...v0.116.2 …
> Release v0.116.2

- packages/neuron-ui/src/containers/Main/index.tsx
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/es.json
- packages/neuron-ui/src/locales/fr.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-wallet/src/block-sync-renderer/sync/queue.ts
- packages/neuron-wallet/src/services/ckb-runner.ts
- packages/neuron-wallet/src/services/light-runner.ts
- packages/neuron-wallet/src/utils/toml.ts
- packages/neuron-wallet/tests/services/ckb-runner.test.ts
- packages/neuron-wallet/tests/services/light-runner.test.ts
- packages/neuron-wallet/tests/utils/toml/test.toml
- packages/neuron-wallet/tests/utils/toml/toml.test.ts
Refer to https://github.com/Magickbase/neuron-public-issues/issues/371
https://github.com/nervosnetwork/neuron/assets/12881040/ede180fc-751d-471c-af23-4b3e09565569
> feat: Optimize light client external node detection

- .github/workflows/package_for_test.yml
I am checking no commit after the trigger comment. If someone pushes a new commit, the package should be repacked again to include the latest commit.
https://github.com/yanguoyu/neuron/actions/runs/9484668688 is the failed example.
https://github.com/yanguoyu/neuron/actions/runs/9484691876 is the success example.
> fix: Skip package if the last commit is after the comment

- packages/neuron-ui/src/components/CellManagement/hooks.ts
- packages/neuron-ui/src/components/GeneralSetting/LockWindowDialog/hooks.ts
- packages/neuron-ui/src/components/GeneralSetting/LockWindowDialog/index.tsx
- packages/neuron-ui/src/containers/LockWindow/index.tsx
- packages/neuron-ui/src/containers/LockWindow/lockWindow.module.scss
- packages/neuron-ui/src/containers/LockWindow/verifyWallet.tsx
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/es.json
- packages/neuron-ui/src/locales/fr.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/types/Controller/index.d.ts
- packages/neuron-ui/src/widgets/Dialog/index.tsx
- packages/neuron-ui/src/widgets/SplitPasswordInput/index.tsx
- packages/neuron-wallet/src/controllers/api.ts
- packages/neuron-wallet/src/controllers/cell-management.ts
- packages/neuron-wallet/src/controllers/sign-message.ts
- packages/neuron-wallet/src/services/sign-message.ts
- packages/neuron-wallet/src/types/controller.d.ts
- packages/neuron-wallet/tests/controllers/cell-management.test.ts
- packages/neuron-wallet/tests/services/sign-message.test.ts
Refer to https://github.com/Magickbase/neuron-public-issues/issues/394
https://github.com/nervosnetwork/neuron/assets/12881040/8199a4c3-8acc-40df-a41b-e0c93e88d049
> feat: Support reset lock window password

- packages/neuron-ui/src/components/MultisigAddress/index.tsx
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/es.json
- packages/neuron-ui/src/locales/fr.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
issue: https://github.com/Magickbase/neuron-public-issues/issues/405
> fix: Multisig address sync tip language

- packages/neuron-wallet/src/block-sync-renderer/sync/indexer-cache-service.ts
- packages/neuron-wallet/src/block-sync-renderer/tx-status-listener.ts
- packages/neuron-wallet/src/models/chain/transaction.ts
- packages/neuron-wallet/src/models/chain/tx-status.ts
- packages/neuron-wallet/src/services/rpc-service.ts
- packages/neuron-wallet/src/services/tx/failed-transaction.ts
- packages/neuron-wallet/src/services/tx/transaction-generator.ts
issue: https://github.com/Magickbase/neuron-public-issues/issues/402
> feat: Periodic validation of pending transactions

- .github/workflows/check-code-style.yml
- .github/workflows/check_storybook.yml
- .github/workflows/merge_released_into_develop.yml
- .github/workflows/package.yml
- .github/workflows/package_for_test.yml
- .github/workflows/unit_tests.yml
- .github/workflows/update_ckb_client_versions.yml
- .github/workflows/update_neuron_compatible.yml
- .github/workflows/update_wallet_env.yml
1. set version of node.js 20.15.1
2. bump the followings
- tj-actions/changed-files
- actions/checkout
- peter-evans/create-pull-request
- peterjgrainger/action-create-branch
Ref: https://github.com/Magickbase/neuron-public-issues/issues/366
> ci: bump github actions

- packages/neuron-ui/src/containers/Main/hooks.ts
- packages/neuron-ui/src/containers/Main/index.tsx
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/es.json
- packages/neuron-ui/src/locales/fr.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/types/Subject/index.d.ts
- packages/neuron-wallet/src/controllers/api.ts
- packages/neuron-wallet/src/controllers/wallets.ts
- packages/neuron-wallet/src/models/subjects/command.ts
- packages/neuron-wallet/src/services/wallets.ts
issue: https://github.com/Magickbase/neuron-public-issues/issues/380
https://github.com/user-attachments/assets/497fa2a5-276e-42dd-bd52-133435afcf3f
> feat: Error message for duplicate import of watch wallet

- _typos.toml
Add `passin` to extend-words for running typo check success
> fix: Fix typo check for passin

- packages/neuron-wallet/src/block-sync-renderer/sync/light-synchronizer.ts
- packages/neuron-wallet/src/block-sync-renderer/sync/synchronizer.ts
- packages/neuron-wallet/src/services/sync-progress.ts
- packages/neuron-wallet/tests/block-sync-renderer/synchronizer.test.ts
Fix https://github.com/Magickbase/neuron-public-issues/issues/417#issuecomment-2264388476
> fix: Ignore deleted wallet when ignore duplicate script.

- scripts/admin/decrypt-log/run.ts
This PR makes the log decryption independent of Neuron's source code
> chore: make run.ts independent from neuron

- packages/neuron-wallet/src/controllers/export-debug.ts
- packages/neuron-wallet/src/services/log-encryption.ts
- packages/neuron-wallet/tests/controllers/export-debug.test.ts
Encrypt the blake160 list when admin pk is available to keep the address list private
> feat: encrypt blake160 list in the log

- .github/workflows/package.yml
- packages/neuron-wallet/src/services/log-encryption.ts
Inject LOG_ENCRYPTION_PUBLIC_KEY from github action to
encrypt sensitive log
>  ci: inject environment variables from github action

- .github/workflows/package.yml
Injecting environment variables with `CR` makes the key mismatched.
> fix: remove CRs when inject environment variables 

- packages/neuron-ui/src/components/NervosDAORecord/index.tsx
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/es.json
- packages/neuron-ui/src/locales/fr.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
issue: https://github.com/Magickbase/neuron-public-issues/issues/421
> fix: the remaining time display in Nervos DAO is abnormal

- packages/neuron-ui/src/components/PageContainer/index.tsx
- packages/neuron-ui/src/components/PageContainer/pageContainer.module.scss
- packages/neuron-wallet/src/services/transaction-sender.ts
issue: https://github.com/Magickbase/neuron-public-issues/issues/423
fixed:
> fix: Asset Accounts UI

- packages/neuron-ui/src/locales/en.json
Fix a typo that blocks other CI, e.g. https://github.com/nervosnetwork/neuron/actions/runs/11698582259/job/32579104301?pr=3250#step:3:43
> fix: fix typo of February

- packages/neuron-ui/src/components/SpecialAssetList/hooks.ts
- packages/neuron-ui/src/types/Controller/index.d.ts
- packages/neuron-ui/src/utils/scriptAndAddress.ts
- packages/neuron-wallet/src/models/asset-account-info.ts
- packages/neuron-wallet/src/models/chain/live-cell.ts
- packages/neuron-wallet/src/models/chain/script.ts
target: https://github.com/nervosnetwork/neuron/pull/3255
> feat: handle hash_type:data2

- packages/neuron-ui/src/components/Receive/index.tsx
- packages/neuron-ui/src/components/WalletWizard/hooks.ts
- packages/neuron-ui/src/components/WalletWizard/index.tsx
- packages/neuron-ui/src/components/withWizard/index.tsx
- packages/neuron-ui/src/types/Controller/index.d.ts
- packages/neuron-ui/src/widgets/MnemonicInput/index.tsx
- packages/neuron-wallet/src/controllers/api.ts
- packages/neuron-wallet/src/controllers/app/menu.ts
- packages/neuron-wallet/src/controllers/wallets.ts
- packages/neuron-wallet/src/locales/en.ts
- packages/neuron-wallet/src/locales/es.ts
- packages/neuron-wallet/src/locales/fr.ts
- packages/neuron-wallet/src/locales/zh-tw.ts
- packages/neuron-wallet/src/locales/zh.ts
- packages/neuron-wallet/src/models/keys/hd-public-key-info.ts
- packages/neuron-wallet/src/services/wallets.ts
This PR will not merged. I open a draft PR.
> feat: Support import hardware wallet 24-bit seed

- .github/workflows/spam-comment-detection.yaml
When a comment is added in an issue
1. if the comment has specific words, it will be deleted
2. if the comment has unexpected links, an annotation about safety will be appended.
> ci: add a spam comment detection

- .github/workflows/spam-comment-detection.yaml
The default permission of Neuron repo is read-only so the permission write should be specify explicitly
> ci: set proper permission for spam detection action

- .github/workflows/spam-comment-detection.yaml
1. fix the accessibility issue of secrets, `github.secrets` doesn't work when the permissions field is set
2. fix the regexp to include `http://` when checking if a link is external
> ci: refine ci for spam detection

- packages/neuron-ui/src/components/SignAndVerify/index.tsx
- packages/neuron-ui/src/utils/hooks/useGetCountDownAndFeeRateStats.ts
issue: https://github.com/Magickbase/neuron-public-issues/issues/432
https://github.com/user-attachments/assets/1424444c-5821-4f54-9ed1-932b458fc033
> feat: Optimize Sign/verify Message

- packages/neuron-ui/src/components/MultisigAddress/index.tsx
issue: https://github.com/Magickbase/neuron-public-issues/issues/439
https://github.com/user-attachments/assets/a380fbaa-7d3f-4ca1-b7e4-07a6fc85a426
> fix: Nervos Dao record will lost for a while

- packages/neuron-wallet/src/controllers/offline-sign.ts
issue: 
- https://github.com/Magickbase/neuron-public-issues/issues/438
> fix: password tip

- packages/neuron-ui/src/components/ErrorBoundary/index.tsx
- packages/neuron-wallet/src/controllers/api.ts
issue:
- https://github.com/Magickbase/neuron-public-issues/issues/436
```
[2025-03-12T05:22:49.106Z] [error] [
"UI crash: Cannot destructure property 'status' of 'item' as it is null.",
{
stack: "TypeError: Cannot destructure property 'status' of 'item' as it is null.\n" +
'    at TransactionType (http://localhost:3000/src/components/TransactionType/index.tsx:62:9)\n' +
'    at renderWithHooks (http://localhost:3000/node_modules/.vite/deps/chunk-XKMW3FHY.js?v=249d37e2:19079:26)\n' +
'    at mountIndeterminateComponent (http://localhost:3000/node_modules/.vite/deps/chunk-XKMW3FHY.js?v=249d37e2:21829:21)\n' +
'    at beginWork (http://localhost:3000/node_modules/.vite/deps/chunk-XKMW3FHY.js?v=249d37e2:22810:22)\n' +
'    at beginWork$1 …
```
> feat: Add UI crash logs

- .github/workflows/check_storybook.yml
- .github/workflows/package.yml
- .github/workflows/package_for_test.yml
- .github/workflows/unit_tests.yml
- .github/workflows/update_ckb_client_versions.yml
- .github/workflows/update_neuron_compatible.yml
- .github/workflows/update_wallet_env.yml
1. use lts node.js
2. use latest ubuntu
3. use latset windows
By doing so, exceptions in the latest runtime can be handled early
> ci: bump node and runner in ci

- .github/workflows/package.yml
- .github/workflows/package_for_test.yml
runner.os is more general than matrix.os for platform detection
> ci: use runner.os instead of matrix.os in platform conditions

- packages/neuron-wallet/src/exceptions/transaction.ts
- packages/neuron-wallet/src/locales/ar.ts
- packages/neuron-wallet/src/locales/en.ts
- packages/neuron-wallet/src/locales/es.ts
- packages/neuron-wallet/src/locales/fr.ts
- packages/neuron-wallet/src/locales/zh-tw.ts
- packages/neuron-wallet/src/locales/zh.ts
- packages/neuron-wallet/src/services/transaction-sender.ts
issue:
- https://github.com/Magickbase/neuron-public-issues/issues/464
> feat: Identify and prompt for multisig transaction

- packages/neuron-wallet/src/services/tx/transaction-generator.ts
issue:
- https://github.com/Magickbase/neuron-public-issues/issues/476
> feat: Optimize receive address handling for hardware wallets
