nervosnetwork/neuron

- .travis.yml
- packages/react-app/package.json
> Travis setup

- .eslintrc.js
- .gitignore
- package.json
- packages/electron-app/package.json
- packages/electron-app/src/main.ts
- packages/react-app/package.json
- yarn.lock
> feat: add electron builder

- .travis.yml
- package.json
- packages/electron-app/src/main.ts
- yarn.lock
enable cross env to set environment variables as #6
> enable cross env

- .yarnrc
- yarn.lock
So that yarn would ignore people's local registry and lock file won't change so much.
> Add yarnrc file fixing registry to registry.yarnpkg.com

- .editorconfig
- .vscode/settings.json
- package.json
- packages/electron-app/package.json
- packages/electron-app/tsconfig.json
- packages/react-app/package.json
- packages/react-app/tsconfig.json
- yarn.lock
Cherry-picked ESLint customization from #24, mostly for editors.
> ESLint config

- packages/neuron-ui/package.json
- packages/neuron-ui/src/components/Addresses/index.tsx
- packages/neuron-ui/src/components/App.tsx
- packages/neuron-ui/src/components/History/index.tsx
- packages/neuron-ui/src/components/Receive/index.tsx
- packages/neuron-ui/src/components/Router/index.tsx
- packages/neuron-ui/src/components/Send/index.tsx
- packages/neuron-ui/src/components/Settings/index.tsx
- packages/neuron-ui/src/components/Sidebar/index.tsx
[add router](https://github.com/nervosnetwork/neuron-internal/issues/40)
> feat(neuron-ui): add router and basic components

- packages/neuron-wallet/src/main.ts
that the window can be dragged and moved
> fix(ui): set BrowserWindow's title bar style to default

- packages/neuron-ui/src/components/Addresses/index.tsx
- packages/neuron-ui/src/components/Modal/index.tsx
- packages/neuron-ui/src/components/Router/index.tsx
- packages/neuron-ui/src/utils/storage.ts
@wuyuyue Removing this as it's for demo purpose.
> chore: remove entry for the modal demo

- packages/neuron-ui/src/components/WalletWizard/index.tsx
- packages/neuron-ui/src/styles/layout.scss
re [#47](https://github.com/nervosnetwork/neuron-internal/issues/47)
> feat(neuron-ui): add full-screen layout for wizard

- .editorconfig
- .eslintrc.js
- packages/neuron-ui/public/manifest.json
- packages/neuron-ui/src/components/ActionFlow/index.tsx
- packages/neuron-ui/src/components/Network/index.tsx
- packages/neuron-ui/src/components/Providers/index.tsx
- packages/neuron-ui/src/components/Transfer/index.tsx
- packages/neuron-ui/src/components/WalletDetail/index.tsx
- packages/neuron-ui/src/components/WalletWizard/index.tsx
- packages/neuron-ui/src/containers/Sidebar/index.tsx
- packages/neuron-ui/src/setupTests.ts
- packages/neuron-ui/src/utils/ipc.ts
- packages/neuron-ui/src/widgets/Dialog.tsx
- packages/neuron-wallet/src/Channel.ts
- packages/neuron-wallet/src/mock.ts
re [#66](https://github.com/nervosnetwork/neuron-internal/issues/66)
> chore: set max length to 120 and object imported to multiline

- package.json
- packages/neuron-ui/package.json
- packages/neuron-wallet/package.json
- packages/neuron-wallet/src/Channel.ts
- yarn.lock
Add `ckb-sdk-js` `^0.0.1-alpha.1` dep.
> feat: add ckb sdk from npm

- package.json
- packages/neuron-wallet/package.json
- `start:ui` to start neuron-ui
- `start:wallet` to start neuron-wallet
- `watch:wallet` to hot reload neuron-wallet
- `start` to launch the app
- `watch` to hot reload the app
in neuron-wallet
- `start` to start the wallet
- `build` to build the wallet
- `watch:run` to hot reload wallet
- `watch:build` to hot updating dist
- `watch` to hot reload wallet from source code updating
> chore: update npm scripts

- .travis.yml
- package.json
- packages/neuron-wallet/package.json
- packages/neuron-wallet/setupTests.ts
- packages/neuron-wallet/tests/example.test.ts
- yarn.lock
Experiment travis setup for electron.
Note: unable to make tests run without timeout and fail on Linux. Reconfigured Travis to run w/ `osx` instead of `linux`. Leave making linux work to future.
> Setup electron headless testing

- .travis.yml
- packages/neuron-wallet/tests/example.test.ts
Disable for now to not block us.
> chore(ci): disable e2e tests since it fails with timeout on travis

- packages/neuron-ui/src/components/ActionFlow/index.tsx
- packages/neuron-ui/src/components/Addresses/index.tsx
- packages/neuron-ui/src/components/Router/RoutesWithProps.tsx
- packages/neuron-ui/src/components/Router/index.tsx
- packages/neuron-ui/src/components/Transfer/index.tsx
- packages/neuron-ui/src/components/WalletWizard/actionA.tsx
- packages/neuron-ui/src/components/WalletWizard/actionB.tsx
- packages/neuron-ui/src/components/WalletWizard/createWallet.tsx
- packages/neuron-ui/src/components/WalletWizard/importWallet.tsx
- packages/neuron-ui/src/containers/Header/index.tsx
- packages/neuron-ui/src/containers/MainContent/index.tsx
- packages/neuron-ui/src/containers/Notification/index.tsx
- packages/neuron-ui/src/containers/Providers/index.tsx
- packages/neuron-ui/src/contexts/Wallet.ts
- packages/neuron-ui/src/services/UILayer.ts
- packages/neuron-ui/src/utils/const.ts
- packages/neuron-wallet/.env
- packages/neuron-wallet/package.json
- packages/neuron-wallet/src/channel.ts
- packages/neuron-wallet/src/core.ts
- packages/neuron-wallet/src/env.ts
- packages/neuron-wallet/src/main.ts
- packages/neuron-wallet/src/monitor.ts
- packages/neuron-wallet/src/utils/const.ts
- packages/neuron-wallet/src/wallets/asw.ts
Please notice that the `dispatch` function passed to components can trigger actions in `MainContent`.
> Import export delete wallet

- packages/neuron-wallet/script/package.sh
Not working correctly in Ubuntu without shebang line.
> fix: add shebang line to shell script

- packages/neuron-wallet/package.json
- packages/neuron-wallet/src/preload.ts
> chore(neuron-wallet): add devtron

- packages/neuron-ui/src/components/History/index.tsx
- packages/neuron-ui/src/components/Router/index.tsx
- packages/neuron-ui/src/containers/MainContent/index.tsx
- packages/neuron-ui/src/containers/Providers/index.tsx
- packages/neuron-ui/src/contexts/Chain.ts
- packages/neuron-ui/src/services/UILayer.ts
- packages/neuron-ui/src/types/Channel.d.ts
- packages/neuron-ui/src/utils/SyntheticEventEmitter.ts
- packages/neuron-ui/tsconfig.json
- packages/neuron-wallet/src/channel.ts
- packages/neuron-wallet/src/main.ts
- packages/neuron-wallet/src/preload.ts
- push history on initialization, and monitoring TBD.
- `redirect` listener was added in `Router` in a callback, optimization for re-render will be done in another commit.
> feat(neuron-wallet): push transaction history to neuron-ui

- packages/neuron-ui/src/components/Router/index.tsx
- packages/neuron-ui/src/components/Terminal/index.tsx
- packages/neuron-ui/src/services/Terminal.ts
- packages/neuron-ui/src/services/UILayer.ts
- packages/neuron-ui/src/utils/const.ts
- packages/neuron-wallet/src/channel/index.ts
- packages/neuron-wallet/src/channel/terminal.ts
- packages/neuron-wallet/src/commands/commands.ts
- packages/neuron-wallet/src/commands/dispatcher.ts
- packages/neuron-wallet/src/commands/handlers.ts
- packages/neuron-wallet/src/locales/zh.ts
- packages/neuron-wallet/src/main.ts
- packages/neuron-wallet/src/menu.ts
- packages/neuron-wallet/src/utils/const.ts
add basic functionality of terminal.
styling and shortcuts to be done.
> feat: add terminal with basic functionality

- .gitignore
- packages/neuron-wallet/package.json
- packages/neuron-wallet/src/monitor.ts
- packages/neuron-wallet/src/utils/logger.ts
- yarn.lock
save error logs to neuron-wallet/error.log
> feat(neuron-wallet): save logs to file

- packages/neuron-ui/src/containers/Header/reducer.ts
- packages/neuron-ui/src/containers/MainContent/actionCreators/networks.ts
- packages/neuron-ui/src/containers/Providers/index.tsx
- packages/neuron-ui/src/services/UILayer.ts
- packages/neuron-ui/src/utils/const.ts
- packages/neuron-wallet/src/channel/wallet.ts
- packages/neuron-wallet/src/controllers/netowrks.ts
- packages/neuron-wallet/src/env.ts
- packages/neuron-wallet/src/main.ts
- packages/neuron-wallet/src/services/networks.ts
- packages/neuron-wallet/src/store/NetworksStore.ts
> feat(neuron-wallet): remove networks db

- packages/neuron-ui/src/components/Addresses/Address.ts
- packages/neuron-ui/src/components/Addresses/mock.ts
- packages/neuron-wallet/src/controllers/wallets.ts
- packages/neuron-wallet/src/keys/hd.ts
- packages/neuron-wallet/src/keys/key.ts
- packages/neuron-wallet/src/services/wallets.ts
- packages/neuron-wallet/tests/key.test.ts
- packages/neuron-wallet/tests/store/wallet_store.js
Let's standardize it with `Receiving Address`.
> refactor: Rename receive address to receiving address

- packages/neuron-ui/package.json
- packages/neuron-wallet/package.json
- yarn.lock
`rm -rf` not works on windows platform
> fix: replace `rm -rf` with `rimraf`

- packages/neuron-ui/public/index.html
- packages/neuron-ui/src/components/Mnemonic/index.tsx
- packages/neuron-ui/src/components/ScreenMessages/index.tsx
- packages/neuron-ui/src/components/WalletSubmission/index.tsx
- packages/neuron-ui/src/components/WalletWizard/index.tsx
- packages/neuron-ui/src/containers/Notification/index.tsx
- packages/neuron-ui/src/containers/Providers/index.tsx
- packages/neuron-ui/src/contexts/NeuronWallet/messages.ts
- packages/neuron-ui/src/locales/en.ts
- packages/neuron-ui/src/styles/layout.scss
- packages/neuron-ui/src/widgets/BannerMessages/index.tsx
- packages/neuron-ui/src/widgets/Screen/index.tsx
> feat(neuron-ui): update global messages style to the bootstrap style

- packages/neuron-ui/src/components/LaunchScreen/index.tsx
- packages/neuron-ui/src/components/Receive/index.tsx
- packages/neuron-ui/src/components/Router/index.tsx
- packages/neuron-ui/src/components/Settings/Wallets.tsx
- packages/neuron-ui/src/components/WalletSubmission/index.tsx
- packages/neuron-wallet/src/controllers/wallets.ts
- packages/neuron-wallet/src/utils/initWindow.ts
and adjust new-wallet-detection logic in submission view.
> feat: send active wallet and wallet list to neuron-ui on launch

- packages/neuron-wallet/src/keys/hd.ts
- packages/neuron-wallet/src/keys/key.ts
- packages/neuron-wallet/tests/key.test.ts
* Set default address numbers to 20 and 10
* Update keys test cases about address numbers
> feat: update default address numbers to 20 and 10

- package.json
- packages/neuron-ui/package.json
- packages/neuron-ui/tsconfig.json
- yarn.lock
> Update CRA 3.0.0

- packages/neuron-wallet/src/address/index.ts
- packages/neuron-wallet/src/address/type.ts
- packages/neuron-wallet/src/keys/hd.ts
- packages/neuron-wallet/src/keys/key.ts
- packages/neuron-wallet/src/keys/keystore.ts
- packages/neuron-wallet/tests/walletstore.test.ts
* Add address module for generating and searching
* Refactor key module to make hd more simple
> refactor: add address module and refactor key module

- packages/neuron-wallet/src/address/index.ts
- packages/neuron-wallet/src/address/store.ts
- packages/neuron-wallet/tests/address.test.ts
* Add address store for address module
* Add test cases for address module
* Add `allAddresses()` method for cell module @classicalliu
> feat: Add address store and add test cases

- packages/neuron-wallet/src/services/syncBlocks.ts
- packages/neuron-wallet/src/services/transactions.ts
When find addresses used in fetched transactions, broadcast this info.
> feat: broadcast when addresses used

- packages/neuron-ui/src/components/WalletWizard/index.tsx
> Disable mnemonic textarea input's resizing

- packages/neuron-wallet/src/controllers/wallets.ts
- packages/neuron-wallet/src/services/wallets.ts
- packages/neuron-wallet/tests/services/wallets.test.ts
-  check wallet name exist
-  refactor wallet store test
- broadcast active after creating first wallet
> Fix wallet store

- packages/neuron-ui/src/components/NetworkSetting/index.tsx
- packages/neuron-ui/src/components/WalletSetting/hooks.ts
- packages/neuron-ui/src/components/WalletSetting/index.tsx
- packages/neuron-ui/src/widgets/ContextMenuZone/index.tsx
1. add pointer-events: none on the label in context zone to pass event up
2. add parameters validation on context events.
> fix(neuron-ui): fix events handler on wallet list and network list

- packages/neuron-ui/package.json
- packages/neuron-wallet/package.json
- packages/neuron-wallet/src/appTypes/types.ts
- packages/neuron-wallet/src/entities/Input.ts
- packages/neuron-wallet/src/entities/Output.ts
- packages/neuron-wallet/src/entities/Transaction.ts
- packages/neuron-wallet/src/services/cells.ts
- packages/neuron-wallet/src/services/syncBlocks.ts
- packages/neuron-wallet/src/services/transactions.ts
- packages/neuron-wallet/tests/services/transactions.test.ts
- yarn.lock
> Update SDK to v0.12.0 to support Rylai testnet

- packages/neuron-wallet/src/services/syncBlocks.ts
- packages/neuron-wallet/src/services/transactions.ts
- packages/neuron-wallet/src/startup/loopTask/create.ts
- packages/neuron-wallet/src/utils/lockUtils.ts
- packages/neuron-wallet/tests/utils/lockUtils.test.ts
Using LockUtils to deal with lock/lockHash/address/blake160 convert
> refactor: add LockUtils

- packages/neuron-wallet/src/services/node.ts
each observable will retry 3 times if disconnected, and increase the delay time if failed on retry.
> feat(neuron-wallet): update retry strategy of node service

- packages/neuron-wallet/src/services/syncBlocks.ts
As a temporary workaround.
Syncing infinitely in the renderer process isn't going to work well.
> fix: stop loop when network disabled, auto start while network connected

- tsconfig.json
introduced in TypeScript@3.4, which reduce the time of compiling.
> build: enable incremental building of tsc

- packages/neuron-ui/src/components/WalletSetting/hooks.ts
- packages/neuron-ui/src/contexts/NeuronWallet/settings.ts
- packages/neuron-ui/src/contexts/NeuronWallet/wallet.ts
- packages/neuron-wallet/src/controllers/wallets/index.ts
- packages/neuron-wallet/src/startup/initWindow.ts
filter the path of active wallet addresses, and filter addresses of other wallets
> feat(neuron-wallet): reduce wallet info passed to ui

- packages/neuron-wallet/src/controllers/index.ts
- packages/neuron-wallet/src/controllers/networks/index.ts
- packages/neuron-wallet/src/controllers/networks/methods.ts
- packages/neuron-wallet/src/decorators/validators.ts
- packages/neuron-wallet/src/locales/en.ts
- packages/neuron-wallet/src/locales/zh.ts
- packages/neuron-wallet/src/services/networks.ts
- packages/neuron-wallet/src/services/wallets.ts
- packages/neuron-wallet/src/utils/windowManage.ts
- packages/neuron-wallet/tests/services/networks.test.ts
1. add validation on parameters;
2. add tests of netowrks service
> refactor(neuron-wallet): refactor networks service

- .vscode/settings.json
- package.json
- yarn.lock
> deps: Upgrade TypeScript to 3.5

- packages/neuron-ui/src/containers/Providers/hooks.ts
- packages/neuron-ui/src/services/UILayer.ts
- packages/neuron-wallet/src/controllers/app/index.ts
- packages/neuron-wallet/src/controllers/app/options.ts
- packages/neuron-wallet/src/controllers/helpers.ts
- packages/neuron-wallet/src/controllers/networks/index.ts
- packages/neuron-wallet/src/controllers/wallets/index.ts
- packages/neuron-wallet/src/utils/const.ts
- packages/neuron-wallet/src/utils/windowManage.ts
1. move nav_to and set_ui_locale methods to the app controller and remove corresponding channels;
2. add type definitions on sending messages methods of window manage module.
> refactor(neuron-wallet): refactor app controller

- README.md
- yarn.lock
install lerna explicitly to reduce time of bootstrap.
> build: update bootstrap procedure

- packages/neuron-wallet/src/controllers/app/index.ts
- packages/neuron-wallet/src/controllers/helpers.ts
- packages/neuron-wallet/src/controllers/networks/index.ts
- packages/neuron-wallet/src/controllers/transactions.ts
- packages/neuron-wallet/src/controllers/wallets/index.ts
- packages/neuron-wallet/src/decorators/controller.ts
- packages/neuron-wallet/src/decorators/index.ts
- packages/neuron-wallet/src/router.ts
add a decorator to annotate controllers to specified channels
> feat(neuron-wallet): annotate channel on controller

- packages/neuron-wallet/src/controllers/app/index.ts
- packages/neuron-wallet/src/controllers/helpers.ts
- packages/neuron-wallet/src/controllers/networks/index.ts
- packages/neuron-wallet/src/controllers/transactions.ts
- packages/neuron-wallet/src/controllers/wallets/index.ts
for distinct from Controller class
> refactor(neuron-wallet): rename @Controller to @ControllerDecorator

- packages/neuron-wallet/src/controllers/app/options.ts
- packages/neuron-wallet/src/locales/en.ts
- packages/neuron-wallet/src/locales/zh.ts
- packages/neuron-wallet/src/types/controller/index.d.ts
> feat(neuron-wallet): enable backup

- packages/neuron-ui/src/components/WalletWizard/index.tsx
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh.json
> feat: Polish wallet name/password form

- packages/neuron-ui/src/components/WalletDetail/index.tsx
- packages/neuron-ui/src/containers/Providers/hooks.ts
- packages/neuron-ui/src/contexts/NeuronWallet/wallet.ts
- packages/neuron-ui/src/utils/formatters.ts
- packages/neuron-wallet/src/controllers/app/index.ts
Display wallet name and balance in the wallet detail view.
The currency formatter will be implemented later.
> feat(neuron-ui): add basic currency formatter for the wallet detail view

- packages/neuron-ui/src/components/TransferConfirm/index.tsx
- packages/neuron-ui/src/utils/const.ts
1. update address placeholder according to the current address standard
2. set password input to the type of password
> Update address placeholder

- packages/neuron-ui/src/components/History/hooks.ts
- packages/neuron-ui/src/components/History/index.tsx
- packages/neuron-ui/src/components/TransactionList/index.tsx
- packages/neuron-ui/src/components/WalletDetail/index.tsx
- packages/neuron-ui/src/containers/Providers/hooks.ts
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-wallet/src/controllers/app/index.ts
- packages/neuron-wallet/src/controllers/transactions.ts
1. send recent transactions on initializing the window.
2. display the last 5 in the detail view.
3. extract the `TransactionList` component from `History` and reused in `WalletDetail`
> feat: display recent transactions in the detail view

- packages/neuron-wallet/src/services/node.ts
- packages/neuron-wallet/src/startup/init-app.ts
update connect status by the result of getTipBlockNumber RPC
> refactor(neuron-wallet): move connect detection to node service

- packages/neuron-ui/src/components/History/index.tsx
- packages/neuron-ui/src/contexts/NeuronWallet/chain.ts
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh.json
use 'first, prevoius, next, last' instead of list of page number
> refactor(neuron-ui): refactor pagination

- packages/neuron-ui/src/components/Addresses/index.tsx
- packages/neuron-ui/src/components/Receive/index.tsx
- packages/neuron-ui/src/containers/Providers/hooks.ts
- packages/neuron-ui/src/contexts/NeuronWallet/wallet.ts
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/services/UILayer.ts
- packages/neuron-ui/src/types/global/index.d.ts
- packages/neuron-ui/tsconfig.json
- packages/neuron-wallet/src/controllers/app/index.ts
- packages/neuron-wallet/src/controllers/wallets/index.ts
https://github.com/nervosnetwork/neuron/compare/develop...Keith-CY:display-addresses?expand=1#diff-2873cc75a8b8adbfebbb7b3dc4d3e498R298
A method is required to fetch a bundle of unused addresses. For now only the next one returns. @classicalliu
> refactor: pass addresses to ui with independent method

- packages/neuron-ui/src/components/Addresses/index.tsx
- packages/neuron-ui/src/components/General/index.tsx
- packages/neuron-ui/src/contexts/NeuronWallet/wallet.ts
- packages/neuron-wallet/src/controllers/wallets/index.ts
- packages/neuron-wallet/src/services/wallets.ts
display balances of addresses, and calculate total balance from all addresses.
> feat(neuron-ui): display balance

- packages/neuron-ui/src/components/General/index.tsx
- packages/neuron-ui/src/components/Send/index.tsx
- packages/neuron-ui/src/containers/Providers/hooks.ts
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh.json
cache balance in context for reuse in multiple views
> feat(neuron-ui): display balance in send view

- packages/neuron-ui/src/locales/zh.json
> refactor(neuron-ui): fix typo in i18n

- packages/neuron-wallet/electron-builder.yml
set "createDesktopShortcut" always and set "createStartMenuShortcut" true.
> build(neuron-wallet): add configuration of NSIS package

- packages/neuron-ui/src/contexts/NeuronWallet/chain.ts
As per:
* https://github.com/nervosnetwork/neuron/pull/547
* https://github.com/nervosnetwork/neuron/pull/548
> chore: Update tx status values

- packages/neuron-ui/package.json
- packages/neuron-ui/src/components/GeneralSetting/index.tsx
- yarn.lock
> Add office ui fabric react

- packages/neuron-wallet/src/database/chain/entities/transaction.ts
- packages/neuron-wallet/src/database/chain/migrations/1562038960990-AddStatusToTx.ts
- packages/neuron-wallet/src/database/chain/ormconfig.ts
- packages/neuron-wallet/src/services/transactions.ts
- packages/neuron-wallet/src/types/cell-types.ts
1. add `status` to transaction entity
2. update `status` when after add column
3. set status when create transaction
4. update status when sent tx find in chain
> Add status to tx

- packages/neuron-ui/src/containers/Navbar/index.tsx
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/styles/layout.scss
> chore(ui): Tab style for top navbar

- azure-pipelines.yml
- packages/neuron-wallet/electron-builder.yml
Auto packaging on tag/release.
> Azure Pipelines Package Job

- packages/neuron-ui/src/components/GeneralSetting/index.tsx
- packages/neuron-ui/src/containers/Main/hooks.ts
- packages/neuron-ui/src/containers/Navbar/index.tsx
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/states/initStates/settings.ts
- packages/neuron-ui/src/states/stateProvider/actionCreators/index.ts
- packages/neuron-ui/src/states/stateProvider/actionCreators/settings.ts
- packages/neuron-ui/src/utils/localCache.ts
- hide the address book tab even it's the current view
- cache the visibility of the address book tab locally
- add the address book tab toggle in the general settings view
- remove the settings tab from the navbar
> Hide address book tab

- packages/neuron-ui/src/components/Addresses/index.tsx
- packages/neuron-ui/src/components/LaunchScreen/index.tsx
- packages/neuron-ui/src/components/Overview/index.tsx
- packages/neuron-ui/src/components/Settings/index.tsx
- packages/neuron-ui/src/containers/Main/hooks.ts
- packages/neuron-ui/src/containers/Main/index.tsx
- packages/neuron-ui/src/containers/Navbar/index.tsx
- packages/neuron-ui/src/utils/const.ts
- packages/neuron-wallet/src/services/wallets.ts
- packages/neuron-wallet/tests/services/wallets.test.ts
rename General View to Overview View and navigate to it after wallet creation
> feat: set new created wallet as the current one

- packages/neuron-ui/src/components/WalletWizard/index.tsx
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh.json
> feat: Update welcome wizard screen layout

- packages/neuron-ui/src/containers/Main/hooks.ts
- packages/neuron-wallet/src/models/subjects/tx-db-changed-subject.ts
- packages/neuron-wallet/src/models/window-manager.ts
The message lacks fields of `type` and `value`, please implement them @classicalliu 😊
> feat(neuron-wallet): send transaction updated messages to neuron-ui

- packages/neuron-ui/src/components/Overview/index.tsx
- packages/neuron-ui/src/containers/Navbar/index.tsx
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh.json
use fabric ui to display property list
> refactor(neuron-ui): add style on the overview view

- packages/neuron-ui/src/components/TransactionList/index.tsx
- packages/neuron-ui/src/containers/Main/hooks.ts
- packages/neuron-ui/src/states/stateProvider/reducer.ts
and insert coming transaction when the list is empty and the pageNo is 1
> refactor(neuron-ui): use createdAt timestamp when tx.timestamp is null

- packages/neuron-ui/src/components/Addresses/index.tsx
- packages/neuron-ui/src/components/TransactionList/index.tsx
1. set description bordered when it is focused;
2. align cells to the middle vertically;
> refactor(neuron-ui): beautify tables

- packages/neuron-ui/src/components/Addresses/index.tsx
- packages/neuron-ui/src/components/History/index.tsx
- packages/neuron-ui/src/containers/Footer/index.tsx
- packages/neuron-ui/src/index.tsx
DetailsList and other compoments use this size thus would render larger.
> Override Fabric theme and misc styling updates

- .travis.yml
- README.md
- azure-pipelines.yml
- package.json
To align with Electron 5 which uses 12.
> chore(deps): Drop node 11 support

- azure-pipelines.yml
- packages/neuron-wallet/.eslintignore
- packages/neuron-wallet/assets/entitlements.plist
- packages/neuron-wallet/electron-builder.yml
- packages/neuron-wallet/package.json
- packages/neuron-wallet/scripts/notarize.js
- yarn.lock
Sign and notarize macOS binary.
> macOS app packaging notarizing

- packages/neuron-ui/src/containers/Main/hooks.ts
- packages/neuron-ui/src/states/initStates/chain.ts
- packages/neuron-ui/src/states/initStates/settings.ts
- packages/neuron-ui/src/states/initStates/wallet.ts
- packages/neuron-ui/src/utils/localCache.ts
load cached status on initialization
> feat(neuron-ui): cache app status

- packages/neuron-ui/src/components/Addresses/index.tsx
- packages/neuron-ui/src/components/Overview/index.tsx
- packages/neuron-ui/src/components/Send/index.tsx
- packages/neuron-ui/src/components/TransactionList/index.tsx
- packages/neuron-ui/src/utils/formatters.test.ts
- packages/neuron-ui/src/utils/formatters.ts
1. display tx.value in `CKB`
2. add wrap in the overview view
3. add style to handle overflow in lists
> Adjust style for minimal views

- packages/neuron-ui/src/components/Addresses/index.tsx
- packages/neuron-ui/src/components/Overview/index.tsx
- packages/neuron-ui/src/components/Receive/index.tsx
- packages/neuron-ui/src/components/Send/index.tsx
- packages/neuron-ui/src/components/TransactionList/index.tsx
- packages/neuron-ui/src/containers/Main/hooks.ts
- packages/neuron-ui/src/containers/Main/index.tsx
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/services/UILayer.ts
- packages/neuron-ui/src/utils/const.ts
- packages/neuron-ui/src/utils/formatters.test.ts
- packages/neuron-ui/src/utils/formatters.ts
- packages/neuron-wallet/src/database/chain/entities/transaction.ts
- packages/neuron-wallet/src/models/subjects/tx-db-changed-subject.ts
- packages/neuron-wallet/src/startup/sync-block-task/create.ts
- packages/neuron-wallet/tests/services/networks.test.ts
* Use full horizontal space
* Change receiving address description
* Update button titles
Note: our SVG rendering with canvg looks very fuzzy. Not know how to make QR code shape yet.
> Polish Receive View

- packages/neuron-ui/src/containers/Main/hooks.ts
- packages/neuron-wallet/src/models/subjects/data-update.ts
- packages/neuron-wallet/src/models/subjects/tx-db-changed-subject.ts
1. add debounce time on messages of updating transactions;
2. add an optional parameter for wallet id in the data update message;
> feat: optimize the flow of data updating

- packages/neuron-wallet/src/env.ts
- packages/neuron-wallet/src/services/sync/block-listener.ts
- packages/neuron-wallet/src/services/sync/get-blocks.ts
- packages/neuron-wallet/src/startup/sync-block-task/create.ts
- packages/neuron-wallet/src/startup/sync-block-task/task.ts
1. if sync background window closed, will unsubscribe subscriptions and open a new window
2. if kill the renderer process, will not unsubscribe or reopen one
> feat: unsubscribe when sync window close and reopen one when closed

- packages/neuron-ui/src/components/History/hooks.ts
- packages/neuron-ui/src/components/History/index.tsx
Neuron-wallet should handle the sequence of search result.
> feat(neuron-ui): remove history matching from neuron-ui

- packages/neuron-ui/src/components/Settings/index.tsx
> feat: Smaller Settings title with more spacing between

- packages/neuron-ui/src/components/Overview/index.tsx
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh.json
the copy pubkey hash button and mention lock arg on that button
> feat: Apply a bit style for miner info; add copy icon to

- packages/neuron-ui/src/components/History/index.tsx
- packages/neuron-ui/src/components/TransactionList/index.tsx
add clear icon in search box and expand icon in transaction list
> feat(neuron-ui): register necessary icons

- packages/neuron-wallet/scripts/notarize.js
is not provided via ENV variables
> feat: Do not even try notarizing app if apple id and password

- packages/neuron-ui/src/containers/Main/hooks.ts
- packages/neuron-ui/src/containers/Main/index.tsx
- packages/neuron-ui/src/services/subjects.ts
- packages/neuron-ui/src/types/Subject/index.d.ts
- packages/neuron-ui/src/utils/const.ts
- packages/neuron-wallet/src/models/subjects/data-update.ts
- packages/neuron-wallet/src/models/window-manager.ts
subscribe messages from neuron-wallet in neuron-ui by the `remote` module
> feat(neuron-ui): subscribe data update messages in neuron-ui

- azure-pipelines.yml
- lerna.json
- package.json
- packages/neuron-ui/package.json
- packages/neuron-ui/src/components/PasswordRequest/index.tsx
- packages/neuron-ui/src/components/Send/index.tsx
- packages/neuron-ui/src/components/TransactionFeePanel/index.tsx
- packages/neuron-ui/src/states/initStates/app.ts
- packages/neuron-ui/src/states/stateProvider/actionCreators/send.ts
- packages/neuron-ui/src/stories/TransactionFeePanel.stories.tsx
- packages/neuron-ui/src/types/App/index.d.ts
- packages/neuron-ui/src/utils/formatters.ts
- packages/neuron-ui/src/utils/initializeApp.ts
- packages/neuron-wallet/package.json
- packages/neuron-wallet/scripts/notarize.js
- packages/neuron-wallet/src/main.ts
- yarn.lock
As of this release Neuron will track CKB's stable version.
> [ᚬmaster] Release v0.16.0 alpha.0

- packages/neuron-ui/src/components/History/index.tsx
- packages/neuron-ui/src/components/Overview/index.tsx
- packages/neuron-ui/src/components/Receive/index.tsx
- packages/neuron-ui/src/components/Send/index.tsx
- packages/neuron-ui/src/components/Settings/index.tsx
- packages/neuron-ui/src/components/TransactionFeePanel/index.tsx
- packages/neuron-ui/src/components/TransactionList/index.tsx
- packages/neuron-ui/src/components/WalletWizard/index.tsx
- packages/neuron-ui/src/containers/Footer/index.tsx
- packages/neuron-ui/src/containers/Notification/index.tsx
- packages/neuron-ui/src/index.tsx
- packages/neuron-ui/src/widgets/QRScanner/index.tsx
and import icons by `IconButton` and `Icon` instead of `grommet-icons`
> refactor(neuron-ui): register icons at the entry of neuron-ui

- packages/neuron-ui/src/components/Addresses/index.tsx
- packages/neuron-ui/src/components/History/index.tsx
- packages/neuron-ui/src/components/TransactionList/index.tsx
- packages/neuron-ui/src/index.tsx
- packages/neuron-ui/src/states/initStates/app.ts
- packages/neuron-ui/src/states/stateProvider/actionCreators/transactions.ts
- packages/neuron-ui/src/states/stateProvider/actionCreators/wallets.ts
- packages/neuron-ui/src/stories/TransactionList.stories.tsx
- packages/neuron-ui/src/styles/index.scss
- packages/neuron-ui/src/types/App/index.d.ts
- packages/neuron-ui/src/utils/hooks.ts
1. reduce diff between origin descriptions and local description
2. add updating state in the description field
> feat(neuron-ui): optimize updating descriptions

- packages/neuron-wallet/src/listeners/address.ts
- packages/neuron-wallet/src/main.ts
- packages/neuron-wallet/src/startup/sync-block-task/task.ts
update address will block main process now
> fix: move update address to sync process and buffer it

- packages/neuron-ui/src/containers/Main/hooks.ts
These error messages will not be displayed in the notification.
> feat(neuron-ui): ignore connection error in neuron-ui

- packages/neuron-ui/src/containers/Main/hooks.ts
- packages/neuron-ui/src/states/stateProvider/actionCreators/app.ts
and add the handler in the callback of init function
> feat: remove empty current wallet handler from the main view

- packages/neuron-wallet/src/locales/en.ts
- packages/neuron-wallet/src/locales/zh.ts
- packages/neuron-wallet/src/utils/application-menu.ts
Customize for macOS/Windows to be more platform friendly.
> feat: Rearrange main menu

- packages/neuron-wallet/dev-app-update.yml
- packages/neuron-wallet/src/controllers/app/index.ts
- packages/neuron-wallet/src/controllers/update.ts
- packages/neuron-wallet/src/locales/en.ts
- packages/neuron-wallet/src/locales/zh.ts
- packages/neuron-wallet/src/main.ts
- packages/neuron-wallet/src/models/subjects/wallets.ts
- packages/neuron-wallet/src/utils/application-menu.ts
Add menu item allowing user to check updates.
> feat: Check for updates

- packages/neuron-wallet/src/controllers/transactions.ts
set the default page no to 1, and the default page size to 15
> feat(neuron-wallet): add default parameters in getAllByKeywords method

- packages/neuron-ui/src/components/NetworkEditor/hooks.ts
- packages/neuron-ui/src/containers/Notification/index.tsx
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/states/initStates/app.ts
- packages/neuron-ui/src/states/stateProvider/actionCreators/app.ts
- packages/neuron-ui/src/states/stateProvider/reducer.ts
- packages/neuron-ui/src/types/App/index.d.ts
- packages/neuron-ui/src/utils/loadTheme.tsx
show all warnings and alerts in the notification panel
> feat(neuron-ui): add notification panel

- packages/neuron-wallet/src/controllers/update.ts
- packages/neuron-wallet/src/locales/en.ts
- packages/neuron-wallet/src/locales/zh.ts
Without that Linux doesn't show any button.
> feat: Add OK button to update message box

- packages/neuron-wallet/src/services/wallets.ts
Remove the obliteration of the `wallets.json`
> fix(neuron-wallet): fix the error comes with deleting all wallets

- packages/neuron-ui/src/components/WalletWizard/index.tsx
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/utils/loadTheme.tsx
- packages/neuron-ui/src/utils/validators.ts
> feat(neuron-ui): add dynamic prmopt in wallet wizard

- packages/neuron-ui/src/components/History/hooks.ts
- packages/neuron-ui/src/states/stateProvider/actionCreators/transactions.ts
- packages/neuron-ui/src/states/stateProvider/actionCreators/wallets.ts
- packages/neuron-ui/src/states/stateProvider/reducer.ts
Update the local description as soon as the remote module returns
> feat(neuron-ui): make description update fluently

- packages/neuron-wallet/src/controllers/app/index.ts
- packages/neuron-wallet/src/controllers/update.ts
Remove static functions in favor of class instance functions. In the near future we'll refactor other controllers as well.
> refactor: Create and use update controller instance

- packages/neuron-ui/src/components/GeneralSetting/index.tsx
- packages/neuron-ui/src/components/NetworkEditor/index.tsx
- packages/neuron-ui/src/components/Overview/index.tsx
- packages/neuron-ui/src/components/Send/index.tsx
- packages/neuron-ui/src/components/WalletEditor/index.tsx
- packages/neuron-ui/src/components/WalletWizard/index.tsx
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/utils/const.ts
- packages/neuron-ui/src/utils/loadTheme.tsx
- packages/neuron-ui/src/widgets/PropertyList/index.tsx
- packages/neuron-ui/src/widgets/QRScanner/index.tsx
> Minor ui adjustments

- packages/neuron-wallet/package.json
- yarn.lock
Note we do NOT have explict rule for this.
Reference: https://github.com/nervosnetwork/neuron/pull/817#discussion_r310425212
> chore(deps): Use extact version for deps

- CHANGELOG.md
- lerna.json
- package.json
- packages/neuron-ui/package.json
- packages/neuron-wallet/package.json
> [ᚬmaster] Rc/v0.17.0 alpha.8

- packages/neuron-ui/src/components/Overview/index.tsx
- packages/neuron-ui/src/styles/index.scss
> feat(neuron-ui): disable overflow hidden on activities

- packages/neuron-ui/src/components/Addresses/index.tsx
- packages/neuron-ui/src/components/Transaction/index.tsx
- packages/neuron-ui/src/components/TransactionList/index.tsx
1. enlarge the max width of the address field to 500
2. limit the capacity(amount, value) field to [200, 250]
> feat(neuron-ui): adjust the layout of list

- packages/neuron-wallet/src/main.ts
- packages/neuron-wallet/src/utils/application-menu.ts
- packages/neuron-wallet/src/utils/i18n.ts
1. the app.getLocale method should be called after app.ready.
2. generate the application menu template dynamically on updating so it always has the latest status.
> fix(neuron-wallet): set the language on app ready

- packages/neuron-wallet/src/controllers/update.ts
- packages/neuron-wallet/src/locales/en.ts
- packages/neuron-wallet/src/locales/zh.ts
This allows user to know what they're upgrading to.
> feat: Show available update's version

- packages/neuron-ui/src/components/ImportKeystore/index.tsx
- packages/neuron-ui/src/components/WalletSetting/index.tsx
- packages/neuron-ui/src/components/WalletWizard/index.tsx
- packages/neuron-ui/src/containers/Main/hooks.ts
- packages/neuron-ui/src/containers/Main/index.tsx
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/services/remote/index.ts
- packages/neuron-ui/src/services/remote/wallets.ts
- packages/neuron-ui/src/states/stateProvider/actionCreators/wallets.ts
- packages/neuron-ui/src/theme.tsx
- packages/neuron-ui/src/types/Controller/index.d.ts
- packages/neuron-ui/src/utils/const.ts
- packages/neuron-wallet/src/controllers/app/index.ts
- packages/neuron-wallet/src/controllers/app/options.ts
- packages/neuron-wallet/src/controllers/wallets/index.ts
- packages/neuron-wallet/src/exceptions/wallet.ts
- packages/neuron-wallet/src/locales/en.ts
- packages/neuron-wallet/src/locales/zh.ts
- packages/neuron-wallet/src/models/keys/keystore.ts
- packages/neuron-wallet/src/utils/application-menu.ts
> feat(neuron-ui): add import keystore

- packages/neuron-wallet/src/controllers/wallets/index.ts
- packages/neuron-wallet/src/exceptions/common.ts
- packages/neuron-wallet/src/locales/en.ts
- packages/neuron-wallet/src/locales/zh.ts
Check the JSON format before the Keystore validation
> feat(neuron-ui): check the JSON format before keystore validation

- packages/neuron-ui/src/components/Addresses/index.tsx
- packages/neuron-ui/src/components/History/index.tsx
memorize the lists of transactions and addresses.
> feat(neuron-ui): memorize lists for performance

- packages/neuron-wallet/src/controllers/app/index.ts
- packages/neuron-wallet/src/controllers/app/options.ts
- packages/neuron-wallet/src/locales/en.ts
- packages/neuron-wallet/src/locales/zh.ts
- packages/neuron-wallet/src/utils/application-menu.ts
- packages/neuron-wallet/src/utils/const.ts
Also move external URLs out to put them to `utils/const`.
> feat: Add report issue menu item

- packages/neuron-ui/src/components/Send/hooks.ts
- packages/neuron-ui/src/components/Send/index.tsx
- packages/neuron-ui/src/components/TransactionFeePanel/index.tsx
- packages/neuron-ui/src/services/remote/wallets.ts
- packages/neuron-ui/src/states/stateProvider/actionCreators/app.ts
- packages/neuron-ui/src/states/stateProvider/actionCreators/wallets.ts
- packages/neuron-ui/src/states/stateProvider/reducer.ts
- packages/neuron-ui/src/tests/formatters.test.ts
- packages/neuron-ui/src/types/Controller/index.d.ts
- packages/neuron-ui/src/utils/addressesToBalance.ts
- packages/neuron-ui/src/utils/formatters.ts
- packages/neuron-wallet/src/controllers/wallets/index.ts
@classicalliu please implement the `calculateCycles` method in the wallet controller
> feat(neuron-ui): update the cycles on the outputs changing

- packages/neuron-ui/src/components/Send/hooks.ts
- packages/neuron-ui/src/containers/Notification/index.tsx
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/types/App/index.d.ts
- packages/neuron-ui/src/utils/const.ts
- packages/neuron-ui/src/utils/validators.ts
Use SDK to verify the addresses in the `verifyAddress` method.
> refactor(neuron-ui): verify the addresses before submission

- packages/neuron-ui/src/components/Send/hooks.ts
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/utils/const.ts
disable the amount to be updated if the value is not a number or has more than 8 digits decimal
> feat(neuron-ui): add verification on updating amounts

- packages/neuron-ui/src/components/Overview/index.tsx
1. extract unnecessary callback hooks outside the component
2. memoize event handlers in a memo hook
> refactor(neuron-ui): refactor the Overview View

- packages/neuron-ui/src/components/Overview/index.tsx
- packages/neuron-ui/src/components/WalletSetting/index.tsx
- packages/neuron-ui/src/theme.tsx
- packages/neuron-ui/src/types/App/index.d.ts
- packages/neuron-wallet/src/controllers/app/index.ts
- packages/neuron-wallet/src/controllers/wallets/index.ts
- packages/neuron-wallet/tests-e2e/tests/wallet.ts
> feat(neuron-ui): move the miner info from overview to wallet list

- packages/neuron-ui/src/containers/Navbar/index.tsx
- packages/neuron-ui/src/theme.tsx
> feat(neuron-ui): add a settings icon in the navbar component

- packages/neuron-ui/src/containers/Notification/index.tsx
replace the variable `notification` with `n` which is defined in the map loop.
> fix(neuron-ui): fix the repetition of notification

- packages/neuron-wallet/tests-e2e/main.test.ts
- packages/neuron-wallet/tests-e2e/tests/addressBook.ts
- packages/neuron-wallet/tests-e2e/tests/index.ts
This PR only include the basic tests of functionality
More tests related to UI should be added in the future
- input.isDisabled
- other fields
> test(neuron-ui): add tests of address book

- packages/neuron-ui/src/containers/Navbar/index.tsx
> refactor(neuron-ui): align the settings icon to inset of the main layout

- packages/neuron-ui/src/components/Addresses/index.tsx
- packages/neuron-ui/src/components/Send/hooks.ts
- packages/neuron-ui/src/components/Send/index.tsx
- packages/neuron-ui/src/components/TransactionList/index.tsx
- packages/neuron-ui/src/components/WalletWizard/index.tsx
- packages/neuron-ui/src/utils/hooks.ts
- packages/neuron-ui/src/widgets/QRScanner/index.tsx
1. use data-* as the item identifier
2. align the QR scanner video to the center of the dialog
> Optimize list with target property

- packages/neuron-wallet/src/controllers/app/index.ts
- packages/neuron-wallet/src/controllers/networks/index.ts
- packages/neuron-wallet/src/controllers/transactions.ts
- packages/neuron-wallet/src/controllers/wallets/index.ts
- packages/neuron-wallet/src/decorators/controller.ts
- packages/neuron-wallet/src/decorators/index.ts
- packages/neuron-wallet/src/utils/const.ts
the controller decorator is used to bind router to controllers and not used any more.
> refactor(neuron-wallet): remove unused decorator

- packages/neuron-ui/src/services/remote/controllerMethodWrapper.ts
- packages/neuron-ui/src/services/remote/index.ts
- packages/neuron-ui/src/services/subjects.ts
The electron app is required explicitly
> feat(neuron-ui): make the alert of lacking remote module more clear

- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh.json
1. capitalize Cells, Data, TypeScript
2. use plural of Cell
> fix(neuron-ui): fix the label of skip-data toggle

- packages/neuron-ui/src/widgets/QRCode/index.tsx
- packages/neuron-wallet/src/controllers/wallets/index.ts
* QR image file: replace `Receive.png` with `ckb-address.png`.
* Keystore file: use `[wallet name].json` instead of `[wallet name]`.
> Friendly output name

- packages/neuron-wallet/tests-e2e/application/index.ts
- packages/neuron-wallet/tests-e2e/operations/searchWalletIndex.ts
- packages/neuron-wallet/tests-e2e/tests/generalSettings.ts
- packages/neuron-wallet/tests-e2e/tests/network.ts
- packages/neuron-wallet/tests-e2e/tests/notification.ts
- packages/neuron-wallet/tests-e2e/tests/wallet.ts
> test(e2e): refactor goto setting page from menu based on os platform

- packages/neuron-ui/src/services/remote/app.ts
- packages/neuron-wallet/src/controllers/api.ts
- packages/neuron-wallet/src/controllers/app/index.ts
- packages/neuron-wallet/src/controllers/app/menu.ts
- packages/neuron-wallet/src/controllers/app/show-window.ts
- packages/neuron-wallet/src/controllers/index.ts
- packages/neuron-wallet/src/controllers/networks.ts
- packages/neuron-wallet/src/controllers/transactions.ts
- packages/neuron-wallet/src/controllers/wallets.ts
- packages/neuron-wallet/src/locales/en.ts
- packages/neuron-wallet/src/locales/zh.ts
- packages/neuron-wallet/src/main.ts
- packages/neuron-wallet/src/services/wallets.ts
- packages/neuron-wallet/tests-e2e/application/index.ts
- packages/neuron-wallet/tests-e2e/application/preload.js
- packages/neuron-wallet/tests-e2e/tests/wallet.ts
* Add a new `ApiController` which replaces `AppController`
* neuron-ui talks to remote/api instead of remote/app
* AppController is used as instance, not static functions object
* Detach menu from app controller
* Remove controller and UI action dependency from services
> Api controller

- packages/neuron-ui/src/services/remote/apiMethodWrapper.ts
- packages/neuron-ui/src/services/remote/app.ts
- packages/neuron-ui/src/services/remote/index.ts
- packages/neuron-ui/src/services/remote/networks.ts
- packages/neuron-ui/src/services/remote/skipDataAndType.ts
- packages/neuron-ui/src/services/remote/transactions.ts
- packages/neuron-ui/src/services/remote/wallets.ts
- packages/neuron-wallet/src/controllers/api.ts
- packages/neuron-wallet/src/controllers/networks.ts
- packages/neuron-wallet/src/controllers/transactions.ts
- packages/neuron-wallet/src/controllers/wallets.ts
Neuron UI should require this api controller only.
> feat: Expose a flat API controller from neuron wallet to UI layer

- packages/neuron-ui/src/components/CustomRows/ActivityRow.tsx
- packages/neuron-ui/src/components/CustomRows/activityRow.module.scss
- packages/neuron-ui/src/components/Overview/index.tsx
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh.json
Before this PR:
After this PR:
> update the style of recent activities

- packages/neuron-ui/src/components/CustomRows/activityRow.module.scss
Make the activity row's shadow and status icon softer.
> Smaller activity status info

- packages/neuron-ui/package.json
- packages/neuron-ui/src/components/Addresses/index.tsx
- packages/neuron-ui/src/components/Transaction/index.tsx
- packages/neuron-wallet/package.json
- packages/neuron-wallet/src/controllers/api.ts
- packages/neuron-wallet/src/controllers/app/menu.ts
- packages/neuron-wallet/src/controllers/wallets.ts
- packages/neuron-wallet/src/models/keys/address.ts
- packages/neuron-wallet/src/models/lock-utils.ts
- packages/neuron-wallet/src/services/cells.ts
- packages/neuron-wallet/src/services/tx/transaction-generator.ts
- packages/neuron-wallet/src/services/wallets.ts
- packages/neuron-wallet/tests/services/cells.test.ts
- packages/neuron-wallet/tests/services/tx/transaction-generator.test.ts
- yarn.lock
1. bump SDK to v0.23.0
2. split `sendCapacity` to `sendTx` and `generateTx`
3. add `calculateFee`
4. support generate transaction with `feeRate`
5. set default fee rate to 1000 if fee not set in wallets controller `sendCapacity`
> chore: bump sdk to v0.23.0

- packages/neuron-wallet/src/services/indexer/queue.ts
> fix: break => continue

- packages/neuron-wallet/src/database/chain/entities/transaction.ts
- packages/neuron-wallet/src/database/chain/migrations/1572006450765-AddIndices.ts
- packages/neuron-wallet/src/database/chain/migrations/1572137226866-AddIndexToTxTimestamp.ts
- packages/neuron-wallet/src/database/chain/migrations/1572226722928-AddOutputIndex.ts
- packages/neuron-wallet/src/database/chain/ormconfig.ts
- packages/neuron-wallet/src/services/cells.ts
- packages/neuron-wallet/src/services/indexer/queue.ts
- packages/neuron-wallet/src/services/tx/indexer-transaction.ts
- packages/neuron-wallet/src/services/tx/transaction-persistor.ts
- packages/neuron-wallet/src/services/tx/transaction-service.ts
Mainly for query/insert under `Indexer` module.
> DB query & import logic tweak

- packages/neuron-ui/src/components/TransactionList/index.tsx
> fix(neuron-ui): hide the pending list if it has no items.

- packages/neuron-wallet/package.json
- yarn.lock
> chore: Update electron-builder to 22.1.0

- CHANGELOG.md
- lerna.json
- package.json
- packages/neuron-ui/package.json
- packages/neuron-wallet/package.json
- scripts/release-checksums.rb
- yarn.lock
* Create a ruby script to download a release binaries ([acfa6e9](https://github.com/nervosnetwork/neuron/commit/acfa6e9))
* Use system curl and sha256sum commands to digest binaries ([0fa0dd8](https://github.com/nervosnetwork/neuron/commit/0fa0dd8))
> [ᚬmaster] Rc/v0.24.1

- packages/neuron-wallet/src/services/tx/transaction-service.ts
Those queries are loading too much data and causing sqlite error.
For now simply remove search by amount feature.
> feat: Disable search history by amount

- packages/neuron-ui/src/components/ImportKeystore/index.tsx
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh.json
> feat(neuron-ui): remove input truncation on importing keystore.

- packages/neuron-ui/src/components/Addresses/index.tsx
- packages/neuron-ui/src/components/Transaction/index.tsx
- packages/neuron-ui/src/utils/const.ts
- packages/neuron-wallet/src/models/chain-info.ts
> feat: update the address prefix and the explorer url according to the chain type

- packages/neuron-ui/src/components/CustomRows/DAORecordRow.tsx
- packages/neuron-ui/src/components/NervosDAO/index.tsx
> Fix free and lock value

- packages/neuron-ui/src/components/ImportKeystore/index.tsx
- packages/neuron-ui/src/components/NetworkEditor/hooks.ts
Before this PR:
After this PR:
> feat(neuron-ui): remove redundant error messages

- packages/neuron-ui/src/components/NervosDAO/index.tsx
- packages/neuron-ui/src/containers/Main/hooks.ts
- packages/neuron-ui/src/states/initStates/app.ts
- packages/neuron-ui/src/tests/calculation/calculateGlobalAPY/fixtures.ts
- packages/neuron-ui/src/tests/calculation/calculateGlobalAPY/index.test.ts
- packages/neuron-ui/src/types/App/index.d.ts
- packages/neuron-ui/src/utils/calculateGlobalAPY.ts
> feat(neuron-ui): add global apy estimation

- packages/neuron-ui/src/tests/calculation/calculateGlobalAPY/fixtures.ts
- packages/neuron-ui/src/utils/calculateAPY.ts
- packages/neuron-ui/src/utils/calculateGlobalAPY.ts
> refactor(neuron-ui): improve precision of calculateAPY

- packages/neuron-ui/src/components/NervosDAO/index.tsx
> fix(neuron-ui): fix the missing field in error message.

- packages/neuron-ui/src/components/CustomRows/DAORecordRow.tsx
- packages/neuron-ui/src/types/App/index.d.ts
Please add the field in this branch
> fix(neuron): use deposit timestamp to calculate phase2 dao cell apc

- packages/neuron-ui/src/containers/Notification/Notification.module.scss
- packages/neuron-ui/src/containers/Notification/index.tsx
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/utils/const.ts
> feat(neuron-ui): add a guide link to run a ckb mainnet node.

- packages/neuron-ui/src/containers/Footer/index.tsx
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh.json
> feat(neuron-ui): add hint for synchronization not started.

- packages/neuron-ui/src/styles/index.scss
> feat(neuron-ui): update the pagination style

- packages/neuron-wallet/src/models/subjects/network-switch-subject.ts
- packages/neuron-wallet/src/services/networks.ts
- packages/neuron-wallet/src/startup/sync-block-task/create.ts
- packages/neuron-wallet/src/startup/sync-block-task/params.ts
Reduce about `1100 ~ 1200` `TIME_WAIT` connections to about `20 ~ 30`
> fix: initialize NetworksService in renderer process

- packages/neuron-ui/src/components/NervosDAO/index.tsx
> fix(neuron-ui): show 0 if withdraw rpc returns errors

- packages/neuron-wallet/src/database/address/address-dao.ts
- packages/neuron-wallet/src/services/addresses.ts
- packages/neuron-wallet/src/services/wallets.ts
1. fix the problem that balance will updated in mainnet address when send transaction
2. refactor the `updateTxCountAndBalance` to `updateTxCountAndBalances` to reduce the addresses read and write
> Fix balance after send

- packages/neuron-ui/package.json
- packages/neuron-ui/src/components/GeneralSetting/index.tsx
- packages/neuron-ui/src/components/GeneralSetting/style.module.scss
- packages/neuron-ui/src/containers/Main/hooks.ts
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/services/remote/app.ts
- packages/neuron-ui/src/services/remote/index.ts
- packages/neuron-ui/src/services/remote/updater.ts
- packages/neuron-ui/src/services/subjects.ts
- packages/neuron-ui/src/states/initStates/index.ts
- packages/neuron-ui/src/states/initStates/updater.ts
- packages/neuron-ui/src/states/stateProvider/reducer.ts
- packages/neuron-ui/src/types/App/index.d.ts
- packages/neuron-ui/src/types/Subject/index.d.ts
- packages/neuron-wallet/src/controllers/api.ts
- packages/neuron-wallet/src/controllers/app/menu.ts
- packages/neuron-wallet/src/controllers/app/subscribe.ts
- packages/neuron-wallet/src/controllers/update.ts
- packages/neuron-wallet/src/locales/en.ts
- packages/neuron-wallet/src/locales/zh.ts
- packages/neuron-wallet/src/models/subjects/app-updater.ts
- yarn.lock
Note: some API calls form the settings view component are plain functions. Not sure if it's really necessary to wrap them inside `useCallback`.
> Ui for update

- packages/neuron-ui/src/utils/const.ts
the rfc number has been updated to 0023
https://github.com/nervosnetwork/rfcs/commit/05ed67992508f234050139c0573db2ef011e8803
> feat(neuron-ui): update the url to nervos dao rfc

- packages/neuron-ui/src/components/GeneralSetting/index.tsx
- packages/neuron-ui/src/components/NetworkSetting/index.tsx
- packages/neuron-ui/src/components/WalletSetting/index.tsx
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh.json
Primary buttons have too strong visual weight. (And showing multiple primary buttons on a single view is kind of bad design)
> Settings buttons style

- packages/neuron-ui/src/components/NervosDAO/DepositDialog.tsx
- packages/neuron-ui/src/components/NervosDAO/index.tsx
- packages/neuron-ui/src/services/remote/wallets.ts
- packages/neuron-ui/src/types/Controller/index.d.ts
- packages/neuron-ui/src/utils/formatters.ts
> feat: enable deposit all to nervos dao

- package.json
- packages/neuron-wallet/package.json
- yarn.lock
> Update typescript to 3.7, create-react-app to 3.3.0

- packages/neuron-ui/package.json
- yarn.lock
> Update react-scripts to 3.3.0

- packages/neuron-ui/package.json
- yarn.lock
> Update react-app-rewired to 2.1.5

- packages/neuron-ui/src/components/NervosDAO/index.tsx
Deposit should be prevented when no inputs available even the balance is not zero.
> [ᚬrc/v0.26.0] feat: Disable the deposit dialog if there're no inputs

- packages/neuron-ui/src/components/TransactionList/index.tsx
- packages/neuron-wallet/src/controllers/api.ts
- packages/neuron-wallet/src/controllers/app/show-window.ts
This fixes double clicking to show tx detail not working issue.
> Use showTransactionDetails from both content menu and double click

- packages/neuron-ui/src/components/CustomRows/DAORecordRow.tsx
- packages/neuron-ui/src/components/CustomRows/daoRecordRow.module.scss
- packages/neuron-ui/src/components/NervosDAO/EpochsDialog.tsx
- packages/neuron-ui/src/components/NervosDAO/WithdrawDialog.tsx
- packages/neuron-ui/src/components/NervosDAO/epochsDialog.module.scss
- packages/neuron-ui/src/components/NervosDAO/index.tsx
- packages/neuron-ui/src/components/Send/hooks.ts
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/services/chain.ts
- packages/neuron-ui/src/utils/hooks.ts
> feat: Add a dialog of explanation of epochs period

- packages/neuron-ui/src/components/CustomRows/DAORecordRow.tsx
- packages/neuron-ui/src/components/CustomRows/daoRecordRow.module.scss
> feat: Make the compensation period indicator smaller

- packages/neuron-ui/src/components/Receive/index.tsx
- packages/neuron-ui/src/components/Receive/receive.module.scss
- packages/neuron-ui/src/widgets/QRCode/index.tsx
- packages/neuron-ui/src/widgets/QRCode/qrcode.module.scss
> feat: Update the UI of receive view.

- packages/neuron-ui/src/components/NervosDAO/hooks.ts
1. remove comma on inputting deposit value
2. show error messages on inputting too much
> fix: Refine the process of inputting deposit value

- packages/neuron-wallet/src/controllers/api.ts
- packages/neuron-wallet/src/controllers/app/index.ts
- packages/neuron-wallet/src/controllers/networks/index.ts
- packages/neuron-wallet/src/main.ts
- packages/neuron-wallet/src/services/networks.ts
Whenever connecting to a new network or current one, it should update genesis info and chain type.
> Update current network info (chain, genesis hash) when connected

- packages/neuron-ui/src/components/Settings/index.tsx
Now that Settings has its tab on left side navbar
> Remove back button from settings view

- packages/neuron-ui/src/widgets/Button/button.module.scss
- packages/neuron-ui/src/widgets/Button/index.tsx
Remove the focus style and remove the box-shadow on buttons
> feat: Lighten the style of buttons

- packages/neuron-ui/src/components/Overview/index.tsx
- packages/neuron-ui/src/components/SyncStatus/index.tsx
- packages/neuron-ui/src/containers/Navbar/index.tsx
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/stories/SyncStatus.stories.tsx
- packages/neuron-ui/src/utils/const.ts
- packages/neuron-ui/src/widgets/PropertyList/index.tsx
> feat: Add a new status of syncing.

- packages/neuron-ui/src/components/Overview/index.tsx
- packages/neuron-ui/src/components/Overview/overview.module.scss
- packages/neuron-ui/src/widgets/PropertyList/PropertyList.module.scss
- packages/neuron-ui/src/widgets/PropertyList/index.tsx
> feat: make integer of balance more conspicuous

- packages/neuron-ui/src/styles/index.scss
- packages/neuron-ui/src/styles/layout.scss
> feat: Unify the style of scrollbar

- packages/neuron-wallet/src/block-sync-renderer/sync/block-number.ts
With a rough test/measurement, it makes scanning blocks speed up for 4x on win and 1.6x on mac.
> Only write current height to DB for every 1000 blocks

- packages/neuron-wallet/src/services/ckb-runner.ts
to enable all modules, from which the Indexer module is what we need
> Modify ckb.toml before spawning ckb process

- packages/neuron-ui/src/stories/Addresses.stories.tsx
- packages/neuron-ui/src/stories/History.stories.tsx
- packages/neuron-ui/src/stories/NervosDAO.stories.tsx
- packages/neuron-ui/src/stories/Overview.stories.tsx
- packages/neuron-ui/src/stories/PasswordRequest.stories.tsx
- packages/neuron-ui/src/stories/Receive.stories.tsx
This PR only changes the stories for a better DX.
> refactor: update stories by mocking contexts

- packages/neuron-ui/src/components/Send/send.module.scss
until the desktop capturerer is fixed.
> feat: hide the qr scanner

- packages/neuron-ui/src/styles/index.scss
> feat: re-align the pagination component

- packages/neuron-ui/src/components/Send/index.tsx
- packages/neuron-ui/src/components/Send/send.module.scss
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
> feat: show full address prompt

- packages/neuron-ui/src/components/Addresses/index.tsx
- packages/neuron-ui/src/components/NetworkSetting/index.tsx
- packages/neuron-ui/src/components/Receive/index.tsx
- packages/neuron-ui/src/components/Transaction/index.tsx
- packages/neuron-ui/src/components/TransactionList/index.tsx
- packages/neuron-ui/src/components/WalletSetting/index.tsx
- packages/neuron-ui/src/containers/Main/hooks.ts
- packages/neuron-ui/src/containers/Main/index.tsx
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/services/remote/index.ts
- packages/neuron-ui/src/styles/index.scss
- packages/neuron-ui/src/utils/hooks.ts
Enable copy/paste in the main container and keep navigation non-interactive
> feat: Enable text selection and copy/paste

- packages/neuron-ui/src/containers/Main/index.tsx
Fix a layout bug coming with recently added `div` block.
> fix: Fix the center-aligned layout of importing wallets

- packages/neuron-ui/package.json
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/stories/DatetimePicker.stories.tsx
- packages/neuron-ui/src/stories/index.tsx
- packages/neuron-ui/src/widgets/DatetimePicker/datetimePicker.module.scss
- packages/neuron-ui/src/widgets/DatetimePicker/index.tsx
- yarn.lock
> feat: Add the component of Datetime Picker

- packages/neuron-wallet/src/block-sync-renderer/index.ts
- packages/neuron-wallet/src/block-sync-renderer/sync/queue.ts
- packages/neuron-wallet/src/block-sync-renderer/sync/tx-address-finder.ts
- packages/neuron-wallet/src/block-sync-renderer/task.ts
- packages/neuron-wallet/src/controllers/api.ts
- packages/neuron-wallet/src/controllers/customized-assets.ts
- packages/neuron-wallet/src/controllers/single-multi-sign.ts
- packages/neuron-wallet/src/database/chain/entities/input.ts
- packages/neuron-wallet/src/database/chain/entities/output.ts
- packages/neuron-wallet/src/database/chain/migrations/1581405459272-AddMultiSignBlake160.ts
- packages/neuron-wallet/src/database/chain/ormconfig.ts
- packages/neuron-wallet/src/models/chain/input.ts
- packages/neuron-wallet/src/models/chain/output.ts
- packages/neuron-wallet/src/models/multi-sign-utils.ts
- packages/neuron-wallet/src/models/multi-sign.ts
- packages/neuron-wallet/src/models/transaction-size.ts
- packages/neuron-wallet/src/services/cells.ts
- packages/neuron-wallet/src/services/transaction-sender.ts
- packages/neuron-wallet/src/services/tx/transaction-generator.ts
- packages/neuron-wallet/src/services/tx/transaction-persistor.ts
- packages/neuron-wallet/src/types/controller.d.ts
- packages/neuron-wallet/tests/models/transaction-size.test.ts
- packages/neuron-wallet/tests/services/tx/transaction-generator.test.ts
- packages/neuron-wallet/tests/services/tx/transaction-sender.test.ts
1. sync single multi sign transactions
2. generate transaction with single multi sign inputs
3. sign transaction with single multi sign input and send
> Sync single multi sign transactions

- packages/neuron-ui/src/components/SignAndVerify/signAndVerify.module.scss
The layout is not fit for minimal window on Windows so the padding is removed and animation is adjusted in this PR.
> feat: remove padding and smooth animation for sign and verify component

- packages/neuron-wallet/src/services/tx/transaction-service.ts
- packages/neuron-wallet/tests/services/transactions.test.ts
Optimize transaction loading. Speed up overall performance especially for miner wallets which have huge amount of inputs/outputs.
> [ᚬrc/v0.28.1] Optimize tx list loading

- packages/neuron-ui/src/components/SpecialAsset/index.tsx
- packages/neuron-ui/src/components/SpecialAssetList/index.tsx
- packages/neuron-ui/src/stories/SpecialAsset.stories.tsx
Use the timestamp of local tip block instead of that of system to calculate the estimation time.
> fix: Fix the estimation of release time

- packages/neuron-ui/src/components/SpecialAsset/index.tsx
- packages/neuron-ui/src/components/SpecialAssetList/index.tsx
- packages/neuron-ui/src/stories/SpecialAsset.stories.tsx
- packages/neuron-wallet/tests/services/transactions.test.ts
Use the timestamp of local tip block instead of that of system to calculate the estimation time.
> [ᚬrc/v0.29.0] Fix estimated release time

- packages/neuron-ui/src/components/NetworkStatus/index.tsx
- packages/neuron-ui/src/components/NetworkStatus/networkStatus.module.scss
- packages/neuron-ui/src/components/SyncStatus/index.tsx
- packages/neuron-ui/src/containers/Navbar/index.tsx
- packages/neuron-ui/src/containers/Navbar/navbar.module.scss
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/stories/NetworkStatus.stories.tsx
- packages/neuron-ui/src/styles/index.scss
> feat: add a block number tooltip in the network status

- CHANGELOG.md
- lerna.json
- package.json
- packages/neuron-ui/package.json
- packages/neuron-wallet/package.json
- packages/neuron-wallet/src/controllers/transactions.ts
v0.29.0 official release (2020-03-31).
> [ᚬmaster] Rc/v0.29.0

- packages/neuron-wallet/src/controllers/update.ts
No easy way to say if this actually works. Apply it and observe several future versions to see the result.
> Wrap autoUpdater.quitAndInstall inside setImmediate

- packages/neuron-wallet/src/services/networks.ts
- packages/neuron-wallet/src/utils/common.ts
fetching its genesis block hash and chain info
> Set a timeout of 2 seconds when updating a network

- packages/neuron-ui/src/components/NervosDAO/index.tsx
1. set the value grey
2. set the locked value to '--'
> [ᚬrefactor-nervos-dao] feat: update the nervos dao info style for un-synced status

- packages/neuron-ui/src/components/NervosDAORecord/index.tsx
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/stories/NervosDAORecord.stories.tsx
- packages/neuron-ui/src/tests/getDAOCellStatus/fixtures.json
- packages/neuron-ui/src/utils/getDAOCellStatus.ts
1. update the messages of immature for next step
2. hide the message when the app is not online
> [ᚬrefactor-nervos-dao] feat: add immature for unlock stage

- packages/neuron-ui/src/styles/mixin.scss
Update the font for Chinese text
> [ᚬrefactor-nervos-dao] feat: set the font for chinese

- packages/neuron-ui/.storybook/preview-body.html
- packages/neuron-ui/src/containers/Navbar/index.tsx
- packages/neuron-ui/src/containers/Navbar/navbar.module.scss
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/stories/Navbar.stories.tsx
- packages/neuron-ui/src/stories/index.tsx
- packages/neuron-ui/src/stories/styles.scss
- packages/neuron-ui/src/widgets/Icons/Flask.svg
Separate the experimental items from the normal items.
> Adjust sidebar

- packages/neuron-ui/src/components/SUDTUpdateDialog/index.tsx
- packages/neuron-ui/src/components/SUDTUpdateDialog/sUDTUpdateDialog.module.scss
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/stories/SUDTUpdateDialog.stories.tsx
- packages/neuron-ui/src/stories/index.tsx
> [ᚬsUDT] feat: add the update account info dialog

- packages/neuron-ui/src/components/SUDTAccountList/index.tsx
- packages/neuron-ui/src/components/SUDTAccountList/sUDTAccountList.module.scss
- packages/neuron-ui/src/components/SUDTAccountPile/index.tsx
- packages/neuron-ui/src/components/SUDTCreateDialog/index.tsx
- packages/neuron-ui/src/components/SUDTReceive/index.tsx
- packages/neuron-ui/src/components/SUDTSend/index.tsx
- packages/neuron-ui/src/containers/Main/index.tsx
- packages/neuron-ui/src/containers/Navbar/index.tsx
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/stories/SUDTAccountPile.stories.tsx
- packages/neuron-ui/src/styles/index.scss
- packages/neuron-ui/src/utils/const.ts
- packages/neuron-wallet/src/block-sync-renderer/sync/queue.ts
Assemble the s-udt account list, s-udt send, s-udt receive components into the app.
> [ᚬsUDT] feat: assemble the sudt account list, send and receive

- packages/neuron-wallet/src/controllers/anyone-can-pay.ts
- packages/neuron-wallet/src/controllers/api.ts
- packages/neuron-wallet/src/controllers/asset-account.ts
- packages/neuron-wallet/src/models/asset-account-info.ts
- packages/neuron-wallet/src/services/asset-account-service.ts
1. add the api to get an asset account
2. add the api to get the anyone-can-pay script
> feat: add apis

- packages/neuron-ui/src/components/SUDTAccountList/sUDTAccountList.module.scss
- packages/neuron-ui/src/components/SUDTSend/sUDTSend.module.scss
- packages/neuron-ui/src/components/SUDTUpdateDialog/index.tsx
- packages/neuron-ui/src/components/Send/send.module.scss
- packages/neuron-ui/src/components/TransactionFeePanel/index.tsx
- packages/neuron-ui/src/components/WalletEditor/index.tsx
- packages/neuron-ui/src/styles/index.scss
simply adjust styles and remove some event listeners
> feat: slightly adjust the ui

- packages/neuron-ui/src/components/Send/send.module.scss
- packages/neuron-ui/src/widgets/Button/button.module.scss
adjust the height of buttons according to new height of text fields
> fix: fix the button height

- packages/neuron-ui/src/components/NervosDAORecord/index.tsx
keep the positive sign displayed when the dao record is completed
> feat: prepend the positive sign

- packages/neuron-ui/src/components/SUDTAccountList/index.tsx
- packages/neuron-ui/src/components/SUDTAccountList/sUDTAccountList.module.scss
- packages/neuron-ui/src/components/SUDTCreateDialog/index.tsx
- packages/neuron-ui/src/components/SUDTCreateDialog/sUDTCreateDialog.module.scss
- packages/neuron-ui/src/components/SUDTSend/index.tsx
- packages/neuron-ui/src/components/SUDTSend/sUDTSend.module.scss
- packages/neuron-ui/src/components/SpecialAssetList/index.tsx
- packages/neuron-ui/src/components/SpecialAssetList/specialAssetList.module.scss
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/styles/mixin.scss
- packages/neuron-ui/src/widgets/Button/button.module.scss
- packages/neuron-ui/src/widgets/ExperimentalRibbon/experimentalRibbon.module.scss
1. add experimental ribbon in the sudt pages
2. update i18n and slightly adjust ui
> Add experimental ribbon to components

- packages/neuron-ui/src/components/Addresses/addresses.module.scss
- packages/neuron-ui/src/components/Addresses/index.tsx
- packages/neuron-ui/src/components/Receive/index.tsx
- packages/neuron-ui/src/components/Receive/receive.module.scss
- packages/neuron-ui/src/containers/Navbar/index.tsx
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
1. remove addresses from the navbar
2. add address book button in receive
3. adjust receive and address book style
> feat: update receive and addresses

- packages/neuron-wallet/src/controllers/app/index.ts
- packages/neuron-wallet/src/controllers/networks/index.ts
- packages/neuron-wallet/src/env.ts
- packages/neuron-wallet/src/services/ckb-runner.ts
- packages/neuron-wallet/src/services/node.ts
- packages/neuron-wallet/src/utils/const.ts
Try to start the bundled CKB node when
1. network is specified
2. network address is the default one
3. fail to connect the external CKB node
> refactor: update the logic of starting bundled CKB node

- packages/neuron-ui/src/components/Addresses/index.tsx
- packages/neuron-ui/src/components/SignAndVerify/index.tsx
- packages/neuron-ui/src/components/Transaction/index.tsx
- packages/neuron-ui/src/components/TransactionFeePanel/index.tsx
- packages/neuron-ui/src/components/TransactionList/index.tsx
- packages/neuron-ui/src/components/WalletEditor/index.tsx
- packages/neuron-ui/src/styles/index.scss
- packages/neuron-ui/src/styles/layout.scss
- packages/neuron-ui/src/theme.tsx
1. remove unused font
2. adjust layout
3. adjust fabric dropdown style
> feat: slightly adjust ui

- packages/neuron-ui/src/components/SUDTSend/index.tsx
- packages/neuron-ui/src/types/Controller/index.d.ts
add assetAccountID in the params of generating sudt tx
> feat: adjust api

- packages/neuron-ui/src/components/TransactionFeePanel/index.tsx
- packages/neuron-ui/src/styles/index.scss
- packages/neuron-ui/src/theme.tsx
1. set the tx speed field to 12px
2. set the search bar to 12px
> fix: fix the font size

- packages/neuron-ui/src/components/ImportKeystore/index.tsx
- packages/neuron-ui/src/components/NervosDAO/hooks.ts
- packages/neuron-ui/src/components/PasswordRequest/index.tsx
- packages/neuron-ui/src/components/Send/send.module.scss
- packages/neuron-ui/src/components/SignAndVerify/index.tsx
- packages/neuron-ui/src/components/SpecialAssetList/index.tsx
- packages/neuron-ui/src/components/Transaction/index.tsx
- packages/neuron-ui/src/components/WalletEditor/hooks.ts
- packages/neuron-ui/src/components/WalletWizard/index.tsx
- packages/neuron-ui/src/containers/Main/hooks.ts
- packages/neuron-ui/src/exceptions/index.ts
- packages/neuron-ui/src/services/remote/remoteApiWrapper.ts
- packages/neuron-ui/src/states/initStates/app.ts
- packages/neuron-ui/src/states/stateProvider/actionCreators/app.ts
- packages/neuron-ui/src/states/stateProvider/actionCreators/transactions.ts
- packages/neuron-ui/src/states/stateProvider/actionCreators/wallets.ts
- packages/neuron-ui/src/states/stateProvider/reducer.ts
- packages/neuron-ui/src/stories/PasswordRequest.stories.tsx
- packages/neuron-ui/src/types/App/index.d.ts
- packages/neuron-ui/src/utils/const.ts
- packages/neuron-ui/src/utils/isSuccessResponse.ts
1. display the password error in the password dialog
2. refactor the action creator to remove component related logic outside
> feat: display password error in password dialog

- packages/neuron-ui/src/components/SUDTSend/index.tsx
Remove the useless convertion of total amount
> fix: fix the total amount on validating sudt tx

- packages/neuron-ui/src/containers/Main/hooks.ts
- packages/neuron-ui/src/utils/const.ts
The connection status will be connecting instead of a failure during the mixture of connection status from different URLs.
> feat: update connecting deadline on network switching

- packages/neuron-ui/src/components/SUDTCreateDialog/index.tsx
- packages/neuron-ui/src/components/SUDTUpdateDialog/index.tsx
- packages/neuron-ui/src/components/SUDTUpdateDialog/sUDTUpdateDialog.module.scss
1. scrollable token id
2. capitalized symbol
> feat: refine sudt dialog

- packages/neuron-ui/src/components/SUDTAccountList/sUDTAccountList.module.scss
- packages/neuron-ui/src/components/SUDTAccountPile/sUDTAccountPile.module.scss
Reduce the size of account piles for the layout in minimal window
> feat: adjust sudt accounts layout

- packages/neuron-ui/src/components/SUDTCreateDialog/index.tsx
- packages/neuron-ui/src/components/SUDTUpdateDialog/index.tsx
- packages/neuron-ui/src/exceptions/index.ts
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/utils/const.ts
- packages/neuron-ui/src/utils/hooks.ts
- packages/neuron-ui/src/utils/validators.ts
Add a custom hook to validate sUDT account info
> feat: add custom hook for validation

- packages/neuron-ui/src/components/SUDTAccountList/index.tsx
- packages/neuron-ui/src/components/SUDTCreateDialog/index.tsx
known token info will be filled automatically on creating s-udt accounts
> feat: auto fill token info if it's already known

- packages/neuron-ui/src/components/Addresses/addresses.module.scss
- packages/neuron-ui/src/components/Addresses/index.tsx
- packages/neuron-ui/src/components/Receive/index.tsx
- packages/neuron-ui/src/components/Receive/receive.module.scss
- packages/neuron-ui/src/components/Transaction/index.tsx
- packages/neuron-ui/src/components/Transaction/transaction.module.scss
- packages/neuron-ui/src/components/TransactionList/index.tsx
- packages/neuron-ui/src/components/TransactionList/transactionList.module.scss
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/widgets/CopyZone/copyZone.module.scss
- packages/neuron-ui/src/widgets/CopyZone/index.tsx
> Apply copy component

- packages/neuron-wallet/src/controllers/export-debug.ts
- packages/neuron-wallet/src/services/ckb-runner.ts
Include the last 32kB of run.log from the bundled CKB
> feat: export more logs for debug

- packages/neuron-ui/src/components/Overview/index.tsx
- packages/neuron-ui/src/components/TransactionList/index.tsx
- packages/neuron-ui/src/widgets/SUDTAvatar/index.tsx
1. display send/receive depending on the amount
2. hide amount if the token info is unknown
3. use default account name in the sudt avatar
> feat: update display of sudt in tx list

- CHANGELOG.md
- lerna.json
- package.json
- packages/neuron-ui/package.json
- packages/neuron-ui/src/locales/en.json
- packages/neuron-wallet/package.json
> Release v0.30.0

- packages/neuron-ui/src/components/TransactionList/transactionList.module.scss
> feat: set color of the confirming icon to green

- packages/neuron-ui/src/components/Overview/index.tsx
- packages/neuron-ui/src/components/TransactionList/index.tsx
- packages/neuron-ui/src/tests/formatters/sUDTAmountFormatter/fixtures.ts
- packages/neuron-ui/src/tests/formatters/sUDTAmountFormatter/index.test.ts
- packages/neuron-ui/src/utils/formatters.ts
truncate decimal if it has length > 8
> feat: better s-udt amount format

- packages/neuron-ui/src/components/SUDTAccountList/index.tsx
- packages/neuron-ui/src/components/SUDTCreateDialog/index.tsx
- packages/neuron-ui/src/components/SUDTCreateDialog/sUDTCreateDialog.module.scss
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/stories/SUDTCreateDialog.stories.tsx
- packages/neuron-ui/src/utils/const.ts
- packages/neuron-wallet/src/exceptions/wallet.ts
disable choice and change message color if balance is not enough to create a new account
> feat: add error messages on the create sUDT dialog

- packages/neuron-ui/src/components/Addresses/addresses.module.scss
- packages/neuron-ui/src/components/NervosDAO/index.tsx
- packages/neuron-ui/src/components/NervosDAO/nervosDAO.module.scss
- packages/neuron-ui/src/components/NervosDAORecord/index.tsx
- packages/neuron-ui/src/components/SpecialAsset/index.tsx
- packages/neuron-ui/src/components/SpecialAsset/specialAsset.module.scss
- packages/neuron-ui/src/components/TransactionList/index.tsx
- packages/neuron-ui/src/components/TransactionList/transactionList.module.scss
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/styles/mixin.scss
- packages/neuron-ui/src/widgets/CopyZone/index.tsx
> feat: use the Copy Component on more texts

- packages/neuron-wallet/electron-builder.yml
- packages/neuron-wallet/src/controllers/app/menu.ts
- packages/neuron-wallet/src/locales/en.ts
- packages/neuron-wallet/src/locales/zh-tw.ts
- packages/neuron-wallet/src/locales/zh.ts
> feat: add ckb client version in the about panel

- packages/neuron-wallet/electron-builder.yml
To fix the option-missing error on updating the default network
> fix: bundle ormconfig.json

- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
remove the requirement on the first character
> fix: update validation rules of password

- packages/neuron-ui/src/containers/Main/index.tsx
- packages/neuron-ui/src/containers/Navbar/index.tsx
- packages/neuron-ui/src/utils/enums.ts
- packages/neuron-ui/src/utils/hooks.ts
This branch enables the sUDT when it's the TESTNET.
> Enable sudt on testnet

- packages/neuron-ui/src/components/NervosDAO/nervosDAO.module.scss
- packages/neuron-ui/src/components/Overview/overview.module.scss
- packages/neuron-ui/src/styles/layout.scss
- packages/neuron-ui/src/styles/mixin.scss
Adjust the layouts of Overview and Nervos DAO, especially the title and meta info.
> feat: adjust vertical alignment of title and basic info

- packages/neuron-ui/src/utils/hooks.ts
- packages/neuron-wallet/src/locales/en.ts
- packages/neuron-wallet/src/locales/zh-tw.ts
- packages/neuron-wallet/src/locales/zh.ts
- packages/neuron-wallet/src/services/node.ts
allow user to install/skip/exit when the vcredist is missing
> feat: detect vcredist

- packages/neuron-ui/src/components/History/history.module.scss
- packages/neuron-ui/src/components/History/index.tsx
- packages/neuron-ui/src/components/TransactionList/transactionList.module.scss
> fix: remove unexpected padding and background in the transaction list

- packages/neuron-ui/src/widgets/TextField/textField.module.scss
> feat: enlarge the font size of error message

- packages/neuron-ui/src/components/SUDTAccountPile/sUDTAccountPile.module.scss
> feat: set the font size of sudt balance to 15px

- packages/neuron-ui/src/containers/Navbar/index.tsx
- packages/neuron-wallet/src/controllers/app/menu.ts
throttle the method of opening the settings window.
> feat: open the settings window with throttle time

- packages/neuron-ui/src/components/SUDTAccountPile/index.tsx
- packages/neuron-ui/src/components/SUDTReceive/index.tsx
- packages/neuron-ui/src/components/SUDTSend/index.tsx
- packages/neuron-ui/src/components/TransactionList/index.tsx
- packages/neuron-ui/src/stories/data/transactions.ts
- packages/neuron-ui/src/widgets/SUDTAvatar/index.tsx
> fix: use token avatar in the history

- packages/neuron-ui/src/components/SUDTAccountList/index.tsx
- packages/neuron-ui/src/components/SUDTCreateDialog/index.tsx
- packages/neuron-ui/src/services/remote/remoteApiWrapper.ts
- packages/neuron-ui/src/services/remote/sudt.ts
- packages/neuron-ui/src/types/Controller/index.d.ts
- packages/neuron-wallet/src/controllers/api.ts
- packages/neuron-wallet/src/controllers/asset-account.ts
- packages/neuron-wallet/src/database/chain/entities/sudt-token-info.ts
- packages/neuron-wallet/src/services/asset-account-service.ts
- packages/neuron-wallet/tests/services/asset-account-service.test.ts
1. add an api to fetch token info list
2. fetch the list on creating an account
> feat: share token infos across accounts

- packages/neuron-ui/src/components/Overview/index.tsx
- packages/neuron-ui/src/components/Overview/overview.module.scss
- packages/neuron-ui/src/components/Send/index.tsx
- packages/neuron-ui/src/components/Send/send.module.scss
Make them consistent with each other
> feat: update style of balance in overview and send

- packages/neuron-ui/src/components/GeneralSetting/index.tsx
- packages/neuron-ui/src/components/NetworkSetting/networkSetting.module.scss
- packages/neuron-wallet/src/controllers/api.ts
- packages/neuron-wallet/src/controllers/app/menu.ts
- packages/neuron-wallet/src/controllers/sync.ts
- packages/neuron-wallet/src/locales/en.ts
- packages/neuron-wallet/src/locales/zh-tw.ts
- packages/neuron-wallet/src/locales/zh.ts
1. set the width of the settings window to 900;
2. request confirmation to clear the cache;
> Adjust layout of settings

- packages/neuron-ui/src/components/NervosDAO/index.tsx
- packages/neuron-ui/src/components/NervosDAO/nervosDAO.module.scss
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
> feat: add a link to nervos dao docs

- packages/neuron-wallet/tests/utils/export-history/index.test.ts
Actually, `jest.spyOn` is sufficient for the test case `when file exists`.
> Fix fs mocks

- packages/neuron-ui/src/components/SignAndVerify/signAndVerify.module.scss
Before this PR:
After this PR:
> fix: move address list above buttons

- packages/neuron-wallet/src/block-sync-renderer/index.ts
- packages/neuron-wallet/src/block-sync-renderer/sync/indexer-connector.ts
- packages/neuron-wallet/src/block-sync-renderer/sync/indexer-folder-manager.ts
- packages/neuron-wallet/src/block-sync-renderer/sync/queue.ts
- packages/neuron-wallet/src/controllers/api.ts
- packages/neuron-wallet/src/controllers/sync.ts
- packages/neuron-wallet/src/models/chain/live-cell.ts
- packages/neuron-wallet/src/services/indexer-service.ts
- packages/neuron-wallet/tests/block-sync-render/index.test.ts
- packages/neuron-wallet/tests/block-sync-render/indexer-connector.test.ts
- packages/neuron-wallet/tests/block-sync-render/indexer-folder-manager.intg.test.ts
- packages/neuron-wallet/tests/block-sync-render/queue.test.ts
- yarn.lock
* Support soft and hard reset of indexer data via sync API
* Refactor relevant interfaces to sit within `IndexerConnector`
* Fix a bug to prevent subscribing to address change subject within renderer process
* Fix synced block number
> Support soft and hard reset of indexer data

- packages/neuron-ui/src/components/History/history.module.scss
- packages/neuron-ui/src/components/History/index.tsx
Use the small pagination no matter how tx count is.
> fix: use small-size pagination when tx count < 10000

- packages/neuron-ui/src/components/ClearCache/index.tsx
- packages/neuron-ui/src/components/ClearCache/style.module.scss
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
> feat: remove messages from the clear-cache confirmation dialog

- azure-pipelines.yml
set the vmImage for bundling Neuron-win-ver `vs2017-win2016`
> ci: bundle win-ver on windows vm

- packages/neuron-wallet/src/controllers/api.ts
- packages/neuron-wallet/src/controllers/app/index.ts
- packages/neuron-wallet/src/controllers/app/menu.ts
- packages/neuron-wallet/src/controllers/app/subscribe.ts
- packages/neuron-wallet/src/controllers/networks/index.ts
- packages/neuron-wallet/src/controllers/transactions.ts
- packages/neuron-wallet/src/controllers/update.ts
- packages/neuron-wallet/src/controllers/wallets.ts
- packages/neuron-wallet/src/exceptions/address.ts
- packages/neuron-wallet/src/exceptions/anyone-can-pay.ts
- packages/neuron-wallet/src/exceptions/common.ts
- packages/neuron-wallet/src/exceptions/dao.ts
- packages/neuron-wallet/src/exceptions/helper.ts
- packages/neuron-wallet/src/exceptions/key.ts
- packages/neuron-wallet/src/exceptions/network.ts
- packages/neuron-wallet/src/exceptions/transaction.ts
- packages/neuron-wallet/src/exceptions/wallet.ts
- packages/neuron-wallet/src/locales/i18n.ts
- packages/neuron-wallet/src/services/node.ts
- packages/neuron-wallet/src/utils/export-history.ts
- packages/neuron-wallet/src/utils/to-csv-row.ts
- packages/neuron-wallet/src/utils/validators.ts
- packages/neuron-wallet/tests/services/networks.test.ts
- packages/neuron-wallet/tests/setup.ts
- packages/neuron-wallet/tests/utils/validators.test.ts
The t function exported from locales/i18n doesn't work properly in some cases,
fixed by exporting it from i18next directly
> fix: fix the t function in wallet

- packages/neuron-ui/src/containers/Main/index.tsx
- packages/neuron-ui/src/containers/Navbar/index.tsx
- packages/neuron-ui/src/utils/enums.ts
- packages/neuron-ui/src/utils/hooks.ts
Avoid extra network requests and is more sensitive to toggle the nav item
By this PR the sUDT nav item will be updated on switching network even they are offline.
> refactor: toggle sudt nav item based on cached chain type

- README.md
- packages/neuron-ui/src/components/NervosDAO/index.tsx
- packages/neuron-ui/src/utils/const.ts
- packages/neuron-wallet/src/controllers/app/menu.ts
- packages/neuron-wallet/src/locales/en.ts
- packages/neuron-wallet/src/locales/zh-tw.ts
- packages/neuron-wallet/src/locales/zh.ts
1. update the nervos dao rules link
2. update the docs link in menubar
3. remove the faq link from menubar and readme
4. update the link of how-to-run-a-node in readme
> feat: update docs link

- packages/neuron-wallet/src/block-sync-renderer/sync/indexer-connector.ts
- packages/neuron-wallet/src/services/tx/transaction-persistor.ts
- packages/neuron-wallet/tests/block-sync-render/queue.intg.test.ts
* Fix an incorrect balance issue when importing a wallet
* Fix block number jumping up and down for wallets with certain patterns in their transaction history
> Remove unnecessary checking before upserting tx hash caches

- yarn.lock
ref: https://github.com/advisories/GHSA-wvhm-4hhf-97x9
> dep: upgrade prismjs to 1.12.0

- packages/neuron-ui/src/utils/const.ts
> According to the progress of ASIC mining, power, we could safely change the confirmation count from 300 to 24.
> feat: set confirmation threshold to 24

- packages/neuron-ui/src/components/Balance/balance.module.scss
- packages/neuron-ui/src/components/Balance/index.tsx
- packages/neuron-ui/src/components/Overview/index.tsx
- packages/neuron-ui/src/components/Overview/overview.module.scss
- packages/neuron-ui/src/components/Send/hooks.ts
- packages/neuron-ui/src/components/Send/index.tsx
- packages/neuron-ui/src/components/Send/send.module.scss
1. group import statements
2. rename event handler
3. move the `outputErrors` hook into custom hooks module
4. combine locktime button event handlers
5. add a Balance Component for Overview and Send Components
> Refactor send component

- packages/neuron-ui/.storybook/main.js
Fix the resolution of electron module in storybook
> fix: fix module resolution in storybook

- packages/neuron-ui/src/stories/RingProgressBar.stories.tsx
- packages/neuron-ui/src/stories/index.tsx
- packages/neuron-ui/src/widgets/RingProgressBar/index.tsx
Will be used in the new sync component
> feat: add an ring progress bar widget

- packages/neuron-ui/src/components/Transaction/index.tsx
- packages/neuron-ui/src/tests/scriptToAddress/fixtures.json
- packages/neuron-ui/src/tests/scriptToAddress/index.test.ts
- packages/neuron-ui/src/utils/enums.ts
- packages/neuron-ui/src/utils/index.ts
- packages/neuron-ui/src/utils/scriptToAddress.ts
feat: show multisig address in short version
> feat: show multisig address in short version

- packages/neuron-ui/src/components/PasswordRequest/index.tsx
- packages/neuron-ui/src/components/SUDTSend/index.tsx
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/types/App/index.d.ts
Used to distinguish send-sudt from send-acp in UI
> feat: add an action type of send acp

- packages/neuron-ui/src/tests/getSyncLeftTime/fixtures.json
- packages/neuron-ui/src/utils/getSyncLeftTime.ts
> feat: update estimated left time format

- packages/neuron-wallet/src/services/hardware/hardware.ts
- packages/neuron-wallet/src/services/hardware/ledger.ts
ref:
https://github.com/nervosnetwork/neuron-internal/issues/1307
> refactor: change ledger default path to `m/44'/309'/0'`

- packages/neuron-wallet/src/controllers/export-debug.ts
- packages/neuron-wallet/src/database/chain/cleaner.ts
- packages/neuron-wallet/src/locales/en.ts
- packages/neuron-wallet/src/locales/zh-tw.ts
- packages/neuron-wallet/src/locales/zh.ts
- packages/neuron-wallet/src/services/node.ts
- packages/neuron-wallet/tests/controllers/export-debug.test.ts
- include `hd_public_key_info` in debug log
- keep `hd_public_key_info` when resetting cache
- requires x64 vcredist on windows
> More logs on the data points to fix sync issue in 0.33

- packages/neuron-ui/src/components/SUDTAccountList/index.tsx
- packages/neuron-ui/src/services/remote/remoteApiWrapper.ts
- packages/neuron-ui/src/services/remote/sudt.ts
- packages/neuron-ui/src/types/Controller/index.d.ts
- packages/neuron-wallet/src/controllers/asset-account.ts
1. check migrate acp status on entering sudt account list
2. redirect to overview on rejection
> feat: check migrate acp status on entering sudt account list

- package.json
- packages/neuron-ui/src/components/HardwareSign/index.tsx
- packages/neuron-ui/src/exceptions/hardware.ts
- packages/neuron-ui/src/types/Controller/index.d.ts
- packages/neuron-wallet/src/controllers/wallets.ts
- packages/neuron-wallet/src/services/wallets.ts
Also, if the hardware wallet's original descriptor fails to connect, it will update the wallet's descriptor after reconnection is successful.
> fix: ensure that the ckb app is open for every device operation

- packages/neuron-ui/src/components/History/index.tsx
- packages/neuron-ui/src/components/NervosDAO/index.tsx
- packages/neuron-ui/src/components/Overview/index.tsx
- packages/neuron-ui/src/components/SUDTAccountList/index.tsx
- packages/neuron-ui/src/components/Send/index.tsx
- packages/neuron-ui/src/components/SpecialAssetList/index.tsx
- packages/neuron-ui/src/containers/Main/hooks.ts
- packages/neuron-ui/src/containers/Navbar/index.tsx
- packages/neuron-ui/src/services/subjects.ts
- packages/neuron-ui/src/states/init/chain.ts
- packages/neuron-ui/src/states/stateProvider/reducer.ts
- packages/neuron-ui/src/types/App/index.d.ts
- packages/neuron-ui/src/types/Subject/index.d.ts
- packages/neuron-wallet/src/block-sync-renderer/index.ts
- packages/neuron-wallet/src/block-sync-renderer/sync/queue.ts
- packages/neuron-wallet/src/controllers/app/index.ts
- packages/neuron-wallet/src/controllers/app/subscribe.ts
- packages/neuron-wallet/src/controllers/sync-api.ts
- packages/neuron-wallet/src/models/subjects/sync-state-subject.ts
- packages/neuron-wallet/tests/block-sync-render/index.test.ts
- packages/neuron-wallet/tests/block-sync-render/queue.test.ts
- packages/neuron-wallet/tests/controllers/sync-api.test.ts
- Provide the `SyncStatus` through the `SyncStateSubject`
- Refactor both the front end and back end for the `SyncStatus`
> refactor: sync estimation

- packages/neuron-ui/src/tests/scriptToAddress/fixtures.json
- packages/neuron-ui/src/utils/enums.ts
- packages/neuron-ui/src/utils/scriptToAddress.ts
1. add checking on args' length
2. add anyone-can-pay into recognizable lock scripts
> fix(ui): fix script to address

- packages/neuron-ui/src/components/WalletSetting/index.tsx
- packages/neuron-wallet/src/controllers/app/menu.ts
Will enable hardware wallet after ckb app is approved on ledger store.
> hide hardware wallet import menu in production

- CHANGELOG.md
- azure-pipelines.yml
- lerna.json
- package.json
- packages/neuron-ui/package.json
- packages/neuron-wallet/package.json
@kellyshang Please make another PR based off this one to update the release note and version bump.
> fix libudev-dev dependency for ubuntu build

- CHANGELOG.md
- azure-pipelines.yml
- lerna.json
- package.json
- packages/neuron-ui/package.json
- packages/neuron-ui/src/components/ImportHardware/confirming.tsx
- packages/neuron-ui/src/components/Receive/index.tsx
- packages/neuron-ui/src/components/VerifyHardwareAddress/index.tsx
- packages/neuron-ui/src/components/VerifyHardwareAddress/verify-error.tsx
- packages/neuron-ui/src/components/VerifyHardwareAddress/verifyHardwareAddress.module.scss
- packages/neuron-ui/src/components/WalletSetting/index.tsx
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/services/remote/hardware.ts
- packages/neuron-ui/src/services/remote/remoteApiWrapper.ts
- packages/neuron-wallet/package.json
- packages/neuron-wallet/src/controllers/api.ts
- packages/neuron-wallet/src/controllers/app/menu.ts
- packages/neuron-wallet/src/controllers/hardware.ts
- packages/neuron-wallet/src/services/hardware/common.ts
- packages/neuron-wallet/src/services/hardware/hardware.ts
- packages/neuron-wallet/src/services/hardware/ledger.ts
- packages/neuron-wallet/tests/controllers/hardware.test.ts
- packages/neuron-wallet/tests/mock/hardware.ts
- verify hardware address
- upgrade hw-app-ckb to 0.1.2
@kellyshang Please make another PR based off this one to update the release note and version bump.
> 0.35.0 rc1

- packages/neuron-ui/src/components/SpecialAsset/index.tsx
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
> feat: add tooltip of locked withdraw assets

- packages/neuron-ui/src/components/ImportHardware/index.tsx
- packages/neuron-ui/src/components/ImportHardware/select-model.tsx
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/widgets/ExperimentalRibbon/index.tsx
This commit adds a dialog to show an alert message about importing hardware wallets.
> feat: add alert dialog of ledger

- packages/neuron-ui/src/components/DepositDialog/index.tsx
- packages/neuron-ui/src/components/NervosDAO/index.tsx
- packages/neuron-ui/src/stories/DepositDialog.stories.tsx
Add an onOpen hook to initialize data of deposit dao dialog
> fix: fix init data of deposit dao dialog

- azure-pipelines.yml
- packages/neuron-wallet/src/controllers/export-debug.ts
- packages/neuron-wallet/src/services/networks.ts
- packages/neuron-wallet/tests/services/networks.test.ts
- fix the file name `bundled-ckb-log.json`
- rename default node names `Default` / `Mainnet` to `default node`
- remove libudev for linux builds as it is not necessary anymore
> Wording fixes

- packages/neuron-ui/src/components/SUDTCreateDialog/index.tsx
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
> feat: add hint for token id field

- .github/workflows/package.yml
- .github/workflows/unit_tests.yml
- azure-pipelines.yml
- packages/neuron-wallet/electron-builder.yml
- scripts/release.sh
1. add action of unit tests
2. add action of publishment
3. add action of uploading artifacts
> ci: add github actions

- .github/workflows/package.yml
1. triggered on push event of master, rc/**
2. triggered on pr merge event of master, rc/**
3. not triggered on pr open event of master, rc/**
> ci: update github action of packaging

- packages/neuron-wallet/src/controllers/app/index.ts
- packages/neuron-wallet/src/controllers/mercury.ts
- packages/neuron-wallet/src/main.ts
- packages/neuron-wallet/src/services/indexer.ts
* Rename ckb-indexer data folder from `ckb-indexer` to `ckb_indexer_data`
* Start migration before migrate dialog is open
> fix: migration failure in some cases

- packages/neuron-ui/src/components/SendFieldset/index.tsx
- packages/neuron-ui/src/tests/scriptToAddress/fixtures.json
- packages/neuron-ui/src/utils/scriptToAddress.ts
- packages/neuron-wallet/src/block-sync-renderer/mercury/indexer.ts
- packages/neuron-wallet/src/block-sync-renderer/sync/indexer-connector.ts
- packages/neuron-wallet/src/models/address-parser.ts
- packages/neuron-wallet/src/models/chain/script.ts
- packages/neuron-wallet/tests/block-sync-render/indexer-connector.test.ts
- packages/neuron-wallet/tests/models/address-parser.test.ts
1. add hash type 'data1'
2. update AddressParser to handle '0x00' format address
3. display new full version address instead of obselete full version
address in transaction detail
4. remove 100 chars limitation from address field
> feat: support new full version address

- packages/neuron-wallet/package.json
- yarn.lock
fix some file is empty when export debug info
> update archiver from 4.0.2 to 5.3.0

- packages/neuron-wallet/src/controllers/export-debug.ts
- packages/neuron-wallet/src/services/node.ts
- packages/neuron-wallet/src/utils/redist-check.ts
- packages/neuron-wallet/tests/utils/redist-check/index.test.ts
> add redist log

- packages/neuron-ui/src/components/NervosDAO/hooks.ts
> fix: fix error message of invalid amount on depositing

- packages/neuron-wallet/src/controllers/transactions.ts
- packages/neuron-wallet/src/services/addresses.ts
- packages/neuron-wallet/src/services/tx/transaction-service.ts
Tx with SECP256k1 lock code hash will be collected in tx count
> fix: fix tx count collection

- packages/neuron-ui/package.json
- packages/neuron-ui/src/services/chain.ts
- packages/neuron-wallet/package.json
- packages/neuron-wallet/src/services/transaction-sender.ts
- yarn.lock
replace rpc calculate_dao_maximum_withdraw by js-sdk
> feat: replace calculate_dao_maximum_withdraw with calculateDaoMaximumWithdraw method in sdk

- README.md
> docs: remove azure badge

- packages/neuron-ui/src/components/SendFieldset/index.tsx
- packages/neuron-ui/src/components/SendFieldset/sendFieldset.module.scss
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
> feat: add warn text when send transaction has set locktime

- packages/neuron-wallet/src/block-sync-renderer/index.ts
- packages/neuron-wallet/src/controllers/networks/index.ts
- packages/neuron-wallet/src/services/networks.ts
- packages/neuron-wallet/tests/block-sync-renderer/index/switchNetwork.test.ts
Try to update network information from node before
synchronization
> feat: update network information before synchronization

- packages/neuron-ui/src/components/SignAndVerify/index.tsx
- packages/neuron-ui/src/components/SignAndVerify/signAndVerify.module.scss
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/services/remote/wallets.ts
- packages/neuron-wallet/src/controllers/sign-message.ts
- packages/neuron-wallet/src/services/sign-message.ts
- packages/neuron-wallet/tests/services/sign-message.test.ts
> feat: add new sign tips and add old sign notice

- README.md
1. remove badge of telegram
2. add badge of discord
> feat: update community badges

- packages/neuron-ui/src/components/SendFromMultisigDialog/hooks.ts
- packages/neuron-ui/src/components/SendFromMultisigDialog/index.tsx
- packages/neuron-ui/src/services/remote/multisig.ts
- packages/neuron-ui/src/services/remote/remoteApiWrapper.ts
- packages/neuron-wallet/src/controllers/api.ts
- packages/neuron-wallet/src/controllers/wallets.ts
- packages/neuron-wallet/src/services/cells.ts
- packages/neuron-wallet/src/services/transaction-sender.ts
- packages/neuron-wallet/src/services/tx/transaction-generator.ts
- packages/neuron-wallet/tests/services/cells.test.ts
- packages/neuron-wallet/tests/services/tx/transaction-generator.test.ts
- packages/neuron-wallet/tests/services/tx/transaction-sender.test.ts
https://user-images.githubusercontent.com/12881040/161878584-7dad5ade-f6ea-42a1-886b-e1a6b7162dcf.mov
> feat: Add send max when create multisig transaction

- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-wallet/src/controllers/app/menu.ts
- packages/neuron-wallet/src/locales/en.ts
- packages/neuron-wallet/src/locales/zh-tw.ts
- packages/neuron-wallet/src/locales/zh.ts
> fix: Change menu name.

- packages/neuron-ui/src/components/SUDTSend/index.tsx
- packages/neuron-ui/src/locales/en.json
sudt/acp send any amount to secp256k1 address
https://user-images.githubusercontent.com/12881040/163559889-831864e7-d896-4e62-b8e9-941e72f9a285.mov
Result:
> fix: sudt/acp can send any amount to secp256k1 address

- packages/neuron-ui/src/components/History/hooks.ts
- packages/neuron-ui/src/components/SpecialAssetList/index.tsx
- packages/neuron-ui/src/services/chain.ts
- packages/neuron-ui/src/tests/parsers/index.test.ts
- packages/neuron-ui/src/utils/parsers.ts
1. refactor epochParser with SDK
2. remove unused prompt function
3. fix toUint128Le function, it read wrong bytes in low digits
> fix: fix parsers

- packages/neuron-ui/src/components/HardwareSign/index.tsx
- packages/neuron-ui/src/components/PasswordRequest/index.tsx
- packages/neuron-ui/src/components/SUDTSend/index.tsx
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/services/remote/remoteApiWrapper.ts
- packages/neuron-ui/src/services/remote/specialAssets.ts
- packages/neuron-ui/src/types/App/index.d.ts
- packages/neuron-wallet/src/controllers/api.ts
- packages/neuron-wallet/src/controllers/asset-account.ts
- packages/neuron-wallet/src/exceptions/anyone-can-pay.ts
- packages/neuron-wallet/src/locales/en.ts
- packages/neuron-wallet/src/locales/zh-tw.ts
- packages/neuron-wallet/src/locales/zh.ts
- packages/neuron-wallet/src/services/asset-account-service.ts
- packages/neuron-wallet/src/services/tx/transaction-generator.ts
- packages/neuron-wallet/tests/controllers/asset-account.test.ts
- packages/neuron-wallet/tests/services/asset-account-service.test.ts
- packages/neuron-wallet/tests/services/tx/transaction-generator.test.ts
1. Destroy sUDT acp account
https://user-images.githubusercontent.com/12881040/164125278-3b8f7276-fd9e-46f4-81bf-bebacf7ea475.mov
2. Destroy CKB acp account
https://user-images.githubusercontent.com/12881040/164125331-0d2fadab-4e73-455f-b256-e48eaa765dcc.mov
> feat: SUDT acp account can destory when sUDT amount is 0

- packages/neuron-ui/src/components/SendFromMultisigDialog/sendFromMultisigDialog.module.scss
- packages/neuron-wallet/src/controllers/app/menu.ts
> refactor: refine multisig window

- packages/neuron-ui/src/components/PasswordRequest/index.tsx
- packages/neuron-ui/src/services/remote/app.ts
- packages/neuron-ui/src/services/remote/remoteApiWrapper.ts
- packages/neuron-ui/src/types/Controller/index.d.ts
- packages/neuron-wallet/src/controllers/api.ts
- packages/neuron-wallet/src/locales/en.ts
- packages/neuron-wallet/src/locales/zh-tw.ts
- packages/neuron-wallet/src/locales/zh.ts
Prompt a dialog to view multisig tx in explorer after sending
https://user-images.githubusercontent.com/7271329/166424540-09b22e16-3ea2-4d3b-93d5-a5d412f8e220.mov
> feat: request to open multisig tx in explorer

- packages/neuron-ui/src/components/ApproveMultisigTx/index.tsx
- packages/neuron-ui/src/components/HardwareSign/hardwareSign.module.scss
- packages/neuron-ui/src/components/HardwareSign/index.tsx
- packages/neuron-wallet/src/services/asset-account-service.ts
- packages/neuron-wallet/src/services/transaction-sender.ts
- packages/neuron-wallet/tests/services/asset-account-service.test.ts
- packages/neuron-wallet/tests/services/tx/transaction-sender.test.ts
https://user-images.githubusercontent.com/12881040/165659068-e77e9dea-8b97-4d39-a753-9fe47511b7dd.mov
https://user-images.githubusercontent.com/12881040/165659079-a34b3252-b0d6-462e-b06f-fd1d3ba82a27.mov
https://user-images.githubusercontent.com/12881040/165660052-9eb30f5a-524c-4c92-bd95-f57838f6f54a.mov
https://user-images.githubusercontent.com/12881040/165660060-991778d6-0806-45eb-85f0-adc99496e9e8.mp4
> fix: Fix some bug for hard wallet

- .github/workflows/package.yml
- .github/workflows/package_for_test.yml
Ref: https://github.com/nervosnetwork/neuron/pull/2373, https://github.com/nervosnetwork/neuron/pull/2373#discussion_r873435376
> ci: bump node version to 16.10.0

- packages/neuron-ui/src/components/GeneralSetting/index.tsx
- packages/neuron-wallet/src/controllers/update.ts
> fix: Remove covering above `update` button

- packages/neuron-ui/src/components/SettingTabs/index.tsx
- packages/neuron-ui/src/components/SettingTabs/settingTabs.module.scss
- packages/neuron-ui/src/components/WalletSetting/walletSetting.module.scss
> fix: Remove scroll

- packages/neuron-wallet/tests/services/monitor.test.ts
- packages/neuron-wallet/tests/services/tx/transaction-generator.test.ts
- packages/neuron-wallet/tests/services/tx/transaction-service.test.ts
- packages/neuron-wallet/tests/setupAndTeardown/transactions.fixture.ts
1. Fix some test cases may failed sometimes in local.
> Fix local testcase

- packages/neuron-ui/src/components/ImportHardware/detect-device.tsx
- packages/neuron-ui/src/components/ImportHardware/name-wallet.tsx
- packages/neuron-ui/src/components/ImportHardware/select-model.tsx
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/services/remote/hardware.ts
1. If the device is adapt
https://user-images.githubusercontent.com/12881040/176607494-d5755935-c518-48d3-9d78-108faa3b41d2.mov
2. If a new device does not adapt in the future, maybe you can try select other option if the APIs do not change
https://user-images.githubusercontent.com/12881040/176607570-75ed1941-8355-46c1-a205-24bcf5cd1541.mov
> fix: Adapt ledger nano s plus.

- packages/neuron-wallet/src/services/indexer.ts
Avoid the promise can't resolve or reject.
> fix: Use retry times to replace while.

- packages/neuron-ui/src/components/MultisigAddressCreateDialog/index.tsx
> fix: Show confirm error.

- packages/ckb-indexer/package.json
- packages/neuron-wallet/tests/services/monitor.test.ts
* fix: New instance for every test case to avoid side effect
> fix: New instance for every test case to avoid side effect (#2488)

- packages/neuron-wallet/tests/services/tx/transaction-generator.test.ts
Ref: https://github.com/Magickbase/neuron-public-issues/issues/67
> refactor: use Array.prototype.forEach instead of Array.prototype.map

- package.json
- packages/neuron-wallet/electron-builder.yml
- yarn.lock
1. Remove ckb-indexer copy.
2. Set `usb` version fixed.
> fix: Optimize build

- packages/neuron-wallet/assets/entitlements.plist
- packages/neuron-wallet/package.json
- packages/neuron-wallet/scripts/notarize.js
- yarn.lock
Reference https://github.com/electron-userland/electron-builder/issues/7050#issuecomment-1226594909
> fix: Fix release with arm64

- packages/neuron-wallet/electron-builder.yml
I have tested https://github.com/nervosnetwork/neuron/actions/runs/3872095514 on `windows`. I install it on the desktop. It runs normally.
> feat: Set allowToChangeInstallationDirectory for windows. (#2567)

- packages/neuron-wallet/package.json
- yarn.lock
> fix: messages.codes.SQLITE_MISUSE (#2575) 

- packages/neuron-ui/src/states/stateProvider/actionCreators/wallets.ts
1. The movie before fix
https://user-images.githubusercontent.com/12881040/222609926-0c53ab9a-5c13-4ba6-a83b-811e3726922e.mov
2. After fixed
https://user-images.githubusercontent.com/12881040/222609966-cedad997-ab61-489a-973e-b768552ade78.mov
> fix: Save addresses to local storage when update addresses

- packages/neuron-ui/src/components/DataSetting/index.tsx
- packages/neuron-ui/src/services/remote/app.ts
- packages/neuron-ui/src/services/remote/remoteApiWrapper.ts
- packages/neuron-wallet/src/controllers/api.ts
- packages/neuron-wallet/src/controllers/app/index.ts
- packages/neuron-wallet/src/locales/en.ts
- packages/neuron-wallet/src/locales/zh-tw.ts
- packages/neuron-wallet/src/locales/zh.ts
- packages/neuron-wallet/src/services/indexer.ts
- packages/neuron-wallet/src/services/node.ts
- packages/neuron-wallet/src/services/rpc-service.ts
- packages/neuron-wallet/src/utils/const.ts
- packages/neuron-wallet/src/utils/rpc-request.ts
- packages/neuron-wallet/tests/services/indexer.test.ts
- packages/neuron-wallet/tests/services/node.test.ts
**The Code changes**
1. Add node version and start parameter judgment.
2. Disable the data path set button if ckb node is started externally.
**The display when start without indexer or start a different version**
1. Start ckb node external without --indexer
2. Start a different version ckb node
> feat: Add node version and start parameter judgement.

- .github/workflows/check_checksums.yml
- .github/workflows/merge_released_into_develop.yml
- .github/workflows/package_for_test.yml
1. set 'merge released to develop' reviewers to keith-cy
2. upgrade peter-evans/commit-comment to v2
> ci: update reviewers and action versions

- packages/neuron-ui/src/components/OfflineSign/index.tsx
- packages/neuron-ui/src/components/OfflineSign/offlineSign.module.scss
- packages/neuron-ui/src/components/OfflineSignDialog/index.tsx
- packages/neuron-ui/src/widgets/Button/button.module.scss
Offline Sign with new uidesign
https://github.com/Magickbase/neuron-public-issues/issues/118
- Light Theme
https://user-images.githubusercontent.com/11756869/232943054-6a74c7cd-636d-42f2-a580-e79ca4ce67e4.mp4
- Dark Theme
https://user-images.githubusercontent.com/11756869/232985997-fa9b7da2-c9ec-46ae-b29c-23753d8bb5a6.mp4
> feat: Offline Sign with new ui

- packages/neuron-wallet/src/services/networks.ts
fix: applyLocalhostIPv4Resolve caused additional impact
> fix: applyLocalhostIPv4Resolve caused additional impact

- .github/workflows/package.yml
- .github/workflows/package_for_test.yml
chore: use macos-latest for package
> chore: use macos-latest for package

- packages/neuron-ui/src/components/HistoryDetailPage/historyDetailPage.module.scss
- packages/neuron-ui/src/components/HistoryDetailPage/index.tsx
- packages/neuron-ui/src/widgets/Tabs/index.tsx
> Refactor Tabs

- packages/neuron-wallet/package.json
- packages/neuron-wallet/src/services/cells.ts
- packages/neuron-wallet/src/services/multisig.ts
- yarn.lock
------
As title.
Ref: https://github.com/Magickbase/neuron-public-issues/issues/124
Check List
------
1、List
2、Detail
e2e Test
none
> fix:update dependency sqlite3 to v5.1.6

- packages/neuron-wallet/package.json
- packages/neuron-wallet/tests/block-sync-renderer/indexer-cache-service.intg.test.ts
- yarn.lock
------
As title.
Ref: https://github.com/Magickbase/neuron/pull/162
Check List
------
1、List
2、Detail
e2e Test
none
> fix: update dependency jest when to v3

- packages/neuron-ui/src/components/BalanceSyncingIcon/balanceSyncIcon.module.scss
- packages/neuron-ui/src/components/Overview/overview.module.scss
- packages/neuron-ui/src/components/SyncStatus/syncStatus.module.scss
- packages/neuron-ui/src/styles/animation.scss
------
As title.
Ref: https://github.com/Magickbase/neuron-public-issues/issues/161
Check List
------
1、List
2、Detail
e2e Test
none
> fix: loading sync icons lack animation

- .github/workflows/package.yml
- .github/workflows/package_for_test.yml
- .github/workflows/unit_tests.yml
- .husky/pre-commit
- README.md
- lerna.json
- package.json
- yarn.lock
For `lerna` v7 run, it seems will auto-read the .env file in the current directory. So I need to change the test file.
> feat: Update lerna to v7

- packages/neuron-ui/package.json
- packages/neuron-wallet/package.json
I just realized that I didn't include Prettier in the lint-staged process before. 
🙉
> fix: prettier was not run during the commit

- .github/workflows/check-spell.yml
[fix-spell](https://github.com/nervosnetwork/neuron/tree/fix-spell) is a branch to fix spells in this project, there'll be two steps:
1. add a ci to check spell of changed files
2. fix spells according to the prompts from ci added in step 1
Step 2 will be implemented on [fix-spell](https://github.com/nervosnetwork/neuron/tree/fix-spell)
> ci: add an action to check spell

- packages/neuron-ui/src/components/Receive/multiAddressReceive.tsx
- packages/neuron-ui/src/components/Receive/receive.module.scss
- packages/neuron-ui/src/widgets/CopyZone/copyZone.module.scss
------
As title.
Ref: https://github.com/Magickbase/neuron-public-issues/issues/166
Check List
------
e2e Test
> Fix: issues for receive page

- packages/neuron-wallet/package.json
- yarn.lock
Adjust the installation position of **prettier**、**lint-staged** to the top layer
> chore: dependencies (prettier、lint-staged)

- packages/neuron-ui/src/components/History/RowExtend.tsx
- packages/neuron-ui/src/components/History/history.module.scss
- packages/neuron-ui/src/components/History/index.tsx
- packages/neuron-ui/src/components/HistoryDetailPage/index.tsx
- packages/neuron-ui/src/components/LockInfoDialog/index.tsx
- packages/neuron-ui/src/tests/formatters/complexNumberToPureNumber/fixtures.ts
- packages/neuron-ui/src/tests/formatters/complexNumberToPureNumber/index.test.ts
- packages/neuron-ui/src/utils/formatters.ts
- packages/neuron-ui/src/widgets/Table/index.tsx
------
As title.
Ref:https://github.com/Magickbase/neuron-public-issues/issues/169
Check List
------
e2e Test
> fix: issues for history page

- packages/neuron-ui/src/components/NervosDAO/nervosDAO.module.scss
- packages/neuron-ui/src/components/PageContainer/pageContainer.module.scss
- packages/neuron-ui/src/components/Receive/multiAddressReceive.tsx
- packages/neuron-ui/src/components/Receive/receive.module.scss
- packages/neuron-ui/src/components/SUDTReceiveDialog/index.tsx
- packages/neuron-ui/src/components/SUDTReceiveDialog/sUDTReceiveDialog.module.scss
- packages/neuron-ui/src/styles/index.scss
------
https://github.com/Magickbase/neuron-public-issues/issues/166#issuecomment-1617481787
https://github.com/nervosnetwork/neuron/assets/22511289/395fe764-9e2b-43a5-844c-0bdbe3e1ea20
https://github.com/nervosnetwork/neuron/assets/22511289/521783e5-2a49-4f84-ad67-12386dea043b
Ref: https://github.com/Magickbase/neuron-public-issues/issues/166
Check List
------
e2e Test
> fix:update the display of receive address

- .github/workflows/package_for_test.yml
https://github.com/yanguoyu/neuron/pull/85#issuecomment-1639160771 is the result that runs by checking out the PR branch with the PR number.
> chore(CI): Use pr branch for checkout.

- packages/neuron-ui/src/components/Receive/multiAddressReceive.tsx
Resolve: https://github.com/Magickbase/neuron-public-issues/issues/222
After change preview:
> fix: address book abbreviation not right

- .github/workflows/check-code-style.yml
- .github/workflows/update_valid_target.yml
- package.json
- scripts/update-valid-target.js
Reference to https://github.com/Magickbase/neuron-public-issues/issues/211.
https://github.com/yanguoyu/neuron/pull/82 is the PR create by action triggered by https://github.com/yanguoyu/neuron/pull/72 ready for review.
> chore: Add action to update assume valid target

- packages/neuron-ui/src/components/PricePanel/index.tsx
- packages/neuron-ui/src/components/PricePanel/pricePanel.module.scss
- packages/neuron-ui/src/components/Send/send.module.scss
Reference to https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU?node-id=451:5672&mode=design#500440764.
So we can use the tooltip component to show tips.
> fix: Use common tips style.

- packages/neuron-ui/src/components/Overview/overview.module.scss
- packages/neuron-ui/src/components/PricePanel/index.tsx
- packages/neuron-ui/src/components/Send/hooks.ts
- packages/neuron-ui/src/components/Send/index.tsx
- packages/neuron-ui/src/components/Send/send.module.scss
- packages/neuron-ui/src/states/init/app.ts
- packages/neuron-ui/src/states/stateProvider/reducer.ts
- packages/neuron-ui/src/types/App/index.d.ts
- packages/neuron-ui/src/widgets/DropdownWithCustomRender/index.module.scss
fix issues:
- https://github.com/Magickbase/neuron-public-issues/issues/237
- https://github.com/Magickbase/neuron-public-issues/issues/238
> fix: issues - 237、238

- packages/neuron-ui/src/components/Receive/multiAddressReceive.tsx
- packages/neuron-ui/src/components/Receive/receive.module.scss
- packages/neuron-ui/src/widgets/Table/index.tsx
https://github.com/Magickbase/neuron-public-issues/issues/253
> fix: issue 253

- packages/neuron-ui/src/components/ClearCache/clearCache.module.scss
- packages/neuron-ui/src/components/History/RowExtend.tsx
- packages/neuron-ui/src/components/History/history.module.scss
- packages/neuron-ui/src/components/History/index.tsx
- packages/neuron-ui/src/components/Receive/multiAddressReceive.tsx
- packages/neuron-ui/src/components/Receive/receive.module.scss
- packages/neuron-ui/src/components/SUDTAccountList/sUDTAccountList.module.scss
- packages/neuron-ui/src/components/SUDTMigrateDialog/sUDTMigrateDialog.module.scss
- packages/neuron-ui/src/components/SpecialAssetList/specialAssetList.module.scss
- packages/neuron-ui/src/containers/Navbar/navbar.module.scss
- packages/neuron-ui/src/styles/mixin.scss
- packages/neuron-ui/src/styles/theme.scss
- packages/neuron-ui/src/widgets/Table/index.tsx
- packages/neuron-ui/src/widgets/Table/table.module.scss
1. History cursor and search width
2. Receive dismiss table hover tr and add pointer.
3. [Fix navbar style, and asset account less three slider](https://github.com/nervosnetwork/neuron/pull/2799/commits/d74d71a39b73060b2b58b6e458a411d875aac445)
4. [fix: Fix edit history desc](https://github.com/nervosnetwork/neuron/pull/2799/commits/79999ebb8d755cf5c36ecdc72f5861c1f2a51d38)
> fix: Fix styles.

- packages/neuron-ui/src/components/ApproveMultisigTxDialog/approveMultisigTx.module.scss
- packages/neuron-ui/src/components/ApproveMultisigTxDialog/index.tsx
- packages/neuron-wallet/src/controllers/multisig.ts
- packages/neuron-wallet/src/controllers/offline-sign.ts
- packages/neuron-wallet/src/services/offline-sign.ts
- packages/neuron-wallet/tests/controllers/multisig.test.ts
- packages/neuron-wallet/tests/controllers/offline-sign.test.ts
- packages/neuron-wallet/tests/services/offline-sign.test.ts
fix: 
- https://github.com/Magickbase/neuron-public-issues/issues/266
> fix: Style issue with multisig addresses

- .github/workflows/update_ckb_client_versions.yml
- package.json
- scripts/update-ckb-client-versions.js
This PR adds an action to check/update versions of ckb node and ckb light client
Ref: https://github.com/Magickbase/neuron-public-issues/issues/273
> ci: add github action to update versions of ckb node and light client

- packages/neuron-ui/src/components/DepositDialog/hooks.ts
- packages/neuron-ui/src/components/DepositDialog/index.tsx
- packages/neuron-ui/src/components/History/RowExtend.tsx
- packages/neuron-ui/src/components/History/index.tsx
- packages/neuron-ui/src/components/SUDTAccountList/sUDTAccountList.module.scss
- packages/neuron-ui/src/components/SUDTAccountPile/sUDTAccountPile.module.scss
- packages/neuron-ui/src/components/SUDTMigrateToExistAccountDialog/index.tsx
- packages/neuron-ui/src/components/SUDTMigrateToNewAccountDialog/index.tsx
- packages/neuron-ui/src/components/SUDTReceiveDialog/index.tsx
- packages/neuron-ui/src/components/SUDTReceiveDialog/sUDTReceiveDialog.module.scss
- packages/neuron-ui/src/components/SpecialAssetList/index.tsx
- packages/neuron-ui/src/components/UANDisplay/index.module.scss
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/states/stateProvider/actionCreators/sudt.ts
- packages/neuron-ui/src/states/stateProvider/actionCreators/wallets.ts
- packages/neuron-ui/src/utils/baseActions.ts
- packages/neuron-ui/src/widgets/SUDTAvatar/sUDTAvatar.module.scss
- packages/neuron-ui/src/widgets/TextField/index.tsx
- packages/neuron-wallet/src/block-sync-renderer/tx-status-listener.ts
1. fix the label of a text field
2. fix transaction generation in Nervos DAO panel
> Merge some fixes into rc/v0.110.3

- packages/neuron-ui/src/components/SUDTSend/index.tsx
fix issue: https://github.com/Magickbase/neuron-public-issues/issues/277
> fix: issue - 277

- packages/neuron-ui/src/containers/Navbar/navbar.module.scss
https://github.com/nervosnetwork/neuron/assets/12881040/7356fd63-284d-433b-9fd3-ce4ceca88d7c
> Fix: fix the nav bar to fixed

- scripts/generate-checksum-table.js
The checksum table can be appended in release note
This script facilitates https://github.com/Magickbase/neuron-public-issues/issues/141
> chore: add a script to generate checksum table

- compatible.csv
- packages/neuron-wallet/src/services/node.ts
This step should be added to the release steps. We'd better add an action to update it to avoid forgetting.
> fix: Update compatible.csv after update ckb and Neuron version

- packages/neuron-ui/src/components/MultisigAddress/index.tsx
fix: https://github.com/Magickbase/neuron-public-issues/issues/321
https://github.com/nervosnetwork/neuron/assets/11756869/6c8eadfb-de98-41b7-a185-92f9587d28b3
> fix: Issue of creating multisig address

- CHANGELOG.md
1. update release date
2. update ckb light version
3. update assume valid target
4. add changelog of fixing transaction recognition on light client mode
> chore: Update ckb node assume valid target for rc/v0.112.0.

- packages/neuron-ui/src/components/ClearCache/index.tsx
- packages/neuron-ui/src/components/DataSetting/index.tsx
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/services/remote/app.ts
- packages/neuron-ui/src/types/Controller/index.d.ts
- packages/neuron-wallet/src/controllers/api.ts
- packages/neuron-wallet/src/services/indexer.ts
- packages/neuron-wallet/tests/services/indexer.test.ts
Refer to https://github.com/Magickbase/neuron-public-issues/issues/330
https://github.com/nervosnetwork/neuron/assets/12881040/cfac896f-6995-45d5-9a80-a6af56c93772
> feat: Remove rebuild index of separated indexer

- packages/neuron-ui/src/components/LanguageDialog/languageDialog.module.scss
Due to the addition of language selection, the selector's style needs to be modified.
> fix: Fix language select

- packages/neuron-ui/src/components/HardwareSign/hooks.ts
Refer to https://github.com/Magickbase/neuron-public-issues/issues/358
Add `transfer-to-sudt` and `withdraw-cheque` cases for hardware sign.
> fix: Add `transfer-to-sudt` and `withdraw-cheque` for hardware sign.

- CHANGELOG.md
- lerna.json
- package.json
- packages/neuron-ui/package.json
- packages/neuron-wallet/package.json
- [CKB@v0.114.0](https://github.com/nervosnetwork/ckb/releases/tag/v0.114.0) was released on Feb. 29st, 2024. This version of CKB node is now bundled and preconfigured in Neuron.
- [CKB Light Client@v0.3.6](https://github.com/nervosnetwork/ckb-light-client/releases/tag/v0.3.6) was released on Feb. 8th, 2024. This version of CKB Light Client is now bundled and preconfigured in Neuron
Block before `0x397d7d41167051cab2bf1610e334ad3aa5cf612e2cd442f71b91422e0361141e`(at height `12,450,084`) will be skipped in validation.(https://github.com/nervosnetwork/neuron/pull/3077)
---
Good day, good Neuron, packed with exciting new features and enhancements to elevate your transaction experience!
With support for Cell Management, Chained Transactions, and detailed viewing options, managing your …
> Release v0.114.2

- packages/neuron-wallet/package.json
- yarn.lock
issue: https://github.com/Magickbase/neuron-public-issues/issues/186
> feat: Remove unnecessary package electron-build-env

- packages/neuron-wallet/src/services/settings.ts
- packages/neuron-wallet/tests/services/setting.test.ts
Refer to https://github.com/Magickbase/neuron-public-issues/issues/385
> fix: Fix menu when switch language.

- package.json
- yarn.lock
Refer to https://github.com/Magickbase/neuron-public-issues/issues/389
> fix: Fix socket hang

- packages/neuron-ui/src/components/GeneralSetting/generalSetting.module.scss
- packages/neuron-ui/src/components/SyncStatus/index.tsx
- packages/neuron-ui/src/components/SyncStatus/syncStatus.module.scss
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/es.json
- packages/neuron-ui/src/locales/fr.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/widgets/Icons/Question.svg
- packages/neuron-ui/src/widgets/Icons/icon.tsx
- packages/neuron-ui/src/widgets/Tooltip/tooltip.module.scss
Refer to https://github.com/Magickbase/neuron-public-issues/issues/137
1. Add a help link https://neuron.magickbase.com/posts/issues/2893 when sync failed
2. Add prompt for left time.
> feat: Add help link for sync failed.

- .github/workflows/update_wallet_env.yml
Fix https://github.com/nervosnetwork/neuron/pull/3172#issuecomment-2134873465
> fix: Fix action branch sha

- packages/neuron-ui/src/components/CellManagement/cellManagement.module.scss
- packages/neuron-ui/src/components/CellManagement/index.tsx
https://github.com/Magickbase/neuron-public-issues/issues/370
> feat: Add tooltip/title so function of icon buttons will be clear

- packages/neuron-ui/src/components/GeneralSetting/index.tsx
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/es.json
- packages/neuron-ui/src/locales/fr.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
Refer to https://github.com/Magickbase/neuron-public-issues/issues/397#issuecomment-2182108426
> fix: For windows os the user need to start the Neuron manually after installed.

- packages/neuron-ui/src/components/MultisigAddress/index.tsx
- packages/neuron-ui/src/components/Settings/index.tsx
- packages/neuron-ui/src/components/SignAndVerify/index.tsx
- packages/neuron-ui/src/containers/LockWindow/index.tsx
- packages/neuron-ui/src/containers/Main/index.tsx
- packages/neuron-ui/src/containers/Navbar/index.tsx
Fix https://github.com/Magickbase/neuron-public-issues/issues/408
> fix: Move the i18n subscribe to the entry of the page.

- packages/neuron-ui/src/components/MultisigAddress/index.tsx
- packages/neuron-ui/src/components/MultisigAddress/multisigAddress.module.scss
issue: https://github.com/Magickbase/neuron-public-issues/issues/404
https://github.com/nervosnetwork/neuron/assets/11756869/5c367b96-7ca6-4e1a-9189-b9c173a317ce
> feat: Make Mulsig Addresses's More button more intuitive

- packages/neuron-ui/src/components/CellInfoDialog/cellInfoDialog.module.scss
issue: https://github.com/Magickbase/neuron-public-issues/issues/383
> fix: Capacity green progress bar

- packages/neuron-wallet/package.json
- packages/neuron-wallet/src/utils/ckb-rpc.ts
- packages/neuron-wallet/src/utils/rpc-request.ts
- packages/neuron-wallet/tests/controllers/sync-api.test.ts
- packages/neuron-wallet/tests/utils/rpc-request.test.ts
- yarn.lock
issue: https://github.com/Magickbase/neuron-public-issues/issues/409
> feat: Remove undici

- packages/neuron-ui/src/components/NervosDAO/hooks.ts
- packages/neuron-ui/src/components/SUDTUpdateDialog/index.tsx
- packages/neuron-ui/src/components/SpecialAssetList/index.tsx
- packages/neuron-ui/src/states/stateProvider/actionCreators/app.ts
- packages/neuron-ui/src/states/stateProvider/reducer.ts
Fixed https://github.com/Magickbase/neuron-public-issues/issues/417#issuecomment-2264996336
> fix: Use GlobalAlertDialog to replace Notification

- packages/neuron-ui/src/components/Receive/index.tsx
issue: https://github.com/Magickbase/neuron-public-issues/issues/437
> fix: Hide 'View Private Key' when Neuron connects to a hardware wallet

- packages/neuron-ui/src/components/DepositDialog/index.tsx
issue: https://github.com/Magickbase/neuron-public-issues/issues/431
https://github.com/user-attachments/assets/a02bdca6-83e7-4ef9-bd05-683bf5968b2b
> fix: cursor move to last position

- packages/neuron-ui/src/components/MultisigAddress/index.tsx
- packages/neuron-ui/src/components/MultisigAddressNervosDAODialog/index.tsx
- packages/neuron-ui/src/components/SUDTSend/hooks.ts
- packages/neuron-ui/src/locales/ar.json
- packages/neuron-ui/src/locales/en.json
- packages/neuron-ui/src/locales/es.json
- packages/neuron-ui/src/locales/fr.json
- packages/neuron-ui/src/locales/zh-tw.json
- packages/neuron-ui/src/locales/zh.json
- packages/neuron-ui/src/types/App/index.d.ts
- packages/neuron-ui/src/utils/enums.ts
- packages/neuron-wallet/tests/services/anyone-can-pay.test.ts
- packages/neuron-wallet/tests/services/cells.test.ts
issue: 
- https://github.com/Magickbase/neuron-public-issues/issues/455
> fix: Multisig dao withdraw hasCkbBalance search wallet balance is wrong

- packages/neuron-ui/src/containers/Navbar/index.tsx
- packages/neuron-wallet/src/block-sync-renderer/sync/full-synchronizer.ts
- packages/neuron-wallet/src/block-sync-renderer/sync/light-synchronizer.ts
- packages/neuron-wallet/src/services/node.ts
issue:
- https://github.com/Magickbase/neuron-public-issues/issues/454
> fix: display a message if the external node is not running with --indexer
